<Project>
    <PropertyGroup>
        <!-- IMPORTANT: Should point to <Barotrauma_Install>\LocalMods\<MyModName>\ -->
        <!-- IMPORTANT: ModDeplyDir Path must end with '\' -->
        <ProjectName>SOS</ProjectName>
        <ModDeployDir>D:\ProgramS\ProgramFiles\Steam\steamapps\common\Barotrauma\LocalMods\$(ProjectName)\</ModDeployDir>
        <AssemblyName>Retype.SOS</AssemblyName>
    </PropertyGroup>
    <Import Project="CheckLocalization.targets" />
</Project>