<Project>
    <PropertyGroup>
        <ProjectName>SOS</ProjectName>
        <AssemblyName>Retype.SOS</AssemblyName>
    </PropertyGroup>

    <Import Project="UserBuildData.props" Condition="Exists('UserBuildData.props')" />

    <ItemGroup>
        <PackageReference Include="FluentResults" Version="3.16.0" />
    </ItemGroup>

    <Import Project="CheckLocalization.targets" />
</Project>