// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using Barotrauma.LuaCs;

namespace SOS
{
    /// <summary>
    /// Static facade for S.O.S mod API extensibility points.
    /// </summary>
    /// <remarks>
    /// Provides registration, retrieval, and removal mechanisms for mod components including sections, tabs, configs,
    /// prefab providers, and window profiles. Uses <see cref="SortedFactory{T}"/> for ordered discovery and instance caching.
    /// Event-related methods (<see cref="On"/>, <see cref="Off"/>, <see cref="Emit"/>, <see cref="SetState"/>,
    /// <see cref="GetState"/>) utilize the internal <see cref="EventBus"/> with priority-based execution ordering via
    /// <see cref="EventPriority"/>. Thread-safety: registry dictionaries are protected by monitor locks; event handlers
    /// execute outside locks, guaranteeing reentrancy safety and zero deadlocks.
    /// </remarks>
    /// <example>
    /// <code>
    /// // Register a custom stat section
    /// API.RegisterSection(new MyStatSection(), "my-section", 5.0);
    ///
    /// // Get a registered section
    /// var section = API.GetSection<MyStatSection>("my-section");
    ///
    /// // Subscribe to an event
    /// API.On("key", () => Console.WriteLine("event fired"), EventPriority.UI);
    ///
    /// // Emit an event
    /// API.Emit("key");
    /// </code>
    /// </example>
    public static class API
    {
        private static EventBus eventBus = new();

        // Factories  
        private static readonly SortedFactory<ISOSStatSection> _sectionFactories = new();
        private static readonly SortedFactory<ISOSTab> _tabFactories = new();
        private static readonly SortedFactory<ISOSConfig> _configFactories = new();
        private static readonly SortedFactory<ISOSPrefab> _prefabFactories = new();
        private static readonly SortedFactory<ISOSWindowProfile> _profileFactories = new();

        private static bool _scanned = false;

        #region Info Sections

        /// <summary>
        /// Registers a <paramref name="obj"/> as a stat section of type <typeparamref name="T"/> managed by <see cref="SortedFactory{T}"/>.
        /// </summary>
        /// <param name="obj">The instance or factory delegate to register. Can be an object, a <see cref="Type"/>, a <see cref="Func{T}"/> factory, or an existing instance.</param>
        /// <param name="id">Optional unique identifier. If null, the type's full name is used.</param>
        /// <param name="order">Registration order determines display priority. Lower values appear first. Defaults to 0.0.</param>
        /// <param name="active">Whether the section is initially active. Defaults to true.</param>
        /// <returns><c>true</c> if registration succeeded; otherwise, <c>false</c> if <paramref name="obj"/> is null or fails type checks.</returns>
        /// <remarks>
        /// Registered sections are discoverable via <see cref="GetSection"/> or <see cref="GetAllSections"/>.
        /// Instances are cached based on the <paramref name="keepInstance"/> flag in retrieval methods.
        /// </remarks>
        public static bool RegisterSection(object obj, string? id = null, double order = 0.0, bool active = true)
            => _sectionFactories.Register(obj, id, order, active);

        public static bool ActivateSection(string id) => _sectionFactories.SetActive(id, true);
        /// <summary>
        /// Activates the stat section identified by <paramref name="id"/>.
        /// </summary>
        /// <param name="id">The unique identifier of the section to activate.</param>
        /// <returns><c>true</c> if the section was found and activated; <c>false</c> if not found.</returns>
        /// <remarks>
        /// If the section is already active, this method returns <c>true</c> without side effects.
        /// </remarks>
        public static bool DeactivateSection(string id) => _sectionFactories.SetActive(id, false);
        /// <summary>
        /// Deactivates the stat section identified by <paramref name="id"/>.
        /// </summary>
        /// <param name="id">The unique identifier of the section to deactivate.</param>
        /// <returns><c>true</c> if the section was found and deactivated; <c>false</c> if not found.</returns>
        /// <remarks>
        /// If the section is already inactive, this method returns <c>true</c> without side effects.
        /// </remarks>

        public static T? GetSection<T>(string id, bool keepInstance = true)
            => GetSection(id, keepInstance) is T t ? t : default;
        /// <summary>
        /// Retrieves a stat section of type <typeparamref name="T"/> by its identifier.
        /// </summary>
        /// <typeparam name="T">The expected type of the section; must match the registered type.</typeparam>
        /// <param name="id">The unique identifier of the section to retrieve.</param>
        /// <param name="keepInstance">If <c>true</c>, the returned instance is cached for subsequent calls. If <c>false>, a new instance is created each time via the factory.</param>
        /// <returns>The section instance if found; otherwise, <c>default</c> (<c>null</c> for reference types).</returns>
        /// <remarks>
        /// The keepInstance flag controls whether the instance is cached in the internal dictionary for faster subsequent access.
        /// </remarks>

        public static ISOSStatSection? GetSection(string id, bool keepInstance = true)
            => _sectionFactories.Get(id, keepInstance);
        /// <summary>
        /// Retrieves a stat section by its identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the section to retrieve.</param>
        /// <param name="keepInstance">If <c>true</c>, the returned instance is cached for subsequent calls.</param>
        /// <returns>The <see cref="ISOSStatSection"/> instance if found; otherwise, <c>null</c>.</returns>
        /// <remarks>
        /// Uses the internal <see cref="SortedFactory{T}.Get(string, bool)"/> method which may instantiate the section via its factory if not already cached.
        /// </remarks>

        public static IEnumerable<ISOSStatSection> GetAllSections(bool keepInstance = true)
            => _sectionFactories.GetAll(keepInstance).Select(t => t.Instance);
        /// <summary>
        /// Retrieves all registered stat sections.
        /// </summary>
        /// <param name="keepInstance">If <c>true</c>, instances are cached for subsequent calls. If <c>false>, each call creates new instances via factories.</param>
        /// <returns>An enumerable of all <see cref="ISOSStatSection"/> instances.</returns>
        /// <remarks>
        /// The order of sections follows the registration order within each <see cref="SortedFactory{T}"/>, sorted by their registration order value.
        /// </remarks>

        public static bool RemoveSection(string id, bool onlyInstance = false)
            => _sectionFactories.Remove(id, onlyInstance);
        /// <summary>
        /// Removes a stat section by its identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the section to remove.</param>
        /// <param name="onlyInstance">If <c>true</c>, only the cached instance is removed without removing the registration. If <c>false</c>, both the registration and cached instance are removed.</param>
        /// <returns><c>true</c> if the section was found and removed; <c>false</c> if not found.</returns>
        /// <remarks>
        /// When <paramref name="onlyInstance"/> is <c>false</c> (default), the registration is completely removed from the factory,
        /// and if a cached instance exists, it is disposed (if <see cref="IDisposable"/>).
        /// </remarks>

        #endregion

        #region Tabs

        /// <summary>
        /// Registers a <paramref name="obj"/> as a tab of type <typeparamref name="T"/> managed by <see cref="SortedFactory{T}"/>.
        /// </summary>
        /// <param name="obj">The instance or factory delegate to register. Can be an object, a <see cref="Type"/>, a <see cref="Func{T}"/> factory, or an existing instance.</param>
        /// <param name="id">Optional unique identifier. If null, the type's full name is used.</param>
        /// <param name="order">Registration order determines display priority. Lower values appear first. Defaults to 0.0.</param>
        /// <param name="active">Whether the tab is initially active. Defaults to true.</param>
        /// <returns><c>true</c> if registration succeeded; otherwise, <c>false</c> if <paramref name="obj"/> is null or fails type checks.</returns>
        /// <remarks>
        /// Registered tabs are discoverable via <see cref="GetTab"/> or <see cref="GetAllTabs"/>.
        /// Instances are cached based on the <paramref name="keepInstance"/> flag in retrieval methods.
        /// </remarks>
        public static bool RegisterTab(object obj, string? id = null, double order = 0.0, bool active = true)
            => _tabFactories.Register(obj, id, order, active);

        /// <summary>
        /// Activates the tab identified by <paramref name="id"/>.
        /// </summary>
        /// <param name="id">The unique identifier of the tab to activate.</param>
        /// <returns><c>true</c> if the tab was found and activated; <c>false</c> if not found.</returns>
        /// <remarks>
        /// If the tab is already active, this method returns <c>true</c> without side effects.
        /// </remarks>
        public static bool ActivateTab(string id) => _tabFactories.SetActive(id, true);
        /// <summary>
        /// Deactivates the tab identified by <paramref name="id"/>.
        /// </summary>
        /// <param name="id">The unique identifier of the tab to deactivate.</param>
        /// <returns><c>true</c> if the tab was found and deactivated; <c>false</c> if not found.</returns>
        /// <remarks>
        /// If the tab is already inactive, this method returns <c>true</c> without side effects.
        /// </remarks>
        public static bool DeactivateTab(string id) => _tabFactories.SetActive(id, false);

        /// <summary>
        /// Retrieves a tab of type <typeparamref name="T"/> by its identifier.
        /// </summary>
        /// <typeparam name="T">The expected type of the tab; must match the registered type.</typeparam>
        /// <param name="id">The unique identifier of the tab to retrieve.</param>
        /// <param name="keepInstance">If <c>true</c>, the returned instance is cached for subsequent calls. If <c>false>, a new instance is created each time via the factory.</param>
        /// <returns>The tab instance if found; otherwise, <c>default</c> (<c>null</c> for reference types).</returns>
        /// <remarks>
        /// The keepInstance flag controls whether the instance is cached in the internal dictionary for faster subsequent access.
        /// </remarks>
        public static T? GetTab<T>(string id, bool keepInstance = true)
            => GetTab(id, keepInstance) is T t ? t : default;

        /// <summary>
        /// Retrieves a tab by its identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the tab to retrieve.</param>
        /// <param name="keepInstance">If <c>true</c>, the returned instance is cached for subsequent calls.</param>
        /// <returns>The <see cref="ISOSTab"/> instance if found; otherwise, <c>null</c>.</returns>
        /// <remarks>
        /// Uses the internal <see cref="SortedFactory{T}.Get(string, bool)"/> method which may instantiate the tab via its factory if not already cached.
        /// </remarks>
        public static ISOSTab? GetTab(string id, bool keepInstance = true)
            => _tabFactories.Get(id, keepInstance);

        /// <summary>
        /// Retrieves all registered tabs.
        /// </summary>
        /// <param name="keepInstance">If <c>true</c>, instances are cached for subsequent calls. If <c>false>, each call creates new instances via factories.</param>
        /// <returns>An enumerable of all <see cref="ISOSTab"/> instances.</returns>
        /// <remarks>
        /// The order of tabs follows the registration order within the <see cref="SortedFactory{T}"/>, sorted by their registration order value.
        /// </remarks>
        public static IEnumerable<ISOSTab> GetAllTabs(bool keepInstance = true)
            => _tabFactories.GetAll(keepInstance).Select(t => t.Instance);

        /// <summary>
        /// Removes a tab by its identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the tab to remove.</param>
        /// <param name="onlyInstance">If <c>true</c>, only the cached instance is removed without removing the registration. If <c>false</c>, both the registration and cached instance are removed.</param>
        /// <returns><c>true</c> if the tab was found and removed; <c>false</c> if not found.</returns>
        /// <remarks>
        /// When <paramref name="onlyInstance"/> is <c>false</c> (default), the registration is completely removed from the factory,
        /// and if a cached instance exists, it is disposed (if <see cref="IDisposable"/>).
        /// </remarks>
        public static bool RemoveTab(string id, bool onlyInstance = false)
            => _tabFactories.Remove(id, onlyInstance);

        #endregion

        #region Configs

        /// <summary>
        /// Registers a <paramref name="obj"/> as a config of type <typeparamref name="T"/> managed by <see cref="SortedFactory{T}"/>.
        /// </summary>
        /// <param name="obj">The instance or factory delegate to register. Can be an object, a <see cref="Type"/>, a <see cref="Func{T}"/> factory, or an existing instance.</param>
        /// <param name="id">Optional unique identifier. If null, the type's full name is used.</param>
        /// <param name="order">Registration order determines display priority. Lower values appear first. Defaults to 0.0.</param>
        /// <param name="active">Whether the config is initially active. Defaults to true.</param>
        /// <returns><c>true</c> if registration succeeded; otherwise, <c>false</c> if <paramref name="obj"/> is null or fails type checks.</returns>
        /// <remarks>
        /// Registered configs are discoverable via <see cref="GetConfig"/> or <see cref="GetAllConfigs"/>.
        /// </remarks>
        public static bool RegisterConfig(object obj, string? id = null, double order = 0.0, bool active = true)
            => _configFactories.Register(obj, id, order, active);

        /// <summary>
        /// Activates the config identified by <paramref name="id"/>.
        /// </summary>
        /// <param name="id">The unique identifier of the config to activate.</param>
        /// <returns><c>true</c> if the config was found and activated; <c>false</c> if not found.</returns>
        /// <remarks>
        /// If the config is already active, this method returns <c>true</c> without side effects.
        /// </remarks>
        public static bool ActivateConfig(string id) => _configFactories.SetActive(id, true);
        /// <summary>
        /// Deactivates the config identified by <paramref name="id"/>.
        /// </summary>
        /// <param name="id">The unique identifier of the config to deactivate.</param>
        /// <returns><c>true</c> if the config was found and deactivated; <c>false</c> if not found.</returns>
        /// <remarks>
        /// If the config is already inactive, this method returns <c>true</c> without side effects.
        /// </remarks>
        public static bool DeactivateConfig(string id) => _configFactories.SetActive(id, false);

        /// <summary>
        /// Retrieves a config of type <typeparamref name="T"/> by its identifier.
        /// </summary>
        /// <typeparam name="T">The expected type of the config; must match the registered type.</typeparam>
        /// <param name="id">The unique identifier of the config to retrieve.</param>
        /// <param name="keepInstance">If <c>true</c>, the returned instance is cached for subsequent calls. If <c>false>, a new instance is created each time via the factory.</param>
        /// <returns>The config instance if found; otherwise, <c>default</c> (<c>null</c> for reference types).</returns>
        /// <remarks>
        /// The keepInstance flag controls whether the instance is cached in the internal dictionary for faster subsequent access.
        /// </remarks>
        public static T? GetConfig<T>(string id, bool keepInstance = true)
            => GetConfig(id, keepInstance) is T t ? t : default;

        /// <summary>
        /// Retrieves a config by its identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the config to retrieve.</param>
        /// <param name="keepInstance">If <c>true</c>, the returned instance is cached for subsequent calls.</param>
        /// <returns>The <see cref="ISOSConfig"/> instance if found; otherwise, <c>null</c>.</returns>
        /// <remarks>
        /// Uses the internal <see cref="SortedFactory{T}.Get(string, bool)"/> method which may instantiate the config via its factory if not already cached.
        /// </remarks>
        public static ISOSConfig? GetConfig(string id, bool keepInstance = true)
            => _configFactories.Get(id, keepInstance);

        /// <summary>
        /// Retrieves all registered configs.
        /// </summary>
        /// <param name="keepInstance">If <c>true</c>, instances are cached for subsequent calls. If <c>false>, each call creates new instances via factories.</param>
        /// <returns>An enumerable of all <see cref="ISOSConfig"/> instances.</returns>
        /// <remarks>
        /// The order of configs follows the registration order within the <see cref="SortedFactory{T}"/>, sorted by their registration order value.
        /// </remarks>
        public static IEnumerable<ISOSConfig> GetAllConfigs(bool keepInstance = true)
            => _configFactories.GetAll(keepInstance).Select(t => t.Instance);

        /// <summary>
        /// Removes a config by its identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the config to remove.</param>
        /// <param name="onlyInstance">If <c>true</c>, only the cached instance is removed without removing the registration. If <c>false</c>, both the registration and cached instance are removed.</param>
        /// <returns><c>true</c> if the config was found and removed; <c>false</c> if not found.</returns>
        /// <remarks>
        /// When <paramref name="onlyInstance"/> is <c>false</c> (default), the registration is completely removed from the factory,
        /// and if a cached instance exists, it is disposed (if <see cref="IDisposable"/>).
        /// </remarks>
        public static bool RemoveConfig(string id, bool onlyInstance = false)
            => _configFactories.Remove(id, onlyInstance);

        #endregion

        #region Prefab Providers

        /// <summary>
        /// Registers a <paramref name="obj"/> as a prefab provider of type <typeparamref name="T"/> managed by <see cref="SortedFactory{T}"/>.
        /// </summary>
        /// <param name="obj">The instance or factory delegate to register. Can be an object, a <see cref="Type"/>, a <see cref="Func{T}"/> factory, or an existing instance.</param>
        /// <param name="id">Optional unique identifier. If null, the type's full name is used.</param>
        /// <param name="order">Registration order determines display priority. Lower values appear first. Defaults to 0.0.</param>
        /// <param name="active">Whether the provider is initially active. Defaults to true.</param>
        /// <returns><c>true</c> if registration succeeded; otherwise, <c>false</c> if <paramref name="obj"/> is null or fails type checks.</returns>
        /// <remarks>
        /// Registered prefab providers are discoverable via <see cref="GetPrefabProvider"/> or <see cref="GetAllPrefabProviders"/>.
        /// </remarks>
        public static bool RegisterPrefabProvider(object obj, string? id = null, double order = 0.0, bool active = true)
            => _prefabFactories.Register(obj, id, order, active);

        /// <summary>
        /// Activates the prefab provider identified by <paramref name="id"/>.
        /// </summary>
        /// <param name="id">The unique identifier of the provider to activate.</param>
        /// <returns><c>true</c> if the provider was found and activated; <c>false</c> if not found.</returns>
        /// <remarks>
        /// If the provider is already active, this method returns <c>true</c> without side effects.
        /// </remarks>
        public static bool ActivatePrefabProvider(string id) => _prefabFactories.SetActive(id, true);
        /// <summary>
        /// Deactivates the prefab provider identified by <paramref name="id"/>.
        /// </summary>
        /// <param name="id">The unique identifier of the provider to deactivate.</param>
        /// <returns><c>true</c> if the provider was found and deactivated; <c>false</c> if not found.</returns>
        /// <remarks>
        /// If the provider is already inactive, this method returns <c>true</c> without side effects.
        /// </remarks>
        public static bool DeactivatePrefabProvider(string id) => _prefabFactories.SetActive(id, false);

        /// <summary>
        /// Retrieves a prefab provider of type <typeparamref name="T"/> by its identifier.
        /// </summary>
        /// <typeparam name="T">The expected type of the provider; must match the registered type.</typeparam>
        /// <param name="id">The unique identifier of the provider to retrieve.</param>
        /// <param name="refresh">If <c>true</c>, forces re-creation of the instance even if cached. If <c=false>, uses cached instance if available.</param>
        /// <returns>The provider instance if found; otherwise, <c>default</c> (<c>null</c> for reference types).</returns>
        /// <remarks>
        /// Defaults to <c>true</c> to ensure the latest instance is returned, useful when providers may have been modified at runtime.
        /// </remarks>
        public static T? GetPrefabProvider<T>(string id, bool refresh = true)
            => GetPrefabProvider(id, refresh) is T t ? t : default;

        /// <summary>
        /// Retrieves a prefab provider by its identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the provider to retrieve.</param>
        /// <param name="keepInstance">If <c>true</c>, the returned instance is cached for subsequent calls. If <c>false>, a new instance is created each time via the factory.</param>
        /// <returns>The <see cref="ISOSPrefab"/> instance if found; otherwise, <c>null</c>.</returns>
        /// <remarks>
        /// Uses the internal <see cref="SortedFactory{T}.Get(string, bool)"/> method which may instantiate the provider via its factory if not already cached.
        /// </remarks>
        public static ISOSPrefab? GetPrefabProvider(string id, bool keepInstance = true)
            => _prefabFactories.Get(id, keepInstance);

        /// <summary>
        /// Retrieves all registered prefab providers.
        /// </summary>
        /// <param name="keepInstance">If <c>true</c>, instances are cached for subsequent calls. If <c>false>, each call creates new instances via factories.</param>
        /// <returns>An enumerable of all <see cref="ISOSPrefab"/> instances.</returns>
        /// <remarks>
        /// The order of providers follows the registration order within the <see cref="SortedFactory{T}"/>, sorted by their registration order value.
        /// </remarks>
        public static IEnumerable<ISOSPrefab> GetAllPrefabProviders(bool keepInstance = true)
            => _prefabFactories.GetAll(keepInstance).Select(t => t.Instance);

        /// <summary>
        /// Removes a prefab provider by its identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the provider to remove.</param>
        /// <param name="onlyInstance">If <c>true</c>, only the cached instance is removed without removing the registration. If <c>false</c>, both the registration and cached instance are removed.</param>
        /// <returns><c>true</c> if the provider was found and removed; <c>false</c> if not found.</returns>
        /// <remarks>
        /// When <paramref name="onlyInstance"/> is <c>false</c> (default), the registration is completely removed from the factory,
        /// and if a cached instance exists, it is disposed (if <see cref="IDisposable"/>).
        /// </remarks>
        public static bool RemovePrefabProvider(string id, bool onlyInstance = false)
            => _prefabFactories.Remove(id, onlyInstance);

        #endregion

        #region Window Profiles

        /// <summary>
        /// Registers a <paramref name="obj"/> as a window profile of type <typeparamref name="T"/> managed by <see cref="SortedFactory{T}"/>.
        /// </summary>
        /// <param name="obj">The instance or factory delegate to register. Can be an object, a <see cref="Type"/>, a <see cref="Func{T}"/> factory, or an existing instance.</param>
        /// <param name="id">Optional unique identifier. If null, the type's full name is used.</param>
        /// <param name="order">Registration order determines display priority. Lower values appear first. Defaults to 0.0.</param>
        /// <param name="active">Whether the profile is initially active. Defaults to true.</param>
        /// <returns><c>true</c> if registration succeeded; otherwise, <c>false</c> if <paramref name="obj"/> is null or fails type checks.</returns>
        /// <remarks>
        /// Registered window profiles are discoverable via <see cref="GetWindowProfile"/> or <see cref="GetAllWindowProfiles"/>.
        /// </remarks>
        public static bool RegisterWindowProfile(object obj, string? id = null, double order = 0.0, bool active = true)
            => _profileFactories.Register(obj, id, order, active);

        /// <summary>
        /// Activates the window profile identified by <paramref name="id"/>.
        /// </summary>
        /// <param name="id">The unique identifier of the profile to activate.</param>
        /// <returns><c>true</c> if the profile was found and activated; <c>false</c> if not found.</returns>
        /// <remarks>
        /// If the profile is already active, this method returns <c>true</c> without side effects.
        /// </remarks>
        public static bool ActivateWindowProfile(string id) => _profileFactories.SetActive(id, true);
        /// <summary>
        /// Deactivates the window profile identified by <paramref name="id"/>.
        /// </summary>
        /// <param name="id">The unique identifier of the profile to deactivate.</param>
        /// <returns><c>true</c> if the profile was found and deactivated; <c>false</c> if not found.</returns>
        /// <remarks>
        /// If the profile is already inactive, this method returns <c>true</c> without side effects.
        /// </remarks>
        public static bool DeactivateWindowProfile(string id) => _profileFactories.SetActive(id, false);

        /// <summary>
        /// Retrieves a window profile of type <typeparamref name="T"/> by its identifier.
        /// </summary>
        /// <typeparam name="T">The expected type of the profile; must match the registered type.</typeparam>
        /// <param name="id">The unique identifier of the profile to retrieve.</param>
        /// <param name="keepInstance">If <c>true</c>, the returned instance is cached for subsequent calls. Note: defaults to <c>false</c> for profiles.</param>
        /// <returns>The profile instance if found; otherwise, <c>default</c> (<c>null</c> for reference types).</returns>
        /// <remarks>
        /// Uses the internal <see cref="SortedFactory{T}.Get(string, bool)"/> method. If no ID is provided, returns the first profile.
        /// </remarks>
        public static T? GetWindowProfile<T>(string id, bool keepInstance = false)
            => GetWindowProfile(id, keepInstance) is T t ? t : default;

        /// <summary>
        /// Retrieves a window profile by its identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the profile to retrieve. If <c>null</c> or empty, returns the first profile.</param>
        /// <param name="keepInstance">If <c>true</c>, the returned instance is cached for subsequent calls. Defaults to <c>false</c>.</param>
        /// <returns>The <see cref="ISOSWindowProfile"/> instance if found; otherwise, <c>null</c>.</returns>
        /// <remarks>
        /// Complex lookup logic: if the profile is not found, a warning is logged and the default profile is attempted.
        /// </remarks>
        public static ISOSWindowProfile? GetWindowProfile(string? id, bool keepInstance = false)
        {
            ISOSWindowProfile? v;
            if (string.IsNullOrEmpty(id)) v = _profileFactories.First(keepInstance);
            else
            {
                Logger.LogDebug($"GetWindowProfile >> id: '{id}'", level: LogLevel.Trace);
                v = _profileFactories.Get(id, keepInstance);
                if (v == null)
                {
                    Logger.LogWarning("[SOS] Profile not encountered. Trying to use default profile.");
                    v = _profileFactories.First();
                }
                Logger.LogDebug($"GetWindowProfile >> Name: '{v?.DisplayName ?? "null"}'", level: LogLevel.Trace);
            }
            if (v == null)
            {
                var color = Microsoft.Xna.Framework.Color.LightSkyBlue;
                Logger.LogDebugError($"[SOS] No one profile encountered.\n => Profile list: {string.Join(',', GetAllWindowProfiles().ToList().Select(p => p.DisplayName))}\n => Profile _dict => {string.Join(',', _profileFactories.GetSorted().Select(f => $"[{f.Id}, {f.Order}]"))}");
                Logger.LogReleaseError($"[SOS] No one profile encountered. Try reinstall 'S.O.S - Standard Operation Schematics' Mod, report that in steam mod page or create an issue on Git project(‖color:{color.R},{color.G},{color.B}‖https://github.com/retype15/SOS‖end‖).");
            }
            return v;
        }

        /// <summary>
        /// Retrieves all registered window profiles.
        /// </summary>
        /// <param name="keepInstance">If <c>true</c>, instances are cached for subsequent calls. If <c>false>, each call creates new instances via factories.</param>
        /// <returns>An enumerable of all <see cref="ISOSWindowProfile"/> instances.</returns>
        /// <remarks>
        /// The order of profiles follows the registration order within the <see cref="SortedFactory{T}"/>, sorted by their registration order value.
        /// </remarks>
        public static IEnumerable<ISOSWindowProfile> GetAllWindowProfiles(bool keepInstance = false)
            => _profileFactories.GetAll(keepInstance).Select(t => t.Instance);

        /// <summary>
        /// Removes a window profile by its identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the profile to remove.</param>
        /// <param name="onlyInstance">If <c>true</c>, only the cached instance is removed without removing the registration. If <c>false</c>, both the registration and cached instance are removed.</param>
        /// <returns><c>true</c> if the profile was found and removed; <c>false</c> if not found.</returns>
        /// <remarks>
        /// When <paramref name="onlyInstance"/> is <c>false</c> (default), the registration is completely removed from the factory,
        /// and if a cached instance exists, it is disposed (if <see cref="IDisposable"/>).
        /// </remarks>
        public static bool RemoveWindowProfile(string id, bool onlyInstance = false)
            => _profileFactories.Remove(id, onlyInstance);

        #endregion

        #region EventBus Facade

        /// <summary>
        /// Subscribes a callback to the specified event channel with priority-based execution ordering.
        /// </summary>
        /// <typeparam name="T">The payload type associated with the event (use <c>Action</c> for event-only signals).</typeparam>
        /// <param name="key">The unique event identifier channel (see <see cref="CommKeys"/>).</param>
        /// <param name="handler">The delegate to invoke when the event is emitted.</param>
        /// <param name="order">The execution priority weight. Lower values execute earlier (see <see cref="EventPriority"/>).
        /// Values are normalized to 4 decimal places. Defaults to <see cref="EventPriority.Default"/> (<c>0.0</c>).</param>
        /// <remarks>
        /// Handlers are executed outside internal synchronization locks, guaranteeing reentrancy safety and zero deadlocks.
        /// To unsubscribe, use <see cref="Off"/> with the same key and handler, or specify an exact order with <see cref="Off{T}(string, Action{T}, double?, bool)"/>.
        /// </remarks>
        public static void On(string key, Action handler, double order = 0) => eventBus.On(key, handler, order);

        /// <summary>
        /// Subscribes a strongly-typed callback to the specified event channel with priority-based execution ordering.
        /// </summary>
        /// <typeparam name="T">The payload type associated with the event.</typeparam>
        /// <param name="key">The unique event identifier channel (see <see cref="CommKeys"/>).</param>
        /// <param name="handler">The delegate to invoke when the event is emitted.</param>
        /// <param name="order">The execution priority weight. Lower values execute earlier (see <see cref="EventPriority"/>).
        /// Values are normalized to 4 decimal places. Defaults to <see cref="EventPriority.Default"/> (<c>0.0</c>).</param>
        /// <remarks>
        /// Handlers are executed outside internal synchronization locks, guaranteeing reentrancy safety and zero deadlocks.
        /// </remarks>
        public static void On<T>(string key, Action<T> handler, double order = 0) => eventBus.On<T>(key, handler, order);

        /// <summary>
        /// Unsubscribes a previously registered handler from the specified event channel.
        /// </summary>
        /// <param name="key">The unique event identifier channel.</param>
        /// <param name="handler">The delegate to remove.</param>
        /// <param name="order">Optional. If specified, removes the handler only from the priority level matching <paramref name="order"/>.
        /// If <c>null</sub>, removes the handler from <b>all</b> priority levels.</param>
        /// <param name="removeState">If <c>true</c>, also removes any saved state associated with the key.</param>
        /// <remarks>
        /// <para>
        /// <c>Off(key, handler)</c>: Removes the handler from all priority levels where it was subscribed.
        /// </para>
        /// <para>
        /// <c>Off(key, handler, order)</c>: Targeted removal from a specific priority level.
        /// </para>
        /// </remarks>
        public static void Off(string key, Action handler, double? order = null, bool removeState = false) => eventBus.Off(key, handler, order, removeState);

        /// <summary>
        /// Unsubscribes a strongly-typed handler from the specified event channel.
        /// </summary>
        /// <typeparam name="T">The payload type associated with the event.</typeparam>
        /// <param name="key">The unique event identifier channel.</param>
        /// <param name="handler">The delegate to remove.</param>
        /// <param name="order">Optional. If specified, removes the handler only from the priority level matching <paramref name="order"/>.
        /// If <c>null</sub>, removes the handler from <b>all</b> priority levels.</param>
        /// <param name="removeState">If <c>true</c>, also removes any saved state associated with the key.</param>
        /// <remarks>
        /// <para>
        /// <c>Off<T>(key, handler)</c>: Removes the handler from all priority levels where it was subscribed.
        /// </para>
        /// <para>
        /// <c>Off<T>(key, handler, order)</c>: Targeted removal from a specific priority level.
        /// </para>
        /// </remarks>
        public static void Off<T>(string key, Action<T> handler, double? order = null, bool removeState = false) => eventBus.Off<T>(key, handler, order, removeState);

        /// <summary>
        /// Emits an event on the specified channel, optionally with a value and state management.
        /// </summary>
        /// <param name="key">The unique event identifier channel.</param>
        /// <remarks>
        /// <para><c>Emit(key)</c>: Emits with no value and no state change.</para>
        /// <para><c>Emit(key, order)</c>: Emits with an optional order parameter.</para>
        /// <para><c>Emit<T>(key, value)</c>: Emits a typed value.</para>
        /// <para><c>EmitRange(key, min, max)</c>: Emits within a range.</para>
        /// </remarks>
        public static bool Emit(string key) => eventBus.Emit(key, null);

        /// <summary>
        /// Emits an event on the specified channel with an optional order parameter.
        /// </summary>
        /// <param name="key">The unique event identifier channel.</param>
        /// <param name="order">Optional execution order override.</param>
        /// <returns><c>true</c> if the event was emitted to at least one handler; <c>false</c> otherwise.</returns>
        public static bool Emit(string key, double? order = null) => eventBus.Emit(key, order);

        /// <summary>
        /// Emits an event on the specified channel with a typed value and state management.
        /// </summary>
        /// <typeparam name="T">The type of the value to emit.</typeparam>
        /// <param name="key">The unique event identifier channel.</param>
        /// <param name="value">The value to emit.</param>
        /// <param name="order">Optional execution order. If <c>null</c>, uses the handler's registered order.</param>
        /// <param name="setState">If <c>true</c>, sets the state to the emitted value after firing.</param>
        /// <returns><c>true</c> if the event was emitted to at least one handler; <c>false</c> otherwise.</returns>
        public static bool Emit<T>(string key, T value, double? order = null, bool setState = true) => eventBus.Emit<T>(key, value, order, setState);

        /// <summary>
        /// Emits an event on the specified channel within a priority range, invoking all handlers whose orders fall between <paramref name="min"/> and <paramref name="max"/>.
        /// </summary>
        /// <param name="key">The unique event identifier channel.</param>
        /// <param name="min">Minimum order (inclusive). Defaults to <see cref="double.MinValue"/>.</param>
        /// <param name="max">Maximum order (inclusive). Defaults to <see cref="double.MaxValue"/>.</param>
        /// <returns><c>true</c> if the event was emitted to at least one handler; <c>false</c> otherwise.</returns>
        public static bool EmitRange(string key, double min = double.MinValue, double max = double.MaxValue) => eventBus.Emit(key, min, max);

        /// <summary>
        /// Emits an event on the specified channel within a priority range with a typed value and optional state management.
        /// </summary>
        /// <typeparam name="T">The type of the value to emit.</typeparam>
        /// <param name="key">The unique event identifier channel.</param>
        /// <param name="value">The value to emit.</param>
        /// <param name="min">Minimum order (inclusive). Defaults to <see cref="double.MinValue"/>.</param>
        /// <param name="max">Maximum order (inclusive). Defaults to <see cref="double.MaxValue"/>.</param>
        /// <param name="setState">If <c>true</c>, sets the state to the emitted value after firing.</param>
        /// <returns><c>true</c> if the event was emitted to at least one handler; <c>false</c> otherwise.</returns>
        public static bool EmitRange<T>(string key, T value, double min = double.MinValue, double max = double.MaxValue, bool setState = true) => eventBus.Emit<T>(key, value, min, max, setState);

        /// <summary>
        /// Sets the state for a given key, optionally emitting the value as an event.
        /// </summary>
        /// <typeparam name="T">The type of the state value.</typeparam>
        /// <param name="key">The unique identifier for the state.</param>
        /// <param name="value">The value to set as state.</param>
        /// <param name="emit">If <c>true</c>, emits the value as an event after setting the state.</param>
        /// <remarks>
        /// State is stored internally and can be retrieved via <see cref="GetState{T}(string)"/>.
        /// </remarks>
        public static void SetState<T>(string key, T value, bool emit = false) => eventBus.SetState<T>(key, value, emit);

        /// <summary>
        /// Sets the state for a given key using a provider method.
        /// </summary>
        /// <typeparam name="T">The type of the state value.</typeparam>
        /// <param name="key">The unique identifier for the state.</param>
        /// <param name="method">A <see cref="Func{T}"/> delegate that returns the state value.</param>
        /// <param name="emit">If <c>true</c>, emits the resulting value as an event after invoking the method.</param>
        /// <remarks>
        /// The method is invoked each time <see cref="GetState{T}(string)"/> is called, allowing for dynamic state computation.
        /// </remarks>
        public static void SetState<T>(string key, Func<T> method, bool emit = false) => eventBus.SetState<T>(key, method, emit);

        /// <summary>
        /// Retrieves the current state value for the specified key.
        /// </summary>
        /// <typeparam name="T">The expected type of the state value.</typeparam>
        /// <param name="key">The unique identifier for the state.</param>
        /// <returns>The state value if found; otherwise, <c>default</c> (<c>null</c> for reference types).</returns>
        /// <remarks>
        /// State is set via <see cref="SetState{T}(string, T, bool)"/> or <see cref="SetState{T}(string, Func{T}, bool)"/>.
        /// If the stored type does not match <typeparamref name="T"/>, an exception is thrown.
        /// </remarks>
        public static T? GetState<T>(string key) => eventBus.GetState<T>(key);

        /// <summary>
        /// Removes the state associated with the specified key.
        /// </summary>
        /// <param name="key">The unique identifier of the state to remove.</param>
        /// <returns><c>true</c> if the state was found and removed; <c>false</c> if not found.</returns>
        /// <remarks>
        /// State removal does not affect event handlers subscribed via <see cref="On"/>.
        /// </remarks>
        public static bool RemoveState(string key) => eventBus.RemoveState(key);

        #endregion

        #region Internal helpers

        /// <summary>
        /// Initializes the SDK by auto-registering all mod components from the provided <see cref="IPluginManagementService"/>.
        /// </summary>
        /// <param name="pluginManagementService">The service used to discover implementing types via their <see cref="AutoRegisterAttribute"/>.</param>
        /// <remarks>
        /// This method is typically called once during mod loading. It scans for types decorated with <see cref="AutoRegisterAttribute"/>
        /// and registers them in the appropriate <see cref="SortedFactory{T}"/> registries.
        /// </remarks>
        internal static void Initialize(IPluginManagementService pluginManagementService)
        {
            if (_scanned) return;

            _sectionFactories.AutoRegister(pluginManagementService);
            _tabFactories.AutoRegister(pluginManagementService);
            _configFactories.AutoRegister(pluginManagementService);
            _prefabFactories.AutoRegister(pluginManagementService);
            _profileFactories.AutoRegister(pluginManagementService);

            _scanned = true;
        }

        /// <summary>
        /// Clears temporary instances from all registered factories, keeping only persistent instances.
        /// </summary>
        /// <remarks>
        /// Sections and prefab providers are cleared (instances disposed if <see cref="IDisposable"/>), while tabs are preserved.
        /// Useful for cleanup between game rounds or mod reload scenarios.
        /// </remarks>
        internal static void ClearTemporaryInstances()
        {
            _sectionFactories.Clear(true);
            _tabFactories.Clear(true);
            _prefabFactories.Clear(true);
            _profileFactories.Clear(true);
        }

        /// <summary>
        /// Clears all registrations and instances from all factories, resetting the SDK to its initial state.
        /// </summary>
        /// <remarks>
        /// All cached instances are disposed (if <see cref="IDisposable"/>), registrations are removed, and the internal scan flag is reset.
        /// This effectively reinitializes the SDK; typically called for mod unloading or full reload scenarios.
        /// </remarks>
        internal static void Clear()
        {
            _sectionFactories.Clear();
            _tabFactories.Clear();
            _configFactories.Clear();
            _prefabFactories.Clear();
            _profileFactories.Clear();
            _scanned = false;
            eventBus = new();
        }

        #endregion
    }
}
