// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using Barotrauma.LuaCs;

namespace SOS
{

    /// <summary>
    /// Primary static facade providing access to S.O.S. mod extensibility points, SOS module registries, prioritized event dispatching, and shared runtime state.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Architecture:</b>
    /// <list type="bullet">
    /// <item><description><b>SOS Module Registries:</b> Manages SOS modules: sections (<see cref="ISOSStatInfo"/>), tabs (<see cref="ISOSTab"/>), configs (<see cref="ISOSConfig"/>), prefab providers (<see cref="ISOSPrefab"/>), and window profiles (<see cref="ISOSWindowProfile"/>) with ordering and activation control.</description></item>
    /// <item><description><b>Prioritized Event Pipeline:</b> Provides thread-safe event publishing and subscription (<c>On"</c>, <c>Off"</c>, <c>Emit</c>) ordered deterministically across <see cref="EventPriority"/> tiers.</description></item>
    /// <item><description><b>Shared State:</b> Offers a lightweight, reactive key-value state store (<see cref="SetState{T}(string, T, bool)"/>, <see cref="GetState{T}(string)"/>) for cross-mod communication.</description></item>
    /// </list>
    /// </para>
    /// <para>
    /// <b>Thread-Safety &amp; Reentrancy:</b> Internal registry mutations are synchronized via monitor locks. Event callbacks execute outside internal locks, ensuring safe reentrant invocations and zero deadlocks.
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// // Registering an SOS module:
    /// API.RegisterTab(typeof(MyCustomTab), "MyMod.CustomTab", order: 10.0);
    /// 
    /// // Listening to target selection events:
    /// API.On&lt;Prefab?&gt;(CommKeys.SelectTarget, target => 
    /// {
    ///     Logger.LogDebug($"Target selected: {target?.Identifier}");
    /// }, EventPriority.UI);
    /// 
    /// // Reading shared state:
    /// var currentTarget = API.GetState&lt;Prefab?&gt;(CommKeys.SelectTarget);
    /// </code>
    /// </example>
    public static class API
    {
        private static EventBus eventBus = new();

        // Factories  
        private static readonly SortedFactory<ISOSStatInfo> SectionFactories = SortedFactory.GetOrInstantiate<ISOSStatInfo>();
        private static readonly SortedFactory<ISOSTab> TabFactories = SortedFactory.GetOrInstantiate<ISOSTab>();
        private static readonly SortedFactory<ISOSConfig> ConfigFactories = SortedFactory.GetOrInstantiate<ISOSConfig>();
        private static readonly SortedFactory<ISOSPrefab> PrefabFactories = SortedFactory.GetOrInstantiate<ISOSPrefab>();
        private static readonly SortedFactory<ISOSWindowProfile> ProfileFactories = SortedFactory.GetOrInstantiate<ISOSWindowProfile>();

        private static bool _scanned = false;

        #region Generic Factory accessor

        /// <summary>
        /// Gets the factory entry registered for contract <typeparamref name="T"/> under <paramref name="id"/>, without instantiating it.
        /// </summary>
        /// <typeparam name="T">The module contract type.</typeparam>
        /// <param name="id">The unique registration identifier.</param>
        /// <returns>The factory entry if registered; otherwise, <c>null</c>.</returns>
        public static IFactoryEntry<T>? GetEntry<T>(string id) where T : class
            => SortedFactory<T>.GetOrInstantiate().Get(id);

        /// <summary>
        /// Gets all registered factory entries for contract <typeparamref name="T"/> in ascending registration order, without instantiating them.
        /// </summary>
        /// <typeparam name="T">The module contract type.</typeparam>
        /// <returns>An enumerable sequence of factory entries.</returns>
        public static IEnumerable<IFactoryEntry<T>> GetAllEntries<T>() where T : class
            => SortedFactory<T>.GetOrInstantiate().GetAll();

        #endregion

        #region Info Sections

        /// <summary>
        /// Registers an SOS module acting as a stat section provider into the S.O.S. inspector sidebar registry.
        /// </summary>
        /// <param name="obj">The target to register: a concrete <see cref="Type"/> implementing <see cref="ISOSStatInfo"/>, a factory delegate (<see cref="Func{ISOSStatInfo}"/>), or an existing instance.</param>
        /// <param name="id">Optional unique identifier. If <c>null</c>, defaults to the type's full name.</param>
        /// <param name="order">Display priority order. Lower values appear higher up in the inspector sidebar. Defaults to <c>0.0</c>.</param>
        /// <param name="active">Whether the section is initially enabled for rendering. Defaults to <c>true</c>.</param>
        /// <returns><c>true</c> if registration succeeded; <c>false</c> if <paramref name="obj"/> is null or fails type contract validation.</returns>
        public static bool RegisterStatInfo(object obj, string? id = null, double order = 0.0, bool active = true)
            => SectionFactories.Register(obj, id, order, active);

        /// <summary>
        /// Resolves a registered stat section by identifier and casts it to <typeparamref name="T"/> using a <c>DuckProxy</c>.
        /// </summary>
        /// <typeparam name="T">The concrete or interface type expected. Must implement <see cref="ISOSStatInfo"/>.</typeparam>
        /// <param name="id">The unique identifier of the section.</param>
        /// <param name="fresh">If <c>true</c>, forces re-instantiation, replacing and disposing the cached instance. Defaults to <c>false</c>.</param>
        /// <returns>The resolved section instance if found and active; otherwise, <c>default</c>.</returns>
        public static T? GetStatInfoInstance<T>(string id, bool fresh = false) where T : class
            => GetStatInfoInstance(id, fresh)?.TryCast<T>();

        /// <summary>
        /// Resolves a registered stat section by identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the section.</param>
        /// <param name="fresh">If <c>true</c>, forces re-instantiation, replacing and disposing the cached instance. Defaults to <c>false</c>.</param>
        /// <returns>The <see cref="ISOSStatInfo"/> instance if found and active; otherwise, <c>null</c>.</returns>
        public static ISOSStatInfo? GetStatInfoInstance(string id, bool fresh = false)
            => SectionFactories.GetInstance(id, fresh);

        /// <summary>
        /// Resolves and enumerates all currently active stat sections in ascending registration order.
        /// </summary>
        /// <param name="onlyActives">If <c>true</c>, returns only instances that marked with in `IsActive`. If <c>false</c>, returns all instances.</param>
        /// <param name="fresh">If <c>true</c>, forces re-instantiation, replacing and disposing the cached instance. Defaults to <c>false</c>.</param>
        /// <returns>An enumerable sequence of active <see cref="ISOSStatInfo"/> instances.</returns>
        public static IEnumerable<ISOSStatInfo> GetAllStatInfoInstances(bool onlyActives = true, bool fresh = false)
            => SectionFactories.GetAllInstances(onlyActives, fresh);

        /// <summary>
        /// Gets the factory entry registered under <paramref name="id"/>, without instantiating it.
        /// </summary>
        /// <param name="id">The unique identifier of the section.</param>
        /// <returns>The factory entry if registered; otherwise, <c>null</c>.</returns>
        public static IFactoryEntry<ISOSStatInfo>? GetStatInfo(string id) => SectionFactories.Get(id);

        /// <summary>
        /// Gets the factory entry registered under <paramref name="id"/> and adapts it to <typeparamref name="TEntry"/>, without instantiating it.
        /// </summary>
        /// <typeparam name="TEntry">The expected entry view type.</typeparam>
        /// <param name="id">The unique identifier of the section.</param>
        /// <returns>The adapted entry if registered; otherwise, <c>null</c>.</returns>
        public static TEntry? GetStatInfo<TEntry>(string id) where TEntry : class
            => SectionFactories.Get(id)?.TryCast<TEntry>();

        /// <summary>
        /// Removes a stat section registration or its cached instance by identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the section.</param>
        /// <param name="onlyInstance">If <c>true</c>, evicts only the cached instance without removing the registration. Defaults to <c>false</c>.</param>
        /// <returns><c>true</c> if found and removed; otherwise, <c>false</c>.</returns>
        public static bool RemoveStatInfo(string id, bool onlyInstance = false)
            => SectionFactories.Remove(id, onlyInstance);

        #endregion

        #region Tabs

        /// <summary>
        /// Registers an SOS module acting as a UI tab provider into the central tab widget registry.
        /// </summary>
        /// <param name="obj">The target to register: a concrete <see cref="Type"/> implementing <see cref="ISOSTab"/>, a factory delegate (<see cref="Func{ISOSTab}"/>), or an existing instance.</param>
        /// <param name="id">Required unique identifier under which the tab is registered. Also used for localization (<c>{id}.title</c> / <c>{id}.tooltip</c>).</param>
        /// <param name="order">Display priority order determining tab button sequence. Lower values appear first. Defaults to <c>0.0</c>.</param>
        /// <param name="active">Whether the tab is initially enabled. Defaults to <c>true</c>.</param>
        /// <returns><c>true</c> if registration succeeded; <c>false</c> if <paramref name="obj"/> is null or fails type contract validation.</returns>
        public static bool RegisterTab(object obj, string id, double order = 0.0, bool active = true)
            => TabFactories.Register(obj, id, order, active);

        /// <summary>
        /// Enables the tab matching <paramref name="id"/> so it will appear in the tab bar when applicable.
        /// </summary>
        /// <param name="id">The unique identifier of the tab.</param>
        /// <returns><c>true</c> if the tab was found; otherwise, <c>false</c>.</returns>
        public static bool ActivateTab(string id) => TabFactories.SetActive(id, true);

        /// <summary>
        /// Disables the tab matching <paramref name="id"/>, hiding it from the tab bar and evicting any cached instance.
        /// </summary>
        /// <param name="id">The unique identifier of the tab.</param>
        /// <returns><c>true</c> if the tab was found; otherwise, <c>false</c>.</returns>
        public static bool DeactivateTab(string id) => TabFactories.SetActive(id, false);

        /// <summary>
        /// Gets the factory entry registered under <paramref name="id"/>, without instantiating it.
        /// </summary>
        /// <param name="id">The unique identifier of the tab.</param>
        /// <returns>The factory entry if registered; otherwise, <c>null</c>.</returns>
        public static IFactoryEntry<ISOSTab>? GetTab(string id)
            => TabFactories.Get(id);

        /// <summary>
        /// Resolves a registered tab by identifier and casts it to <typeparamref name="T"/>.
        /// </summary>
        /// <typeparam name="T">The concrete or interface type expected. Must implement <see cref="ISOSTab"/>.</typeparam>
        /// <param name="id">The unique identifier of the tab.</param>
        /// <param name="fresh">If <c>true</c>, forces re-instantiation, replacing and disposing the cached instance. Defaults to <c>false</c>.</param>
        /// <returns>The resolved tab instance if found and active; otherwise, <c>default</c>.</returns>
        public static T? GetTabInstance<T>(string id, bool fresh = false)
            => GetTabInstance(id, fresh) is T t ? t : default;

        /// <summary>
        /// Resolves a registered tab by identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the tab.</param>
        /// <param name="fresh">If <c>true</c>, forces re-instantiation, replacing and disposing the cached instance. Defaults to <c>false</c>.</param>
        /// <returns>The <see cref="ISOSTab"/> instance if found and active; otherwise, <c>null</c>.</returns>
        public static ISOSTab? GetTabInstance(string id, bool fresh = false)
            => TabFactories.GetInstance(id, fresh);

        /// <summary>
        /// Gets all registered tab factory entries in ascending registration order, without instantiating them.
        /// </summary>
        /// <param name="onlyActives">If <c>true</c>, returns only entries marked active. If <c>false</c>, returns all entries.</param>
        /// <returns>An enumerable sequence of tab factory entries.</returns>
        public static IEnumerable<IFactoryEntry<ISOSTab>> GetAllTabs(bool onlyActives = true)
            => TabFactories.GetAll(onlyActives);

        /// <summary>
        /// Resolves and enumerates all currently active tabs in ascending registration order.
        /// </summary>
        /// <param name="onlyActives">If <c>true</c>, returns only instances that marked with in `IsActive`. If <c>false</c>, returns all instances.</param>
        /// <param name="fresh">If <c>true</c>, forces re-instantiation, replacing and disposing the cached instance. Defaults to <c>false</c>.</param>
        /// <returns>An enumerable sequence of active <see cref="ISOSTab"/> instances.</returns>
        public static IEnumerable<ISOSTab> GetAllTabInstances(bool onlyActives = true, bool fresh = false)
            => TabFactories.GetAllInstances(onlyActives, fresh);

        /// <summary>
        /// Removes a tab registration or its cached instance by identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the tab.</param>
        /// <param name="onlyInstance">If <c>true</c>, evicts only the cached instance without unregistering. Defaults to <c>false</c>.</param>
        /// <returns><c>true</c> if found and removed; otherwise, <c>false</c>.</returns>
        public static bool RemoveTab(string id, bool onlyInstance = false)
            => TabFactories.Remove(id, onlyInstance);

        #endregion

        #region Configs

        /// <summary>
        /// Registers an SOS module acting as an extensible configuration unit into the SDK.
        /// </summary>
        /// <param name="obj">The target to register: a concrete <see cref="Type"/> implementing <see cref="ISOSConfig"/>, a factory delegate (<see cref="Func{ISOSConfig}"/>), or an existing instance.</param>
        /// <param name="id">Optional unique identifier. If <c>null</c>, defaults to the type's full name.</param>
        /// <param name="order">Placement priority order in the settings window. Defaults to <c>0.0</c>.</param>
        /// <param name="active">Whether the config is initially enabled. Defaults to <c>true</c>.</param>
        /// <returns><c>true</c> if registration succeeded; <c>false</c> if <paramref name="obj"/> is null or fails type contract validation.</returns>
        public static bool RegisterConfig(object obj, string? id = null, double order = 0.0, bool active = true)
            => ConfigFactories.Register(obj, id, order, active);

        /// <summary>
        /// Enables the configuration matching <paramref name="id"/>, allowing it to load, save, and render in settings.
        /// </summary>
        /// <param name="id">The unique identifier of the config.</param>
        /// <returns><c>true</c> if found; otherwise, <c>false</c>.</returns>
        public static bool ActivateConfig(string id) => ConfigFactories.SetActive(id, true);

        /// <summary>
        /// Disables the configuration matching <paramref name="id"/> and evicts any cached instance.
        /// </summary>
        /// <param name="id">The unique identifier of the config.</param>
        /// <returns><c>true</c> if found; otherwise, <c>false</c>.</returns>
        public static bool DeactivateConfig(string id) => ConfigFactories.SetActive(id, false);

        /// <summary>
        /// Gets the factory entry registered under <paramref name="id"/>, without instantiating it.
        /// </summary>
        /// <param name="id">The unique identifier of the config.</param>
        /// <returns>The factory entry if registered; otherwise, <c>null</c>.</returns>
        public static IFactoryEntry<ISOSConfig>? GetConfig(string id)
            => ConfigFactories.Get(id);

        /// <summary>
        /// Resolves a registered configuration by identifier and casts it to <typeparamref name="T"/> using DuckProxy cast.
        /// </summary>
        /// <typeparam name="T">The concrete or interface type expected. Must implement <see cref="ISOSConfig"/>.</typeparam>
        /// <param name="id">The unique identifier of the config.</param>
        /// <param name="fresh">If <c>true</c>, forces re-instantiation, replacing and disposing the cached instance. Defaults to <c>false</c>.</param>
        /// <returns>The config instance if found and active; otherwise, <c>default</c>.</returns>
        public static T? GetConfigInstance<T>(string id, bool fresh = false) where T : class
            => GetConfigInstance(id, fresh)?.TryCast<T>();

        /// <summary>
        /// Resolves a registered configuration by identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the config.</param>
        /// <param name="fresh">If <c>true</c>, forces re-instantiation, replacing and disposing the cached instance. Defaults to <c>false</c>.</param>
        /// <returns>The <see cref="ISOSConfig"/> instance if found and active; otherwise, <c>null</c>.</returns>
        public static ISOSConfig? GetConfigInstance(string id, bool fresh = false)
            => ConfigFactories.GetInstance(id, fresh);

        /// <summary>
        /// Gets all registered configuration factory entries in ascending registration order, without instantiating them.
        /// </summary>
        /// <param name="onlyActives">If <c>true</c>, returns only entries marked active. If <c>false</c>, returns all entries.</param>
        /// <returns>An enumerable sequence of configuration factory entries.</returns>
        public static IEnumerable<IFactoryEntry<ISOSConfig>> GetAllConfigs(bool onlyActives = true)
            => ConfigFactories.GetAll(onlyActives);

        /// <summary>
        /// Resolves and enumerates all currently active configurations in ascending registration order.
        /// </summary>
        /// <param name="onlyActives">If <c>true</c>, returns only instances that marked with in `IsActive`. If <c>false</c>, returns all instances.</param>
        /// <param name="fresh">If <c>true</c>, forces re-instantiation, replacing and disposing the cached instance. Defaults to <c>false</c>.</param>
        /// <returns>An enumerable sequence of active <see cref="ISOSConfig"/> instances.</returns>
        public static IEnumerable<ISOSConfig> GetAllConfigInstances(bool onlyActives = true, bool fresh = false)
            => ConfigFactories.GetAllInstances(onlyActives, fresh);

        /// <summary>
        /// Removes a configuration registration and disposes its cached instance by identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the config.</param>
        /// <returns><c>true</c> if found and removed; otherwise, <c>false</c>.</returns>
        public static bool RemoveConfig(string id)
            => ConfigFactories.Remove(id);

        #endregion

        #region Prefab Providers

        /// <summary>
        /// Registers an SOS module acting as a custom prefab data provider into the S.O.S. entity browser registry.
        /// </summary>
        /// <param name="obj">The target to register: a concrete <see cref="Type"/> implementing <see cref="ISOSPrefab"/>, a factory delegate (<see cref="Func{ISOSPrefab}"/>), or an existing instance.</param>
        /// <param name="id">Optional unique identifier. If <c>null</c>, defaults to the type's full name.</param>
        /// <param name="order">Display priority order determining section sequence in the browser list. Lower values appear first. Defaults to <c>0.0</c>.</param>
        /// <param name="active">Whether the provider is initially enabled. Defaults to <c>true</c>.</param>
        /// <returns><c>true</c> if registration succeeded; <c>false</c> if <paramref name="obj"/> is null or fails type contract validation.</returns>
        public static bool RegisterPrefabProvider(object obj, string? id = null, double order = 0.0, bool active = true)
            => PrefabFactories.Register(obj, id, order, active);

        /// <summary>
        /// Enables the prefab provider matching <paramref name="id"/> so its prefabs appear in the browser.
        /// </summary>
        /// <param name="id">The unique identifier of the provider.</param>
        /// <returns><c>true</c> if found; otherwise, <c>false</c>.</returns>
        public static bool ActivatePrefabProvider(string id) => PrefabFactories.SetActive(id, true);

        /// <summary>
        /// Disables the prefab provider matching <paramref name="id"/> and evicts any cached instance.
        /// </summary>
        /// <param name="id">The unique identifier of the provider.</param>
        /// <returns><c>true</c> if found; otherwise, <c>false</c>.</returns>
        public static bool DeactivatePrefabProvider(string id) => PrefabFactories.SetActive(id, false);

        /// <summary>
        /// Gets the factory entry registered under <paramref name="id"/>, without instantiating it.
        /// </summary>
        /// <param name="id">The unique identifier of the provider.</param>
        /// <returns>The factory entry if registered; otherwise, <c>null</c>.</returns>
        public static IFactoryEntry<ISOSPrefab>? GetPrefabProvider(string id)
            => PrefabFactories.Get(id);

        /// <summary>
        /// Resolves a registered prefab provider by identifier and casts it to <typeparamref name="T"/>.
        /// </summary>
        /// <typeparam name="T">The concrete or interface type expected. Must implement <see cref="ISOSPrefab"/>.</typeparam>
        /// <param name="id">The unique identifier of the provider.</param>
        /// <param name="fresh">If <c>true</c>, forces re-instantiation, replacing and disposing the cached instance. Defaults to <c>false</c>.</param>
        /// <returns>The provider instance if found and active; otherwise, <c>default</c>.</returns>
        public static T? GetPrefabProviderInstance<T>(string id, bool fresh = false)
            => GetPrefabProviderInstance(id, fresh) is T t ? t : default;

        /// <summary>
        /// Resolves a registered prefab provider by identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the provider.</param>
        /// <param name="fresh">If <c>true</c>, forces re-instantiation, replacing and disposing the cached instance. Defaults to <c>false</c>.</param>
        /// <returns>The <see cref="ISOSPrefab"/> instance if found and active; otherwise, <c>null</c>.</returns>
        public static ISOSPrefab? GetPrefabProviderInstance(string id, bool fresh = false)
            => PrefabFactories.GetInstance(id, fresh);

        /// <summary>
        /// Gets all registered prefab provider factory entries in ascending registration order, without instantiating them.
        /// </summary>
        /// <param name="onlyActives">If <c>true</c>, returns only entries marked active. If <c>false</c>, returns all entries.</param>
        /// <returns>An enumerable sequence of prefab provider factory entries.</returns>
        public static IEnumerable<IFactoryEntry<ISOSPrefab>> GetAllPrefabProviders(bool onlyActives = true)
            => PrefabFactories.GetAll(onlyActives);

        /// <summary>
        /// Resolves and enumerates all currently active prefab providers in ascending registration order.
        /// </summary>
        /// <param name="onlyActives">If <c>true</c>, returns only instances that marked with in `IsActive`. If <c>false</c>, returns all instances.</param>
        /// <param name="fresh">If <c>true</c>, forces re-instantiation, replacing and disposing the cached instance. Defaults to <c>false</c>.</param>
        /// <returns>An enumerable sequence of active <see cref="ISOSPrefab"/> instances.</returns>
        public static IEnumerable<ISOSPrefab> GetAllPrefabProviderInstances(bool onlyActives = true, bool fresh = false)
                    => PrefabFactories.GetAllInstances(onlyActives, fresh);

        /// <summary>
        /// Removes a prefab provider registration or its cached instance by identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the provider.</param>
        /// <param name="onlyInstance">If <c>true</c>, evicts only the cached instance without unregistering. Defaults to <c>false</c>.</param>
        /// <returns><c>true</c> if found and removed; otherwise, <c>false</c>.</returns>
        public static bool RemovePrefabProvider(string id, bool onlyInstance = false)
                    => PrefabFactories.Remove(id, onlyInstance);

        #endregion

        #region Window Profiles

        /// <summary>
        /// Registers an SOS module acting as a visual window layout profile into the S.O.S. profile registry.
        /// </summary>
        /// <param name="obj">The target to register: a concrete <see cref="Type"/> implementing <see cref="ISOSWindowProfile"/>, a factory delegate (<see cref="Func{ISOSWindowProfile}"/>), or an existing instance.</param>
        /// <param name="id">Required unique identifier under which the profile is registered. Also used for localization (<c>{id}.name</c> / <c>{id}.desc</c>) and persisted selection.</param>
        /// <param name="order">Priority order in the profile selector dropdown. Defaults to <c>0.0</c>.</param>
        /// <param name="active">Whether the profile is initially enabled. Defaults to <c>true</c>.</param>
        /// <returns><c>true</c> if registration succeeded; <c>false</c> if <paramref name="obj"/> is null or fails type contract validation.</returns>
        public static bool RegisterWindowProfile(object obj, string id, double order = 0.0, bool active = true)
                    => ProfileFactories.Register(obj, id, order, active);

        /// <summary>
        /// Enables the window profile matching <paramref name="id"/> so it appears in the profile selection menu.
        /// </summary>
        /// <param name="id">The unique identifier of the profile.</param>
        /// <returns><c>true</c> if found; otherwise, <c>false</c>.</returns>
        public static bool ActivateWindowProfile(string id) => ProfileFactories.SetActive(id, true);

        /// <summary>
        /// Disables the window profile matching <paramref name="id"/> and evicts any cached instance.
        /// </summary>
        /// <param name="id">The unique identifier of the profile.</param>
        /// <returns><c>true</c> if found; otherwise, <c>false</c>.</returns>
        public static bool DeactivateWindowProfile(string id) => ProfileFactories.SetActive(id, false);

        /// <summary>
        /// Gets the window profile factory entry matching <paramref name="id"/>, falling back to the first active entry if not found. Never instantiates.
        /// </summary>
        /// <param name="id">The unique identifier of the profile. If <c>null</c> or not found, resolves the first active entry.</param>
        /// <returns>The factory entry; or <c>null</c> if no active profiles are registered.</returns>
        public static IFactoryEntry<ISOSWindowProfile>? GetWindowProfile(string? id)
            => ProfileFactories.GetOrFirst(id);

        /// <summary>
        /// Resolves a registered window profile by identifier and casts it to <typeparamref name="T"/>.
        /// </summary>
        /// <typeparam name="T">The concrete or interface type expected. Must implement <see cref="ISOSWindowProfile"/>.</typeparam>
        /// <param name="id">The unique identifier of the profile.</param>
        /// <param name="fresh">If <c>true</c>, forces re-instantiation, replacing and disposing the cached instance. Defaults to <c>false</c> for visual profiles.</param>
        /// <returns>The profile instance if found and active; otherwise, <c>default</c>.</returns>
        public static T? GetWindowProfileInstance<T>(string id, bool fresh = false)
            => GetWindowProfileInstance(id, fresh) is T t ? t : default;

        /// <summary>
        /// Resolves a registered window profile by identifier, falling back to the default profile if not found.
        /// </summary>
        /// <param name="id">The unique identifier of the profile. If <c>null</c> or empty, resolves the first active profile.</param>
        /// <param name="fresh">If <c>true</c>, forces re-instantiation, replacing and disposing the cached instance. Defaults to <c>false</c> for visual profiles.</param>
        /// <returns>The resolved <see cref="ISOSWindowProfile"/> instance; or <c>null</c> if no active profiles are registered.</returns>
        public static ISOSWindowProfile? GetWindowProfileInstance(string? id, bool fresh = false)
        {
            ISOSWindowProfile? v;
            if (string.IsNullOrEmpty(id)) v = ProfileFactories.FirstInstance(fresh);
            else
            {
                Logger.LogDebug($"GetWindowProfile >> id: '{id}'", level: LogLevel.Trace);
                var entry = ProfileFactories.Get(id);
                v = entry?.Instance(fresh);
                if (v == null)
                {
                    Logger.LogWarning("[SOS] Profile not encountered. Trying to use default profile.");
                    v = ProfileFactories.FirstInstance();
                    entry = ProfileFactories.First();
                }
                Logger.LogDebug($"GetWindowProfile >> Name: '{entry?.DisplayName() ?? "null"}'", level: LogLevel.Trace);
            }
            if (v == null)
            {
                var color = Microsoft.Xna.Framework.Color.LightSkyBlue;
                Logger.LogDebugError($"[SOS] No one profile encountered.\n => Profile list: {string.Join(',', GetAllWindowProfiles().Select(p => p.DisplayName()))}\n => Profile _dict => {string.Join(',', ProfileFactories.GetAll().Select(f => $"[{f.Id}, {f.Order}]"))}");
                Logger.LogReleaseError($"[SOS] No one profile encountered. Try reinstall 'S.O.S - Standard Operation Schematics' Mod, report that in steam mod page or create an issue on Git project(‖color:{color.R},{color.G},{color.B}‖https://github.com/retype15/SOS‖end‖).");
            }
            return v;
        }

        /// <summary>
        /// Gets all registered window profile factory entries in ascending registration order, without instantiating them.
        /// </summary>
        /// <param name="onlyActives">If <c>true</c>, returns only entries marked active. If <c>false</c>, returns all entries.</param>
        /// <returns>An enumerable sequence of window profile factory entries.</returns>
        public static IEnumerable<IFactoryEntry<ISOSWindowProfile>> GetAllWindowProfiles(bool onlyActives = true)
            => ProfileFactories.GetAll(onlyActives);

        /// <summary>
        /// Resolves and enumerates all currently active window profiles in ascending registration order.
        /// </summary>
        /// <param name="onlyActives">If <c>true</c>, returns only instances that marked with in `IsActive`. If <c>false</c>, returns all instances.</param>
        /// <param name="fresh">If <c>true</c>, forces re-instantiation, replacing and disposing the cached instance. Defaults to <c>false</c> for visual profiles.</param>
        /// <returns>An enumerable sequence of active <see cref="ISOSWindowProfile"/> instances.</returns>
        public static IEnumerable<ISOSWindowProfile> GetAllWindowProfileInstances(bool onlyActives = true, bool fresh = false)
            => ProfileFactories.GetAllInstances(onlyActives, fresh);

        /// <summary>
        /// Removes a window profile registration or its cached instance by identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the profile.</param>
        /// <param name="onlyInstance">If <c>true</c>, evicts only the cached instance without unregistering. Defaults to <c>false</c>.</param>
        /// <returns><c>true</c> if found and removed; otherwise, <c>false</c>.</returns>
        public static bool RemoveWindowProfile(string id, bool onlyInstance = false)
            => ProfileFactories.Remove(id, onlyInstance);

        #endregion

        #region EventBus Facade

        /// <summary>
        /// Subscribes a parameterless callback to the specified event channel with priority-based execution ordering.
        /// </summary>
        /// <param name="key">The unique event channel identifier (see <see cref="CommKeys"/>).</param>
        /// <param name="handler">The callback delegate invoked when the event is emitted.</param>
        /// <param name="order">The execution priority weight. Lower values execute earlier (see <see cref="EventPriority"/>). Defaults to <c>0.0</c>.</param>
        /// <remarks>
        /// Handlers execute outside internal locks, ensuring safe reentrancy and zero deadlocks.
        /// </remarks>
        public static void On(string key, Action handler, double order = 0) => eventBus.On(key, handler, order);

        /// <summary>
        /// Subscribes a strongly-typed callback to the specified event channel with priority-based execution ordering.
        /// </summary>
        /// <typeparam name="T">The payload type associated with the event.</typeparam>
        /// <param name="key">The unique event channel identifier (see <see cref="CommKeys"/>).</param>
        /// <param name="handler">The callback delegate invoked with the payload when the event is emitted.</param>
        /// <param name="order">The execution priority weight. Lower values execute earlier (see <see cref="EventPriority"/>). Defaults to <c>0.0</c>.</param>
        /// <remarks>
        /// Handlers execute outside internal locks, ensuring safe reentrancy and zero deadlocks.
        /// </remarks>
        public static void On<T>(string key, Action<T> handler, double order = 0) => eventBus.On<T>(key, handler, order);

        /// <summary>
        /// Unsubscribes a parameterless callback from the specified event channel.
        /// </summary>
        /// <param name="key">The unique event channel identifier.</param>
        /// <param name="handler">The callback delegate to remove.</param>
        /// <param name="order">Optional. If specified, removes the handler only from this exact priority tier; if <c>null</c>, removes it across all tiers.</param>
        /// <param name="removeState">If <c>true</c>, also evicts any state stored under <paramref name="key"/>.</param>
        public static void Off(string key, Action handler, double? order = null, bool removeState = false) => eventBus.Off(key, handler, order, removeState);

        /// <summary>
        /// Unsubscribes a strongly-typed callback from the specified event channel.
        /// </summary>
        /// <typeparam name="T">The payload type associated with the event.</typeparam>
        /// <param name="key">The unique event channel identifier.</param>
        /// <param name="handler">The callback delegate to remove.</param>
        /// <param name="order">Optional. If specified, removes the handler only from this exact priority tier; if <c>null</c>, removes it across all tiers.</param>
        /// <param name="removeState">If <c>true</c>, also evicts any state stored under <paramref name="key"/>.</param>
        public static void Off<T>(string key, Action<T> handler, double? order = null, bool removeState = false) => eventBus.Off<T>(key, handler, order, removeState);

        /// <summary>
        /// Emits a parameterless event across all priority tiers on the specified channel.
        /// </summary>
        /// <param name="key">The unique event channel identifier (see <see cref="CommKeys"/>).</param>
        /// <returns><c>true</c> if at least one handler was invoked; otherwise, <c>false</c>.</returns>
        public static bool Emit(string key) => eventBus.Emit(key, null);

        /// <summary>
        /// Emits an event on the specified channel with an optional order parameter.
        /// </summary>
        /// <param name="key">The unique event identifier channel.</param>
        /// <param name="order">Optional execution order override.</param>
        /// <returns><c>true</c> if the event was emitted to at least one handler; <c>false</c> otherwise.</returns>
        public static bool Emit(string key, double? order = null) => eventBus.Emit(key, order);

        /// <summary>
        /// Emits a strongly-typed event across all priority tiers or within a specific tier, optionally persisting state.
        /// </summary>
        /// <typeparam name="T">The payload type.</typeparam>
        /// <param name="key">The unique event channel identifier (see <see cref="CommKeys"/>).</param>
        /// <param name="value">The payload value delivered to subscribers.</param>
        /// <param name="order">Optional exact priority tier to invoke. If <c>null</c>, delivers to handlers across all priority tiers.</param>
        /// <param name="setState">If <c>true</c>, updates the internal state store with <paramref name="value"/> <i>after</i> all handlers have finished executing.</param>
        /// <returns><c>true</c> if at least one handler was invoked; otherwise, <c>false</c>.</returns>
        /// <remarks>
        /// Handlers execute in ascending order of their priority weights. Delegate invocation occurs outside internal locks.
        /// </remarks>
        public static bool Emit<T>(string key, T value, double? order = null, bool setState = true) => eventBus.Emit<T>(key, value, order, setState);

        /// <summary>
        /// Emits a parameterless event to handlers whose priority order falls within [<paramref name="min"/>, <paramref name="max"/>].
        /// </summary>
        /// <param name="key">The unique event channel identifier.</param>
        /// <param name="min">Minimum priority order (inclusive). Defaults to <see cref="double.MinValue"/>.</param>
        /// <param name="max">Maximum priority order (inclusive). Defaults to <see cref="double.MaxValue"/>.</param>
        /// <returns><c>true</c> if at least one handler was invoked; otherwise, <c>false</c>.</returns>
        public static bool EmitRange(string key, double min = double.MinValue, double max = double.MaxValue) => eventBus.Emit(key, min, max);

        /// <summary>
        /// Emits a strongly-typed event to handlers whose priority order falls within [<paramref name="min"/>, <paramref name="max"/>], optionally persisting state.
        /// </summary>
        /// <typeparam name="T">The payload type.</typeparam>
        /// <param name="key">The unique event channel identifier.</param>
        /// <param name="value">The payload value delivered to subscribers.</param>
        /// <param name="min">Minimum priority order (inclusive). Defaults to <see cref="double.MinValue"/>.</param>
        /// <param name="max">Maximum priority order (inclusive). Defaults to <see cref="double.MaxValue"/>.</param>
        /// <param name="setState">If <c>true</c>, updates the internal state store with <paramref name="value"/> <i>after</i> all handlers have finished executing.</param>
        /// <returns><c>true</c> if at least one handler was invoked; otherwise, <c>false</c>.</returns>
        public static bool EmitRange<T>(string key, T value, double min = double.MinValue, double max = double.MaxValue, bool setState = true) => eventBus.Emit<T>(key, value, min, max, setState);

        /// <summary>
        /// Stores a value in the shared state cache, optionally emitting it across the channel.
        /// </summary>
        /// <typeparam name="T">The state payload type.</typeparam>
        /// <param name="key">The state channel identifier.</param>
        /// <param name="value">The value to store.</param>
        /// <param name="emit">If <c>true</c>, also emits the value across the channel.</param>
        public static void SetState<T>(string key, T value, bool emit = false) => eventBus.SetState<T>(key, value, emit);

        /// <summary>
        /// Stores a dynamic state generator evaluated on-demand when read via <see cref="GetState{T}(string)"/>.
        /// </summary>
        /// <typeparam name="T">The state payload type.</typeparam>
        /// <param name="key">The state channel identifier.</param>
        /// <param name="method">The delegate invoked on each retrieval to compute the state value.</param>
        /// <param name="emit">If <c>true</c>, invokes the delegate immediately and emits the resulting value.</param>
        public static void SetState<T>(string key, Func<T> method, bool emit = false) => eventBus.SetState<T>(key, method, emit);

        /// <summary>
        /// Retrieves the current state value stored under the specified channel key.
        /// </summary>
        /// <typeparam name="T">The expected type of the state value.</typeparam>
        /// <param name="key">The state channel identifier.</param>
        /// <returns>The stored value if found; otherwise, <c>default</c>.</returns>
        /// <exception cref="System.Runtime.InteropServices.SafeArrayTypeMismatchException">Thrown when the stored value cannot be cast to <typeparamref name="T"/>.</exception>
        public static T? GetState<T>(string key) => eventBus.GetState<T>(key);

        /// <summary>
        /// Evicts the state value stored under the specified channel key.
        /// </summary>
        /// <param name="key">The state channel identifier.</param>
        /// <returns><c>true</c> if an entry was removed; otherwise, <c>false</c>.</returns>
        public static bool RemoveState(string key) => eventBus.RemoveState(key);

        #endregion

        #region Event Helpers

        /// <summary>
        /// Requests the active window profile to populate the search box with the given filter token.
        /// </summary>
        /// <param name="tag">The search token (e.g. <c>"#Medical"</c>, <c>"$surgery"</c> or <c>"@Vanilla"</c>).</param>
        public static void SetSearchFilter(string tag) => API.Emit(CommKeys.SetSearchFilter, tag);

        #endregion

        #region Internal helpers

        /// <summary>
        /// Discovers and auto-registers all SOS modules decorated with <see cref="AutoRegisterAttribute"/> across loaded assemblies.
        /// </summary>
        /// <param name="pluginManagementService">The LuaCs plugin management service.</param>
        /// <remarks>
        /// Scans for classes implementing <see cref="ISOSStatInfo"/>, <see cref="ISOSTab"/>, <see cref="ISOSConfig"/>,
        /// <see cref="ISOSPrefab"/>, and <see cref="ISOSWindowProfile"/>.
        /// </remarks>
        internal static void Initialize(IPluginManagementService pluginManagementService)
        {
            if (_scanned) return;

            foreach (var factory in SortedFactory.GetAllFactories())
                factory.AutoRegister(pluginManagementService);

            _scanned = true;
        }

        private static bool _isRegisteredTypesToLuaDataService = false;
        internal static void RegisterTypesToLuaDataService()
        {
            if (_isRegisteredTypesToLuaDataService) return;

            var servicesProvider = Barotrauma.LuaCsSetup.Instance._servicesProvider;
            ILuaUserDataService? userDataService = servicesProvider.GetService<ILuaUserDataService>();

            foreach (var type in typeof(API).Assembly.GetExportedTypes())
            {
                var name = type.FullOrName();
                Logger.LogDebug($"Trying to register '{name}'...", level: LogLevel.Trace);
                userDataService.RegisterType(name);
            }

            _isRegisteredTypesToLuaDataService = true;
        }

        internal static void ClearTemporaryInstances()
        {
            foreach (var factory in SortedFactory.GetAllFactories())
                factory.CleanInstances();
        }

        internal static void Clear()
        {
            SortedFactory.CleanFactory();
            _scanned = false;
            eventBus = new();
        }

        #endregion
    }
}
