// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using System.Runtime.InteropServices;

namespace SOS
{
    /// <summary>
    /// Internal event bus managing prioritized callback execution channels.
    /// </summary>
    /// <remarks>
    /// Uses a Red-Black tree (<see cref="SortedDictionary"/>) keyed by normalized priority orders (4 decimal places)
    /// to store handler lists per event channel. This ensures O(log n) lookup and insertion while preventing
    /// floating-point lookup misses that could cause handlers to be missed or incorrectly dispatched.
    /// </remarks>
    internal sealed class EventBus
    {
        private readonly Dictionary<string, EventChannel> _channels = [];
        private readonly Dictionary<string, object?> _state = [];

        /// <summary>
        /// A priority-ordered channel for event handlers, using a SortedDictionary keyed by normalized priority orders.
        /// </summary>
        /// <remarks>
        /// Handlers are stored in buckets (SortedDictionary&lt;double, List&lt;Delegate&gt;&gt;) where the key is the normalized priority order
        /// (rounded to 4 decimal places via <see cref="Normalize(double)"/>). This 4-decimal precision normalization prevents
        /// floating-point lookup misses in the Red-Black tree structure, ensuring handlers are reliably found and executed.
        /// </remarks>
        private sealed class EventChannel
        {
            private const int DEPTH = 4;
            private readonly SortedDictionary<double, List<Delegate>> buckets = [];

            /// <summary>
            /// Normalizes a priority order to 4 decimal places to prevent floating-point lookup misses in the Red-Black tree.
            /// </summary>
            /// <param name="order">The priority order to normalize.</param>
            /// <returns>The order rounded to 4 decimal places.</returns>
            /// <remarks>
            /// This normalization is critical for the SortedDictionary lookup: without it, floating-point arithmetic differences
            /// could cause lookup misses, resulting in handlers being missed or incorrectly dispatched. The normalized key is
            /// used consistently during subscription and unsubscription to ensure handler lists are correctly found.
            /// </remarks>
            private static double Normalize(double order) => Math.Round(order, DEPTH, MidpointRounding.AwayFromZero);

            public SortedDictionary<double, List<Delegate>>.KeyCollection Keys => buckets.Keys;

            public void Add(Delegate handler, double order)
            {
                double key = Normalize(order);
                lock (buckets)
                {
                    if (!buckets.TryGetValue(key, out var list))
                        buckets[key] = list = [];

                    list.Add(handler);
                }
            }

            public bool Remove(Delegate handler, double? order = null)
                => order.HasValue ?
                    Remove(handler, order.Value) :
                    Remove(handler);

            public bool Remove(Delegate handler, double order)
            {
                double key = Normalize(order);
                bool removed = false;

                lock (buckets)
                    if (buckets.TryGetValue(key, out var list))
                    {
                        removed = list.Remove(handler);
                        if (list.Count == 0) buckets.Remove(key);
                    }

                return removed;
            }
            public bool Remove(Delegate handler)
            {
                List<double> emptybuckets = [];
                bool removed = false;

                lock (buckets)
                {
                    foreach (var (prio, list) in buckets)
                    {
                        if (list.Remove(handler))
                        {
                            removed = true;
                            if (list.Count == 0)
                                emptybuckets.Add(prio);
                        }
                    }

                    foreach (var prio in emptybuckets)
                        buckets.Remove(prio);
                }

                return removed;
            }

            private double[] GetKeyCopy()
            {
                lock (buckets) return [.. Keys];
            }

            private List<double> GetKeyCopy(double min = double.MinValue, double max = double.MaxValue)
            {
                min = Normalize(min);
                max = Normalize(max);

                List<double> keys = [];

                lock (buckets)
                    foreach (var k in Keys)
                        if (k >= min && k <= max) keys.Add(k);

                return keys;
            }

            private Delegate[]? GetValueCopy(double order)
            {
                lock (buckets)
                {
                    if (buckets.TryGetValue(order, out var list))
                        return [.. list];
                }
                return null;
            }

            public bool Call(double? order = null)
                => order.HasValue ?
                    Call(order: order.Value) :
                    Call();

            public bool Call()
            {
                var result = false;

                foreach (var order in GetKeyCopy())
                    result |= Call(order);

                return result;
            }

            public bool Call(double order)
            {
                order = Normalize(order);
                var handlers = GetValueCopy(order);
                if (handlers == null || handlers.Length == 0) return false;
                var result = false;
                foreach (var handler in handlers)
                {
                    try
                    {
                        if (handler is Action h)
                        {
                            h();
                            result = true;
                        }
                    }
                    catch (Exception ex)
                    {
                        Logger.LogError($"[SOS.API] Observer error in handler '{handler.Method.Name}' at order {order}: {ex.Message}");
                    }
                }
                return result;
            }

            public bool Call<T>(T value, double? order = null)
                => order.HasValue ?
                    Call(value: value, order: order.Value) :
                    Call(value: value);

            public bool Call<T>(T value)
            {
                double[]? channels;
                lock (buckets) channels = [.. Keys];
                var result = false;

                foreach (var order in channels)
                    result |= Call<T>(order, value);

                return result;
            }

            public bool Call<T>(double order, T value)
            {
                order = Normalize(order);
                var handlers = GetValueCopy(order);
                if (handlers == null || handlers.Length == 0) return false;
                var result = false;
                foreach (var handler in handlers)
                {
                    try
                    {
                        switch (handler)
                        {
                            case Action<T> h1: h1(value); result = true; break;
                            case Action h2: h2(); result = true; break;
                        }
                    }
                    catch (Exception ex)
                    {
                        Logger.LogError($"[SOS.API] Observer error in handler '{handler.Method.Name}' at order {order}: {ex.Message}");
                    }
                }

                return result;
            }

            public bool CallRange(double min = double.MinValue, double max = double.MaxValue)
            {
                bool result = false;

                foreach (var order in GetKeyCopy(min, max))
                    result |= Call(order);

                return result;
            }

            public bool CallRange<T>(T value, double min = double.MinValue, double max = double.MaxValue)
            {
                List<double> channels = GetKeyCopy(min, max);
                bool result = false;

                foreach (var order in channels)
                    result |= Call<T>(order, value);

                return result;
            }

            /// <summary>
            /// Clears all event channels and state entries.
            /// </summary>
            /// <remarks>
            /// Clears the internal dictionary of channels (_channels) and the state dictionary (_state).
            /// All handlers are removed, and any stored state is cleared. This operation is performed under locks
            /// to ensure thread safety.
            /// </remarks>
            public void Clear()
            {
                lock (buckets) buckets.Clear();
            }
        }

        /// <summary>
        /// Subscribes a strongly-typed callback to the specified event channel with priority-based execution ordering.
        /// </summary>
        /// <typeparam name="T">The payload type associated with the event.</typeparam>
        /// <param name="key">The unique event identifier channel.</param>
        /// <param name="handler">The delegate to invoke when the event is emitted.</param>
        /// <param name="order">The execution priority weight. Lower values execute earlier (see <see cref="EventPriority"/>).
        /// Values are normalized to 4 decimal places. Defaults to <see cref="EventPriority.Default"/> (<c>0.0</c>).
        /// </param>
        /// <remarks>
        /// Handlers are executed outside internal synchronization locks, guaranteeing reentrancy safety and zero deadlocks.
        /// The handler is added to the appropriate priority bucket in the Red-Black tree (<see cref="SortedDictionary double, List{Delegate}"/>).
        /// </remarks>
        public void On<T>(string key, Action<T> handler, double order = 0)
        {
            lock (_channels)
            {
                if (!_channels.TryGetValue(key, out var channel))
                    _channels[key] = channel = new();

                channel.Add(handler, order);
            }

            Logger.LogDebug($"ON '{key}' (T:{typeof(T).FullOrName()}) registered at order {order}.", level: LogLevel.Trace);
        }

        /// <summary>
        /// Subscribes a callback to the specified event channel with priority-based execution ordering.
        /// </summary>
        /// <param name="key">The unique event identifier channel.</param>
        /// <param name="handler">The delegate to invoke when the event is emitted.</param>
        /// <param name="order">The execution priority weight. Lower values execute earlier (see <see cref="EventPriority"/>).
        /// Values are normalized to 4 decimal places. Defaults to <see cref="EventPriority.Default"/> (<c>0.0</c>).
        /// </param>
        /// <remarks>
        /// Handlers are executed outside internal synchronization locks, guaranteeing reentrancy safety and zero deadlocks.
        /// The handler is added to the appropriate priority bucket in the Red-Black tree.
        /// </remarks>
        public void On(string key, Action handler, double order = 0)
        {
            lock (_channels)
            {
                if (!_channels.TryGetValue(key, out var channel))
                    _channels[key] = channel = new();

                channel.Add(handler, order);
            }

            Logger.LogDebug($"ON '{key}' registered at order {order}.", level: LogLevel.Trace);
        }

        /// <summary>
        /// Unsubscribes a strongly-typed handler from the specified event channel.
        /// </summary>
        /// <typeparam name="T">The payload type associated with the event.</typeparam>
        /// <param name="key">The unique event identifier channel.</param>
        /// <param name="handler">The delegate to remove.</param>
        /// <param name="order">Optional. If specified, removes the handler only from the priority level matching this value.
        /// If <c>null</c>, removes the handler from <b>all</b> priority levels where it was subscribed.</param>
        /// <param name="removeState">If <c>true</c>, also removes any saved state associated with the key.</param>
        /// <returns><c>true</c> if the handler was found and removed; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// <para>
        /// <c>Off<T>(key, handler)</c>: Removes the handler from <b>all</b> priority levels.
        /// </para>
        /// <para>
        /// <c>Off<T>(key, handler, order)</c>: Targeted removal from a specific priority level. Only handlers at that exact
        /// normalized order are removed.
        /// </para>
        /// </remarks>
        public bool Off<T>(string key, Action<T> handler, double? order = null, bool removeState = false)
        {
            var result = false;
            lock (_channels)
            {
                if (_channels.TryGetValue(key, out var channel))
                    result = channel.Remove(handler, order);
            }

            if (removeState) RemoveState(key);

            Logger.LogDebug($"OFF '{key}' (T:{typeof(T).FullOrName()}) removed {(order.HasValue ? $"at order {order}" : "on all")}.", level: LogLevel.Trace);

            return result;
        }

        /// <summary>
        /// Unsubscribes a handler from the specified event channel.
        /// </summary>
        /// <param name="key">The unique event identifier channel.</param>
        /// <param name="handler">The delegate to remove.</param>
        /// <param name="order">Optional. If specified, removes the handler only from the priority level matching this value.
        /// If <c>null</c>, removes the handler from <b>all</b> priority levels where it was subscribed.</param>
        /// <param name="removeState">If <c>true</c>, also removes any saved state associated with the key.</param>
        /// <returns><c>true</c> if the handler was found and removed; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// <para>
        /// <c>Off(key, handler)</c>: Removes the handler from <b>all</b> priority levels.
        /// </para>
        /// <para>
        /// <c>Off(key, handler, order)</c>: Targeted removal from a specific priority level. Only handlers at that exact
        /// normalized order are removed.
        /// </para>
        /// </remarks>
        public bool Off(string key, Action handler, double? order = null, bool removeState = false)
        {
            bool result = false;
            lock (_channels)
            {
                if (_channels.TryGetValue(key, out var channel))
                    result = (order.HasValue) ?
                        channel.Remove(handler, order.Value) :
                        channel.Remove(handler);
            }
            if (removeState) RemoveState(key);

            Logger.LogDebug($"OFF '{key}' removed {(order.HasValue ? $"at order {order}" : "on all")}.", level: LogLevel.Trace);

            return result;
        }

        /// <summary>
        /// Emits a typed event on the specified channel with optional order and state management.
        /// </summary>
        /// <typeparam name="T">The type of the value to emit.</typeparam>
        /// <param name="key">The unique event identifier channel.</param>
        /// <param name="value">The value to emit.</param>
        /// <param name="order">Optional execution order. If <c>null</c>, uses the handler's registered order.</param>
        /// <param name="setState">If <c>true</c>, sets the internal state to the emitted value after firing.</param>
        /// <returns><c>true</c> if the event was emitted to at least one handler; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// The event is delivered to all subscribed handlers across all priority levels. Handlers execute outside internal locks,
        /// guaranteeing reentrancy safety. If <paramref name="setState"/> is true, the state is updated before the handlers run.
        /// </remarks>
        public bool Emit<T>(string key, T value, double? order = null, bool setState = true)
        {
            var result = _channels.GetValueLocked(key)?.Call<T>(value: value, order: order) ?? false;

            if (setState) SetState<T>(key, value, false);

            Logger.LogDebug($"EMIT '{key}' called with value '{value}' (T:{typeof(T).FullOrName()})", level: LogLevel.Trace);

            return result;
        }

        /// <summary>
        /// Emits a typed event on the specified channel within a priority range, with state management.
        /// </summary>
        /// <typeparam name="T">The type of the value to emit.</typeparam>
        /// <param name="key">The unique event identifier channel.</param>
        /// <param name="value">The value to emit.</param>
        /// <param name="min">Minimum order (inclusive). Defaults to <see cref="double.MinValue"/>.</param>
        /// <param name="max">Maximum order (inclusive). Defaults to <see cref="double.MaxValue"/>.</param>
        /// <param name="setState">If <c>true</c>, sets the internal state to the emitted value after firing.</param>
        /// <returns><c>true</c> if the event was emitted to at least one handler; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// Only handlers whose registered orders fall within the [min, max] range (after normalization) will be invoked.
        /// Handlers execute outside internal locks, guaranteeing reentrancy safety.
        /// </remarks>
        public bool Emit<T>(string key, T value, double min = double.MinValue, double max = double.MaxValue, bool setState = true)
        {
            var result = _channels.GetValueLocked(key)?.CallRange<T>(value, min, max) ?? false;

            if (setState) SetState<T>(key, value, false);

            Logger.LogDebug($"EMIT '{key}' called with value '{value}' (T:{typeof(T).FullOrName()})", level: LogLevel.Trace);

            return result;
        }

        /// <summary>
        /// Emits an event on the specified channel with an optional order parameter.
        /// </summary>
        /// <param name="key">The unique event identifier channel.</param>
        /// <param name="order">Optional execution order. If <c>null</c>, handlers execute at their registered order.</param>
        /// <returns><c>true</c> if the event was emitted to at least one handler; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// Handlers execute outside internal synchronization locks, guaranteeing reentrancy safety and zero deadlocks.
        /// </remarks>
        public bool Emit(string key, double? order = null)
        {
            var result = _channels.GetValueLocked(key)?.Call(order) ?? false;

            Logger.LogDebug($"EMIT'{key}' called.", level: LogLevel.Trace);

            return result;
        }

        /// <summary>
        /// Emits an event on the specified channel within a priority range, invoking all handlers whose orders fall between <paramref name="min"/> and <paramref name="max"/>.
        /// </summary>
        /// <param name="key">The unique event identifier channel.</param>
        /// <param name="min">Minimum order (inclusive). Defaults to <see cref="double.MinValue"/>.</param>
        /// <param name="max">Maximum order (inclusive). Defaults to <see cref="double.MaxValue"/>.</param>
        /// <returns><c>true</c> if the event was emitted to at least one handler; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// Only handlers with normalized orders in the [min, max] range will be invoked. Handlers execute outside internal locks,
        /// guaranteeing reentrancy safety.
        /// </remarks>
        public bool Emit(string key, double min = double.MinValue, double max = double.MaxValue)
        {
            var result = _channels.GetValueLocked(key)?.CallRange(min, max) ?? false;

            Logger.LogDebug($"EMIT'{key}' called.", level: LogLevel.Trace);

            return result;
        }

        /// <summary>
        /// Sets the state for the specified key, optionally emitting the value as an event.
        /// </summary>
        /// <typeparam name="T">The type of the state value.</typeparam>
        /// <param name="key">The unique identifier for the state.</param>
        /// <param name="value">The value to set as state.</param>
        /// <param name="emit">If <c>true</c>, emits the value as an event after setting the state.</param>
        /// <remarks>
        /// State is stored internally and can be retrieved via <see cref="GetState{T}(string)"/>.
        /// If <paramref name="emit"/> is true, the value is emitted as an event without a specific order (defaults to handler's order).
        /// </remarks>
        public void SetState<T>(string key, T value, bool emit = false)
        {
            lock (_state)
                _state[key] = value;

            if (emit) Emit<T>(key, value, null, setState: false);

            Logger.LogDebug($"SET_STATE CALLED '{key}' with type: {typeof(T).FullOrName()}.", level: LogLevel.Trace);
        }

        /// <summary>
        /// Sets the state for the specified key using a provider method that computes the value on demand.
        /// </summary>
        /// <typeparam name="T">The type of the state value.</typeparam>
        /// <param name="key">The unique identifier for the state.</param>
        /// <param name="method">A <see cref="Func{T}"/> delegate that returns the state value when invoked.</param>
        /// <param name="emit">If <c>true</c>, emits the resulting value as an event after invoking the method.</param>
        /// <remarks>
        /// The method is invoked each time <see cref="GetState{T}(string)"/> is called, allowing for dynamic state computation.
        /// If <paramref name="emit"/> is true, the computed value is emitted as an event.
        /// </remarks>
        public void SetState<T>(string key, Func<T> method, bool emit = false)
        {
            lock (_state)
                _state[key] = method;

            if (emit) Emit(key, method(), null, false);

            Logger.LogDebug($"SET_STATE CALLED '{key}' with a delegate function: 'Func<{typeof(T).FullOrName()}>'.", level: LogLevel.Trace);
        }

        /// <summary>
        /// Retrieves the current state value for the specified key.
        /// </summary>
        /// <typeparam name="T">The expected type of the state value.</typeparam>
        /// <param name="key">The unique identifier for the state.</param>
        /// <returns>The state value if found; otherwise, <c>default</c> (<c>null</c> for reference types).
        /// <para>Type resolution logic:</para>
        /// <list type="bullet">
        /// <item>The stored value is checked: if it matches <typeparamref name="T"/>, it is returned directly.</item>
        /// <item>If the stored value is a <see cref="Func{T}"/>, it is invoked and the result is returned.</item>
        /// <item>If neither matches, a <see cref="SafeArrayTypeMismatchException"/> is thrown with a descriptive message.</item>
        /// </list>
        /// </returns>
        /// <remarks>
        /// State is set via <see cref="SetState{T}(string, T, bool)"/> or <see cref="SetState{T}(string, Func{T}, bool)"/>.
        /// This method performs runtime type checking to determine how to extract the value.
        /// </remarks>
        public T? GetState<T>(string key)
        {
            lock (_state)
            {
                if (_state.TryGetValue(key, out var value))
                {
                    var result = value switch
                    {
                        T t => t,
                        Func<T> ft => ft(),
                        _ => throw new SafeArrayTypeMismatchException($"GetState called with diferent type signature: T:'{typeof(T)}' is not {value?.GetType()}"),
                    };
                    Logger.LogDebug($"GET_STATE CALLED '{key}' with type: {typeof(T).FullOrName()}, returned {result}.", level: LogLevel.Trace);
                    return result;
                }
                Logger.LogDebug($"GET_STATE CALLED '{key}' with type: {typeof(T).FullOrName()}, saved type is {value?.GetType().Name}, returned default.", level: LogLevel.Trace);
            }

            return default;
        }

        /// <summary>
        /// Removes the state associated with the specified key.
        /// </summary>
        /// <param name="key">The unique identifier of the state to remove.</param>
        /// <returns><c>true</c> if the state was found and removed; <c>false</c> if no state existed for the key.</returns>
        /// <remarks>
        /// State removal does not affect event handlers subscribed via <see cref="On"/>.
        /// </remarks>
        public bool RemoveState(string key)
        {
            lock (_state)
                return _state.Remove(key);
        }

        public void Clear()
        {
            lock (_channels) _channels.Clear();
            lock (_state) _state.Clear();
        }
    }
}