// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using Barotrauma;
using Barotrauma.LuaCs;

namespace SOS
{
    public interface IFactoryEntry<T> : IDisposable
    {
        Identifier Id { get; }
        double Order { get; }
        T? Value { get; }
        T? Instance(bool fresh);
        T? Instantiate();
        void Drop();
    }

    /// <summary>
    /// Thread-safe, ordered service registry managing component discovery, sorting, activation, and instance lifecycle.
    /// </summary>
    /// <typeparam name="T">The contract type managed by this registry. Must be a reference type.</typeparam>
    /// <remarks>
    /// <para>
    /// <b>Core Responsibilities:</b>
    /// <list type="bullet">
    /// <item><description><b>Ordered Discovery:</b> Stores component factories paired with a priority order. Output queries are sorted ascending by order, then alphabetically by identifier.</description></item>
    /// <item><description><b>Automated Assembly Scanning:</b> Discovers classes decorated with <see cref="AutoRegisterAttribute"/> via <see cref="AutoRegister(IPluginManagementService)"/> without premature instantiation.</description></item>
    /// <item><description><b>Instance Lifecycle Management:</b> Tracks singletons or transient instances based on the <c>keepInstance</c> parameter. Deactivating or evicting an entry disposes cached instances if they implement <see cref="IDisposable"/>.</description></item>
    /// <item><description><b>Thread-Safety &amp; Reentrancy:</b> Internal maps are guarded by monitor locks during mutations. Factory invocations occur outside locks, guaranteeing deadlock immunity during nested registrations.</description></item>
    /// </list>
    /// </para>
    /// </remarks>
    internal sealed class SortedFactory<T> where T : class
    {
        public class Entry(Identifier id, Func<T?>? factory = null, double order = 0, bool active = true) : IFactoryEntry<T>, IComparable<Entry>, IEquatable<Entry>, IEquatable<Identifier>
        {
            public Identifier Id
            {
                get => id;
                private set => id = value;
            }

            public double Order => order;

            public bool Active
            {
                get => active;
                set => active = value;
            }

            private T? _cache = null;

            public T? Value => Instance();

            private readonly object _sync = new();

            public T? Instance(bool fresh = false)
            {
                lock (_sync)
                    return (fresh) ? _cache = Instantiate() : _cache ??= Instantiate();
            }

            public T? Instantiate()
            {
                try
                {
                    return factory?.Invoke();
                }
                catch (Exception ex)
                {
                    Logger.LogWarning($"[SOS.API] Failed to instantiate type '{typeof(T).Name}' of Id '{Id}'. \nException: {ex.Message}");
                    Logger.LogDebugError(ex.StackTrace);
                    return null;
                }
            }

            public int CompareTo(Entry? other)
            {
                var idEqual = Id.CompareTo(other?.Id);
                if (idEqual == 0) return 0;
                var a = Order.CompareTo(other?.Order);
                return (a == 0) ? idEqual : a;
            }

            public bool Equals(Entry? other) => other != null && Id.Equals(other.Id);

            public bool Equals([AllowNull] Identifier other) => other != null && Id == other;

            public override bool Equals(object? obj) => Equals(obj as Entry);

            public override int GetHashCode() => Id.GetHashCode();

            public void Drop()
            {
                lock (_sync)
                {
                    if (_cache?.TryCast<IDisposable>(out var disposableInstance) ?? false)
                        disposableInstance?.Dispose();
                    _cache = null;
                }
            }

            public void Dispose()
            {
                Drop();
                GC.SuppressFinalize(this);
            }

            ~Entry() => Dispose();

            public static implicit operator Entry(Identifier key) => new(key);

            public static implicit operator Entry(string key) => new(key);
        }

        private readonly SortedSet<Entry> entries = [];

        private void Add(string id, double order, bool active, Func<T?> factory)
        {
            lock (entries)
                entries.Add(new(id, factory, order, active));
        }

        /// <summary>
        /// Unregisters an entry or evicts its cached instance by identifier.
        /// </summary>
        /// <param name="key">The unique string identifier of the component to remove.</param>
        /// <param name="onlyInstance">If <c>true</c>, evicts and disposes only the cached instance, preserving the factory registration. If <c>false</c>, completely removes both the registration and the instance.</param>
        /// <returns><c>true</c> if the entry or instance was found and removed; otherwise, <c>false</c>.</returns>
        /// <remarks>
        /// If <paramref name="onlyInstance"/> is <c>false</c>, the internal sorted cache is marked dirty so subsequent queries regenerate the output list.
        /// Any evicted instance implementing <see cref="IDisposable"/> has its <see cref="IDisposable.Dispose"/> method called immediately under lock.
        /// </remarks>
        public bool Remove(string key, bool onlyInstance = false)
        {

            if (entries.TryGetValue(key, out var entry))
            {
                entry.Drop();
                if (onlyInstance) return true;
                lock (entries)
                    return entries.Remove(key);
            }
            return false;
        }

        /// <summary>
        /// Registers an instance, type, or factory delegate under the specified identifier and priority order.
        /// </summary>
        /// <param name="obj">The target to register. Supports concrete <see cref="Type"/>, <see cref="Func{T}"/>, <see cref="Func{Object}"/>, or an existing instance.</param>
        /// <param name="id">Optional unique identifier. If <c>null</c>, defaults to the type's full name.</param>
        /// <param name="order">Priority order determining placement in sorted queries. Lower values appear first. Defaults to <c>0.0</c>.</param>
        /// <param name="active">Whether the component is initially enabled. Defaults to <c>true</c>.</param>
        /// <returns><c>true</c> if registration succeeded; <c>false</c> if <paramref name="obj"/> is null or fails type contract validation.</returns>
        /// <remarks>
        /// When registering a <see cref="Type"/>, it must be a non-abstract class with a public parameterless constructor.
        /// Registering an entry marks the sorted snapshot cache as dirty and invalidates any prior cached instance under <paramref name="id"/>.
        /// </remarks>
        public bool Register(object obj, string? id = null, double order = 0, bool active = true)
        {
            bool isSuccess = obj switch
            {
                null => false,
                Type type => RegisterType(id, order, active, type),
                Func<T?> func => RegisterFunc(id, order, active, func),
                Func<object> func => RegisterFunc(id, order, active, func),
                _ => RegisterInstance(id, order, active, obj)
            };

            if (isSuccess) Logger.LogDebug($"[SOS.API] Registered '{id}' of type '{obj?.GetType().FullOrName()}' as '{typeof(T).Name}'.", level: LogLevel.Trace);
            else Logger.LogError($"[SOS.API] Failed to register '{id}' of type '{obj?.GetType().FullOrName()}' as '{typeof(T).Name}'.");

            return isSuccess;
        }

        private bool RegisterType(string? id, double order, bool active, Type type)
        {
            if (type.IsAbstract || type.IsInterface || type.GetConstructor(Type.EmptyTypes) == null)
            {
                Logger.LogError($"[SOS.API] Register failed for type: '{type.FullName}', not be an interface, abstract object, and non-void constructor.");
                return false;
            }

            id ??= type.FullOrName();

            try
            {
                Add(id, order, active, () => Activator.CreateInstance(type)?.Cast<T>()); // TODO: Añadir el resto de comprobaciones antes de registrar para evitar que CreateInstance devuelva nulo.

                return true;
            }
            catch (Exception ex)
            {
                Logger.LogWarning($"[SOS.API] Failed to register type '{type.FullName}' as '{typeof(T).Name}'. Type does not satisfy contract. \nException: {ex.Message}");
                return false;
            }
        }

        private bool RegisterFunc(string? id, double order, bool active, Func<T?> func)
        {
            id ??= func.Method.ReturnType.FullOrName();

            Add(id, order, active, func);
            return true;
        }

        private bool RegisterFunc(string? id, double order, bool active, Func<object> func)
        {
            id ??= func.Method.ReturnType.FullOrName();

            Add(id, order, active, () => func()?.Cast<T>());
            return true;
        }

        private bool RegisterInstance(string? id, double order, bool active, object obj)
        {
            id ??= obj.GetType().FullOrName();

            try
            {
                var instance = obj.Cast<T>();
                Add(id, order, active, () => instance);
                return true;
            }
            catch (Exception ex)
            {
                Logger.LogWarning($"[SOS.API] Failed to register instance from type '{obj.GetType()}' as '{typeof(T).Name}'. Instance does not satisfy contract. \nException: {ex.Message}");
                return false;
            }
        }

        /// <summary>
        /// Automatically discovers and registers all loaded types implementing <typeparamref name="T"/> decorated with <see cref="AutoRegisterAttribute"/>.
        /// </summary>
        /// <param name="pluginManagementService">The LuaCs plugin management service used for assembly reflection scanning.</param>
        /// <returns><c>true</c> if at least one component was registered; otherwise, <c>false</c>.</returns>
        public bool AutoRegister(IPluginManagementService pluginManagementService) => AutoRegister<T>(pluginManagementService);

        /// <summary>
        /// Automatically discovers and registers all loaded types implementing or deriving from <typeparamref name="TAuto"/> decorated with <see cref="AutoRegisterAttribute"/>.
        /// </summary>
        /// <typeparam name="TAuto">The filter contract type to scan for. Must derive from or implement <typeparamref name="T"/>.</typeparam>
        /// <param name="pluginManagementService">The LuaCs plugin management service used for assembly reflection scanning.</param>
        /// <returns><c>true</c> if at least one component was registered; otherwise, <c>false</c>.</returns>
        /// <remarks>
        /// Reads metadata (<see cref="AutoRegisterAttribute.Id"/>, <see cref="AutoRegisterAttribute.Order"/>, and <see cref="AutoRegisterAttribute.Active"/>)
        /// directly from the attribute metadata without instantiating the classes during the scan.
        /// </remarks>
        public bool AutoRegister<TAuto>(IPluginManagementService pluginManagementService) where TAuto : T
        {
            var result = pluginManagementService.GetImplementingTypes<TAuto>();

            bool anySuccess = false;

            if (result.IsSuccess)
                foreach (Type t in result.Value)
                {
                    var attr = t.GetCustomAttribute<AutoRegisterAttribute>();
                    if (attr != null)
                        anySuccess |= RegisterType(attr.Id ?? t.FullOrName(), attr.Order, attr.Active, t);
                }

            return anySuccess;
        }

        /// <summary>
        /// Updates the activation state of a registered component by identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the component.</param>
        /// <param name="active">The new activation state. If <c>false</c>, the component is omitted from sorted queries.</param>
        /// <returns><c>true</c> if the component was found; <c>false</c> if no registration exists under <paramref name="id"/>.</returns>
        /// <remarks>
        /// If a component is deactivated and has an active cached instance implementing <see cref="IDisposable"/>,
        /// it is disposed and evicted immediately. Marks the sorted snapshot cache as dirty.
        /// </remarks>
        public bool SetActive(string id, bool active)
        {
            if (entries.TryGetValue(id, out var entry))
            {
                entry.Active = active;
                return true;
            }

            return false;
            //lock (_dict)
            //{
            //    if (!_dict.TryGetValue(id, out var entry)) return false;
            //    if (entry.IsActive == active) return true;
            //
            //    _dict[id] = (entry.Order, active, entry.Factory);
            //    _isDirty = true;
            //
            //    if (!active && _instances.Remove(id, out var instance))
            //    {
            //        if (instance is IDisposable d) d.Dispose();
            //    }
            //
            //    return true;
            //}
        }

        /// <summary>
        /// Checks whether a registered component is currently enabled.
        /// </summary>
        /// <param name="id">The unique identifier of the component.</param>
        /// <returns><c>true</c> if registered and active; otherwise, <c>false</c>.</returns>
        public bool IsActive(string id)
        {
            return entries.TryGetValue(id, out var entry) && entry.Active;
        }

        public IEnumerable<Entry> GetAll(bool onlyActives = true)
        {
            foreach (var entry in entries) if (!onlyActives || entry.Active)
                yield return entry;
        }

        /// <summary>
        /// Resolves and enumerates all currently active components in registration order.
        /// </summary>
        /// <param name="onlyActives">If <c>true</c>, returns only instances that marked with in `IsActive`. If <c>false</c>, returns all instances.</param>
        /// <param name="keepInstance">If <c>true</c>, resolved instances are stored in the internal cache for future queries.</param>
        /// <returns>An enumerable sequence of resolved (Id, Instance) pairs for active components.</returns>
        /// <remarks>
        /// <para>
        /// <b>Safe Resolution:</b> For each active entry, checks the instance cache first. If missing, invokes the factory delegate
        /// and caches the result if <paramref name="keepInstance"/> is <c>true</c>.
        /// </para>
        /// <para>
        /// If a factory throws an exception during construction, a warning is logged via <see cref="Logger"/> and enumeration
        /// skips to the next entry without aborting the sequence.
        /// </para>
        /// </remarks>
        public IEnumerable<T> GetAllInstances(bool onlyActives = true, bool fresh = false)
        {
            foreach (var entry in GetAll(onlyActives))
            {
                T? result = entry.Instance(fresh);
                if (result != null) yield return result;
            }
        }

        public Entry? Get(string id)
            => (id != null && entries.TryGetValue(id, out var entry)) ? entry : null;

        /// <summary>
        /// Resolves an active component instance by its unique identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the component to retrieve.</param>
        /// <param name="keepInstance">If <c>true</c>, caches the resolved instance in memory for subsequent calls.</param>
        /// <returns>The resolved instance if found and active; otherwise, <c>null</c>.</returns>
        /// <remarks>
        /// Execution order:
        /// <list type="number">
        /// <item><description>Checks if an instance is already cached in memory under lock.</description></item>
        /// <item><description>If not cached, extracts the factory delegate under lock and executes it <i>outside the monitor lock</i> to prevent deadlocks.</description></item>
        /// <item><description>If <paramref name="keepInstance"/> is <c>true</c>, stores the new instance back in the cache under lock.</description></item>
        /// </list>
        /// </remarks>
        public T? GetInstance(string id, bool fresh = false)
            => Get(id)?.Instance(fresh);

        public Entry? First() => entries.FirstOrDefault();

        /// <summary>
        /// Resolves the first active component according to registration order.
        /// </summary>
        /// <param name="keepInstance">If <c>true</c>, caches the resolved instance.</param>
        /// <returns>The first active component instance, or <c>null</c> if no active components are registered.</returns>
        public T? FirstInstance(bool fresh = false)
            => First()?.Instance(fresh);

        public Entry? GetOrFirst(string? id = null)
            => id == null ? First() : Get(id);

        /// <summary>
        /// Resolves the active component matching <paramref name="id"/>, falling back to the first active component if not found.
        /// </summary>
        /// <param name="id">The unique identifier to look up. If <c>null</c> or not found, falls back to <see cref="First"/>.</param>
        /// <param name="keepInstance">If <c>true</c>, caches the resolved instance.</param>
        /// <returns>The resolved instance, or <c>null</c> if no active registrations exist.</returns>
        public T? GetOrFirstInstance(string? id, bool fresh = false)
            => GetOrFirst(id)?.Instance(fresh);
        //  => (id != null && Get(id, keepInstance) is { } instance) ? instance : First(keepInstance);

        /// <summary>
        /// Clears the factory contents, disposing cached instances and optionally removing all registrations.
        /// </summary>
        /// <param name="onlyInstances">If <c>true</c>, disposes and clears only cached instances while preserving factory registrations and sorted cache. If <c>false</c>, completely clears all registrations and resets the factory.</param>
        /// <remarks>
        /// Any cached instance implementing <see cref="IDisposable"/> has its <see cref="IDisposable.Dispose"/> method called under lock.
        /// When <paramref name="onlyInstances"/> is <c>false</c>, the internal sorted snapshot is emptied and the dirty flag is cleared.
        /// </remarks>
        public void Clear()
        {
            Clean();
            lock (entries)
            {
                entries.Clear();
                Logger.LogDebugWarning($"Cleaning factory to type: '{typeof(T).FullOrName()}'");
                return;
            }
        }

        public void Clean()
        {
            lock (entries)
            {
                foreach (var entry in entries)
                    entry.Drop();
            }
        }
    }
}