// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using System.Reflection;
using Barotrauma.LuaCs;

namespace SOS
{
    /// <summary>
    /// Internal ordered discovery factory for mod components.
    /// </summary>
    /// <typeparam name="T">The type of component managed by this factory. Must be a reference type (<c>class</c>).</typeparam>
    /// <remarks>
    /// <para>
    /// <b>Ordered Discovery:</b> Components are registered with an order value that determines their priority position.
    /// When retrieving sorted components via <see cref="GetSorted"/>, items are ordered by ascending order, then by key name.
    /// </para>
    /// <para>
    /// <b>Auto-Registration:</b> Via <see cref="AutoRegister{IPluginManagementService}"/>, types decorated with
    /// <see cref="AutoRegisterAttribute"/> can be automatically discovered and registered through the
    /// <see cref="Barotrauma.LuaCs.IPluginManagementService"/>.
    /// </para>
    /// <para>
    /// <b>Instance Caching:</b> The factory maintains a cache of instantiated instances (dictionary `_instances`).
    /// </para>
    /// <para>
    /// <b>Thread Safety:</b> Registration and state checks occur under a monitor lock on the internal dictionary
    /// (_dict), ensuring atomic updates. However, handler execution and instance retrieval occur outside locks,
    /// guaranteeing reentrancy safety and zero deadlocks.
    /// </para>
    /// </remarks>
    internal sealed class SortedFactory<T> where T : class
    {
        private readonly Dictionary<string, (double Order, bool IsActive, Func<T?> Factory)> _dict = [];
        private readonly Dictionary<string, T> _instances = [];
        private (string Id, double Order, Func<T?> Factory)[] _cache = [];
        private bool _isDirty = false;

        private void Add(string id, double order, bool active, Func<T?> Factory)
        {
            lock (_dict)
            {
                _dict[id] = (order, active, Factory);
                _instances.Remove(id);
                _isDirty = true;
            }
        }

        /// <summary>
        /// Removes a registered entry by key from the factory.
        /// </summary>
        /// <param name="key">The unique identifier of the entry to remove.</param>
        /// <param name="onlyInstance">If <c>true</c>, only removes the cached instance without removing the registration.
        /// If <c>false</c> (default), removes the registration and also removes the cached instance.</param>
        /// <returns><c>true</c> if the entry was found and removed (or instance removed); <c>false</c> if the key was not found.</returns>
        /// <remarks>
        /// The registration is removed from the internal dictionary (_dict) when <paramref name="onlyInstance"/> is <c>false</c>.
        /// If a cached instance exists and implements <see cref="IDisposable"/>, it is disposed.
        /// </remarks>
        public bool Remove(string key, bool onlyInstance = false)
        {
            lock (_dict)
            {
                var isSuccess = !onlyInstance && _dict.Remove(key);
                _instances.Remove(key);
                _isDirty |= isSuccess;
                return isSuccess;
            }
        }

        /// <summary>
        /// Registers an object or factory delegate as a component of type <typeparamref name="T"/>.
        /// </summary>
        /// <param name="obj">The object to register. Supports the following types:
        /// <list type="bullet">
        /// <item><c>null</c>: registration fails, returns <c>false</c>.</item>
        /// <item><see cref="Type"/>: registers a type that must be instantiable (not abstract, have a non-void constructor).</item>
        /// <item><see cref="Func{T}"/>: a factory delegate that creates instances of type <typeparamref name="T"/>.</item>
        /// <item>existing <paramref name="obj"/> instance: registers the instance directly.</item>
        /// </list>
        /// </param>
        /// <param name="id">Optional unique identifier. If <c>null</c>, the type's full name is used as the ID.</param>
        /// <param name="order">Registration order. Determines position in sorted output. Lower values appear first. Defaults to 0.</param>
        /// <param name="active">Whether the registration is initially active. Defaults to true.</param>
        /// <returns><c>true</c> if registration succeeded; <c>false</c> if <paramref name="obj"/> is <c>null</c> or fails type contract checks.</returns>
        /// <remarks>
        /// The type contract requires the registered type to be <c>class</c>, not abstract, have a non-void parameterless constructor,
        /// and be castable to <typeparamref name="T"/>. Registration failures are logged via <see cref="Logger"/> at trace level.
        /// </remarks>
        public bool Register(object obj, string? id = null, double order = 0, bool active = true)
        {
            bool isSuccess = obj switch
            {
                null => false,
                Type type => RegisterType(id, order, active, type),
                Func<T?> func => RegisterFunc(id, order, active, func),
                Func<object> func => RegisterFunc(id, order, active, func),
                _ => RegisterInstance(id, order, active, obj)
            };

            if (isSuccess) Logger.LogDebug($"[SOS.API] Registered '{id}' of type '{obj?.GetType().FullOrName()}' as '{typeof(T).Name}'.", level: LogLevel.Trace);
            else Logger.LogError($"[SOS.API] Failed to register '{id}' of type '{obj?.GetType().FullOrName()}' as '{typeof(T).Name}'.");

            return isSuccess;
        }

        /// <summary>
        /// Registers a type as a component of type <typeparamref name="T"/>.
        /// </summary>
        /// <param name="id">The identifier to use for registration. If <c>null</c>, the type's full name is used.</param>
        /// <param name="order">Registration order. Lower values appear first in sorted output. Defaults to 0.</param>
        /// <param name="active">Whether the registration is initially active. Defaults to true.</param>
        /// <param name="type">The type to register. Must be instantiable (not abstract, have a non-void constructor) and castable to <typeparamref name="T"/>.</param>
        /// <returns><c>true</c> if the type was successfully registered; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// The type must not be abstract, must not be an interface, and must have a non-void parameterless constructor.
        /// Failed registrations are logged via <see cref="Logger"/> with details about the type contract violation.
        /// </remarks>
        private bool RegisterType(string? id, double order, bool active, Type type)
        {
            if (type.IsAbstract || type.IsInterface || type.GetConstructor(Type.EmptyTypes) == null)
            {
                Logger.LogError($"[SOS.API] Register failed for type: '{type.FullName}', not be an interface, abstract object, and non-void constructor.");
                return false;
            }

            id ??= type.FullOrName();

            try
            {
                Add(id, order, active, () => Activator.CreateInstance(type)?.Cast<T>());

                return true;
            }
            catch (Exception ex)
            {
                Logger.LogWarning($"[SOS.API] Failed to register type '{type.FullName}' as '{typeof(T).Name}'. Type does not satisfy contract. \nException: {ex.Message}");
                return false;
            }
        }

        /// <summary>
        /// Registers a factory delegate as a component of type <typeparamref name="T"/>.
        /// </summary>
        /// <param name="id">The identifier to use for registration. If <c>null</c>, the factory's method return type full name is used.</param>
        /// <param name="order">Registration order. Lower values appear first in sorted output. Defaults to 0.</param>
        /// <param name="active">Whether the registration is initially active. Defaults to true.</param>
        /// <param name="func">The factory delegate that creates instances of type <typeparamref name="T"/>.</param>
        /// <returns><c>true</c> if registration succeeded.</returns>
        /// <remarks>
        /// The delegate must return type <typeparamref name="T"/>. The identifier is derived from the delegate's method return type full name.
        /// </remarks>
        private bool RegisterFunc(string? id, double order, bool active, Func<T?> func)
        {
            id ??= func.Method.ReturnType.FullOrName();

            Add(id, order, active, func);
            return true;
        }

        /// <summary>
        /// Registers a factory delegate (returning <see cref="object"/>) as a component of type <typeparamref name="T"/>.
        /// </summary>
        /// <param name="id">The identifier to use for registration. If <c>null</c>, the factory's method return type full name is used.</param>
        /// <param name="order">Registration order. Lower values appear first in sorted output. Defaults to 0.</param>
        /// <param name="active">Whether the registration is initially active. Defaults to true.</param>
        /// <param name="func">The factory delegate that creates instances, boxed as <see cref="object"/>.</param>
        /// <returns><c>true</c> if registration succeeded.</returns>
        /// <remarks>
        /// The delegate must return a value that can be cast to <typeparamref name="T"/>. The identifier is derived from the delegate's method return type full name.
        /// </remarks>
        private bool RegisterFunc(string? id, double order, bool active, Func<object> func)
        {
            id ??= func.Method.ReturnType.FullOrName();

            Add(id, order, active, () => func().Cast<T>());
            return true;
        }

        /// <summary>
        /// Registers an existing instance as a component of type <typeparamref name="T"/>.
        /// </summary>
        /// <param name="id">The identifier to use for registration. If <c>null</c>, the instance's type full name is used.</param>
        /// <param name="order">Registration order. Lower values appear first in sorted output. Defaults to 0.</param>
        /// <param name="active">Whether the registration is initially active. Defaults to true.</param>
        /// <param name="obj">The instance to register. Must be non-null and castable to <typeparamref name="T"/>.</param>
        /// <returns><c>true</c> if registration succeeded; <c>false</c> if the instance fails the type contract.</returns>
        /// <remarks>
        /// The instance is stored and later retrieved via the factory delegate. Failed registrations are logged via <see cref="Logger"/>.
        /// </remarks>
        private bool RegisterInstance(string? id, double order, bool active, object obj)
        {
            id ??= obj.GetType().FullOrName();

            try
            {
                Add(id, order, active, () => obj.Cast<T>());
                return true;
            }
            catch (Exception ex)
            {
                Logger.LogWarning($"[SOS.API] Failed to register instance from type '{obj.GetType()}' as '{typeof(T).Name}'. Instance does not satisfy contract. \nException: {ex.Message}");
                return false;
            }
        }

        /// <summary>
        /// Auto-registers components from the provided <see cref="IPluginManagementService"/>.
        /// </summary>
        /// <param name="pluginManagementService">The service used to discover implementing types.</param>
        /// <returns><c>true</c> if at least one component was successfully registered; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// Retrieves all implementing types of <typeparamref name="T"/> via <see cref="IPluginManagementService.GetImplementingTypes{T}"/>
        /// and checks each for the <see cref="AutoRegisterAttribute"/>. If present, the attribute's values (<see cref="AutoRegisterAttribute.Id"/>,
        /// <see cref="AutoRegisterAttribute.Order"/>, <see cref="AutoRegisterAttribute.Active"/>) are used for registration.
        /// </remarks>
        public bool AutoRegister(IPluginManagementService pluginManagementService) => AutoRegister<T>(pluginManagementService);

        /// <summary>
        /// Auto-registers components of type <typeparamref name="TAuto"/> from the provided <see cref="IPluginManagementService"/>.
        /// </summary>
        /// <typeparam name="TAuto">The base type that registered types must implement or inherit from.</typeparam>
        /// <param name="pluginManagementService">The service used to discover implementing types.</param>
        /// <returns><c>true</c> if at least one component was successfully registered; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// Retrieves all implementing types of <typeparamref name="TAuto"/> via <see cref="IPluginManagementService.GetImplementingTypes{T}"/>
        /// and checks each for the <see cref="AutoRegisterAttribute"/>. If present, the attribute's values (<see cref="AutoRegisterAttribute.Id"/>,
        /// <see cref="AutoRegisterAttribute.Order"/>, <see cref="AutoRegisterAttribute.Active"/>) are used for registration via <see cref="RegisterType"/>.
        /// </remarks>
        public bool AutoRegister<TAuto>(IPluginManagementService pluginManagementService) where TAuto : T
        {
            var result = pluginManagementService.GetImplementingTypes<TAuto>();

            bool anySuccess = false;

            if (result.IsSuccess)
                foreach (Type t in result.Value)
                {
                    var attr = t.GetCustomAttribute<AutoRegisterAttribute>();
                    if (attr != null)
                        anySuccess |= RegisterType(attr.Id ?? t.FullOrName(), attr.Order, attr.Active, t);
                }


            return anySuccess;
        }

        /// <summary>
        /// Sets the active state of a registered component identified by <paramref name="id"/>.
        /// </summary>
        /// <param name="id">The unique identifier of the component to activate or deactivate.</param>
        /// <param name="active">The desired active state. If <c>true</c>, the component is activated; if <c>false</c>, it is deactivated.</param>
        /// <returns><c>true</c> if the component was found and its state was set; <c>false</c> if no component with the given ID exists.</returns>
        /// <remarks>
        /// Thread-safety: This method acquires a monitor lock on the internal dictionary (_dict) to ensure atomic state updates.
        /// If the component is being deactivated and a cached instance implements <see cref="IDisposable"/>, it is disposed.
        /// </remarks>
        public bool SetActive(string id, bool active)
        {
            lock (_dict)
            {
                if (!_dict.TryGetValue(id, out var entry)) return false;
                if (entry.IsActive == active) return true;

                _dict[id] = (entry.Order, active, entry.Factory);
                _isDirty = true;

                if (!active && _instances.Remove(id, out var instance))
                {
                    if (instance is IDisposable d) d.Dispose();
                }

                return true;
            }
        }

        /// <summary>
        /// Checks whether a registered component identified by <paramref name="id"/> is currently active.
        /// </summary>
        /// <param name="id">The unique identifier of the component to check.</param>
        /// <returns><c>true</c> if the component exists and is active; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// Thread-safety: This method acquires a monitor lock on the internal dictionary (_dict) to ensure a consistent read.
        /// </remarks>
        public bool IsActive(string id)
        {
            lock (_dict)
                return _dict.TryGetValue(id, out var entry) && entry.IsActive;
        }

        /// <summary>
        /// Retrieves all active registrations sorted by order and key.
        /// </summary>
        /// <returns>An array of tuples containing (ID, Order, Factory) for all active registrations, sorted ascending by order then by key name.</returns>
        /// <remarks>
        /// If the internal cache is marked as dirty (due to modifications since last retrieval), the sorted list is regenerated
        /// from the dictionary under a monitor lock for thread safety.
        /// The returned array is a snapshot; subsequent modifications to the factory will not be reflected until this method is called again.
        /// </remarks>
        public (string Id, double Order, Func<T?> Factory)[] GetSorted()
        {
            if (_isDirty)
            {
                lock (_dict)
                {
                    _cache = [.. _dict
                        .Where(kvp => kvp.Value.IsActive)
                        .OrderBy(kvp => kvp.Value.Order)
                        .ThenBy(kvp => kvp.Key)
                        .Select(kvp => (kvp.Key, kvp.Value.Order, kvp.Value.Factory))];

                    _isDirty = false;
                }
            }
            return _cache;
        }

        /// <summary>
        /// Retrieves all registered components, optionally keeping cached instances.
        /// </summary>
        /// <param name="keepInstance">If <c>true</c>, cached instances are returned (and updated). If <c>false</c>, each call creates new instances via factories.</param>
        /// <returns>An enumerable of tuples containing (ID, Instance) for all registered components.</returns>
        /// <remarks>
        /// For each registration, the factory delegate is invoked to create an instance. If <paramref name="keepInstance"/>
        /// is true and the instance is non-null, it is cached in the internal dictionary for faster subsequent access.
        /// Failed instantiation is logged via <see cref="Logger"/> and skipped (iteration continues).
        /// </remarks>
        public IEnumerable<(string Id, T Instance)> GetAll(bool keepInstance = true)
        {
            foreach (var (Id, _, factory) in GetSorted())
            {
                T? instance = null;
                lock (_dict)
                    _instances.TryGetValue(Id, out instance);

                try
                {
                    instance ??= factory();
                }
                catch (Exception ex)
                {
                    Logger.LogWarning($"[SOS.API] Failed to instantiate section '{typeof(T).Name}' of Id '{Id}'. \nException: {ex.Message}");
                    continue;
                }

                if (instance != null)
                {
                    if (keepInstance)
                        lock (_dict)
                            _instances[Id] = instance;
                    yield return (Id, instance);
                }
            }
        }

        /// <summary>
        /// Retrieves a component by its identifier, optionally keeping the cached instance.
        /// </summary>
        /// <param name="id">The unique identifier of the component to retrieve.</param>
        /// <param name="keepInstance">If <c>true</c>, the cached instance is returned if available; otherwise, a new instance is created via the factory.</param>
        /// <returns>The component instance if found; otherwise, <c>null</c>.</returns>
        /// <remarks>
        /// The retrieval process:
        /// 1. Checks the cached instance dictionary (_instances) for a previously cached instance.
        /// 2. If not cached, checks the registration dictionary (_dict) for the entry.
        /// 3. If found, invokes the factory delegate to create an instance.
        /// 4. If <paramref name="keepInstance"/> is true and the instance is non-null, caches it for future calls.
        /// Failed instantiation is logged via <see cref="Logger"/> and null is returned.
        /// </remarks>
        public T? Get(string id, bool keepInstance = true)
        {
            Func<T?>? factory;
            lock (_dict)
            {
                if (_instances.TryGetValue(id, out var cached))
                    return cached;

                if (!_dict.TryGetValue(id, out var entry))
                    return null;

                factory = entry.Factory;
            }

            T? instance;

            try
            {
                instance = factory();
            }
            catch (Exception ex)
            {
                Logger.LogWarning($"[SOS.API] Failed to instantiate factory of Id '{id}'. \nException: {ex.Message}");
                return null;
            }

            lock (_dict)
                if (keepInstance && instance != null)
                    _instances[id] = instance;

            return instance;
        }

        /// <summary>
        /// Retrieves the first active component, ordered by registration order.
        /// </summary>
        /// <param name="keepInstance">If <c>true</c>, the returned instance is cached for subsequent calls.</param>
        /// <returns>The first active component, or <c>null</c> if no components are registered.</returns>
        /// <remarks>
        /// Calls <see cref="GetSorted"/> to obtain the sorted list, then returns the first element's instance via <see cref="Get"/>.
        /// </remarks>
        public T? First(bool keepInstance = true)
        {
            var sorted = GetSorted();
            return sorted.Length > 0 ? Get(sorted[0].Id, keepInstance) : null;
        }

        /// <summary>
        /// Retrieves a component by identifier, or the first active component if not found.
        /// </summary>
        /// <param name="id">The unique identifier to look up. If non-null and a component with this ID is found, it is returned.</param>
        /// <param name="keepInstance">If <c>true</c>, the returned instance is cached for subsequent calls.</param>
        /// <returns>The component identified by <paramref name="id"/>, or the first active component if <paramref name="id"/> is null or not found.</returns>
        /// <remarks>
        /// If <paramref name="id"/> is null, behavior is equivalent to calling <see cref="First"/>.
        /// If <paramref name="id"/> is provided but not found, falls back to <see cref="First"/>.
        /// </remarks>
        public T? GetOrFirst(string? id, bool keepInstance = true)
            => (id != null && Get(id, keepInstance) is { } instance) ? instance : First(keepInstance);

        /// <summary>
        /// Clears all registrations and instances from the factory.
        /// </summary>
        /// <param name="onlyInstances">If <c>true</c>, only removes cached instances and disposes them if <see cref="IDisposable"/>,
        /// leaving the registration dictionary intact. If <c>false</c> (default), clears both the registration dictionary and cached instances.</param>
        /// <remarks>
        /// When <paramref name="onlyInstances"/> is <c>false</c>, the internal cache (_cache) is also cleared and the dirty flag (_isDirty) is reset.
        /// All cached instances implementing <see cref="IDisposable"/> are disposed.
        /// This operation is performed under a monitor lock on the internal dictionary to ensure thread safety.
        /// </remarks>
        public void Clear(bool onlyInstances = false)
        {
            lock (_dict)
            {
                if (!onlyInstances)
                {
                    _dict.Clear();
                    _cache = [];
                    _isDirty = false;
                    Logger.LogDebugWarning($"Cleaning factory to type: '{typeof(T).FullOrName()}'");
                }
                foreach (var kv in _instances)
                    if (kv.Value is IDisposable i) i.Dispose();

                _instances.Clear();
            }
        }
    }
}