// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using Barotrauma;
using Microsoft.Xna.Framework;
using SOS.Panels.ItemPanel;
using SOS.Prefabs;

namespace SOS.GUI
{
    /// <summary>
    /// A composite UI element displaying a label, clickable tags, and a dropdown of prefab items.
    /// </summary>
    /// <remarks>
    /// Creates a row with a label (30% width), clickable tags as hyperlinks (55% width), and a dropdown
    /// (fixed 36x24px) on the right. The tags are rendered using <see cref="RichStringExt.JoinToRichString"/>
    /// with comma separators and LightSkyBlue color. The dropdown is populated with prefabs, showing a
    /// gold star prefix for favorite items. The height of the row is automatically calculated based on
    /// the tags text size.
    /// </remarks>
    public class GUIDesplegableBox : GUIFrame
    {
        private readonly GUITextBlock _tagsText;
        /// <summary>
        /// Creates a new desplegable box with tags and a prefab dropdown.
        /// </summary>
        /// <param name="rectT">The parent component to which the row will be added.</param>
        /// <param name="onBadgeClick">Callback invoked when a tag badge is clicked, receiving the tag string.</param>
        /// <param name="labelText">The label text displayed on the left (30% width, gray).</param>
        /// <param name="tags">The tags to display as clickable hyperlinks (55% width).</param>
        /// <param name="items">The prefabs to populate the dropdown with.</param>
        /// <param name="onPrimary">Callback for primary click on a prefab in the dropdown.</param>
        /// <param name="onSecondary">Callback for secondary click on a prefab in the dropdown.</param>
        /// <param name="style">Style for the main GUIFrame.</param>
        /// <remarks>
        /// Creates a row frame with: label (left), tags as hyperlinks (center), and a dropdown (right).
        /// Tags are joined with comma separators and colored LightSkyBlue.
        /// Dropdown items show a gold star prefix for favorites.
        /// </remarks>
        public GUIDesplegableBox(RectTransform rectT, Action<string> onBadgeClick, string labelText, IEnumerable<string> tags, IEnumerable<Prefab> items, Action<Prefab> onPrimary, Action<Prefab> onSecondary, string? style = null) : base(rectT, style)
        {
            _ = new GUITextBlock(new RectTransform(new Vector2(0.3f, 1f), RectTransform, Anchor.CenterLeft), labelText, font: GUIStyle.SmallFont, textColor: Color.Gray) { CanBeFocused = false };

            RichString tagsRich = tags.JoinToRichString(", ", t => t, t => Color.LightSkyBlue);
            _tagsText = new GUITextBlock(new RectTransform(new Vector2(0.55f, 1f), RectTransform, Anchor.TopLeft) { RelativeOffset = new Vector2(0.3f, 0f) }, "", wrap: true, font: GUIStyle.SmallFont, textAlignment: Alignment.CenterLeft);
            _tagsText.SetRichText(tagsRich);

            _tagsText.BindHyperlinks(tags, tag => onBadgeClick?.Invoke(tag));

            var dropDown = new GUIDropDown2(new RectTransform(new Point(36, 24), RectTransform, Anchor.TopRight) { IsFixedSize = true }, elementCount: Math.Min((int)items.Count(), 8), listBoxWidth: (int)(rectT.Rect.Width * 0.95f), style: "GUIDropDown", expandToRight: false);

            foreach (var item in items)
            {
                bool isFav = PrefabHelper.IsFavorite(item.Identifier.Value);
                string prefix = isFav ? " *" : "";

                CardBuilder.DrawCompactItemRow(dropDown.ListBox.Content, item, 1, true, prefix, isFav ? Color.Gold : Color.White,
                onPrimaryClick: (p) => { onPrimary?.Invoke(p); dropDown.Dropped = false; },
                onSecondaryClick: onSecondary);
            }


            UpdateHeight();
            RectTransform.SizeChanged += UpdateHeight;
        }

        /// <summary>
        /// Updates the row height to fit the tags text.
        /// </summary>
        /// <remarks>
        /// Sets the minimum and maximum height based on the tags text height plus 4 pixels of padding.
        /// The minimum height is at least 24 pixels. This is called automatically when the component
        /// is created and whenever the parent rectangle size changes.
        /// </remarks>
        public void UpdateHeight()
        {
            int h = Math.Max(24, (int)_tagsText.TextSize.Y + 4);
            RectTransform.MinSize = new Point(0, h);
            RectTransform.MaxSize = new Point(int.MaxValue, h);
        }
    }
}
