// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using Barotrauma;
using Microsoft.Xna.Framework;

namespace SOS.GUI
{
    /// <summary>
    /// A collapsible container with an animated chevron icon and a content area.
    /// </summary>
    /// <remarks>
    /// Consists of a header button with a dropdown-style chevron icon and a content area
    /// (<see cref="GUILayoutBuilder"/>) that can be shown/hidden. The chevron rotates -90 degrees
    /// when collapsed. Toggling triggers layout recalculation on the accordion and its parent layout group.
    /// </remarks>
    public sealed class GUIAccordion : GUILayoutGroupAuto
    {
        /// <summary>
        /// The fixed height of the accordion header in pixels.
        /// </summary>
        public const int HeaderHeight = 28;

        /// <summary>
        /// The header button that receives click events to toggle the accordion.
        /// </summary>
        private readonly GUIButton _headerButton;

        /// <summary>
        /// The chevron icon indicating the collapsed/expanded state.
        /// </summary>
        private readonly GUIImage? _icon;

        /// <summary>
        /// Optional callback invoked when the accordion is toggled.
        /// </summary>
        private readonly Action<bool>? _onToggle;

        /// <summary>
        /// The current collapsed state.
        /// </summary>
        private bool _collapsed;

        /// <summary>
        /// Gets the content builder for the accordion's collapsible area.
        /// </summary>
        public GUILayoutBuilder Content { get; }

        /// <summary>
        /// Gets whether the accordion is currently collapsed.
        /// </summary>
        public bool IsCollapsed => _collapsed;

        /// <summary>
        /// Creates a new accordion with a custom header component.
        /// </summary>
        /// <param name="header">The custom header component to use.</param>
        /// <param name="parent">The parent rectangle transform.</param>
        /// <param name="collapsed">Whether the accordion starts collapsed. Defaults to false.</param>
        /// <param name="onToggle">Optional callback invoked when the accordion is toggled.</param>
        /// <param name="iconAnchor">The anchor for the chevron icon. Defaults to CenterRight.</param>
        /// <remarks>
        /// The header component is made non-focusable and wrapped in a transparent button that handles clicks.
        /// A chevron icon is created from the "GUIDropDown.dropdownicon" style if available.
        /// The content area is a <see cref="GUILayoutBuilder"/> initially visible based on <paramref name="collapsed"/>.
        /// </remarks>
        public GUIAccordion(GUIComponent header, RectTransform parent, bool collapsed = false, Action<bool>? onToggle = null, Anchor iconAnchor = Anchor.CenterRight)
            : base(new RectTransform(new Vector2(1f, 0f), parent))
        {
            _collapsed = collapsed;
            _onToggle = onToggle;

            header.CanBeFocused = false;

            _headerButton = new GUIButton(new RectTransform(Vector2.One, header.RectTransform), style: null)
            {
                CanBeFocused = true,
                HoverCursor = CursorState.Hand,
                Color = Color.Transparent,
                HoverColor = Color.Transparent,
                PressedColor = Color.Transparent,
                SelectedColor = Color.Transparent,
                TextColor = Color.Transparent,
                HoverTextColor = Color.Transparent,
                SelectedTextColor = Color.Transparent,
                OnClicked = (_, _) => { Toggle(); return true; }
            };

            if (GUIStyle.GetComponentStyle("GUIDropDown")?.ChildStyles.TryGetValue("dropdownicon".ToIdentifier(), out GUIComponentStyle? style) ?? false)
            {
                _icon = new GUIImage(new RectTransform(new Vector2(0.6f, 0.6f), _headerButton.RectTransform, iconAnchor, scaleBasis: ScaleBasis.BothHeight) { AbsoluteOffset = new Point(5, 0) }, null, scaleToFit: true)
                {
                    CanBeFocused = false
                };
                _icon.ApplyStyle(style);
                _icon.Scale = 1.0f;
                _icon.Rotation = _collapsed ? MathHelper.ToRadians(-90f) : 0;
            }
            else
                Logger.LogDebugWarning("Style: 'GUIDropDown.dropdownicon' not encountered.");

            Content = new GUILayoutBuilder(new RectTransform(new Vector2(1f, 0f), RectTransform))
            {
                Visible = !_collapsed
            };

            Visible = !_collapsed;
        }

        /// <summary>
        /// Creates a new accordion with a text header.
        /// </summary>
        /// <param name="title">The header title text.</param>
        /// <param name="parent">The parent rectangle transform.</param>
        /// <param name="tooltip">Optional tooltip for the header button.</param>
        /// <param name="collapsed">Whether the accordion starts collapsed. Defaults to false.</param>
        /// <param name="onToggle">Optional callback invoked when the accordion is toggled.</param>
        /// <param name="iconAnchor">The anchor for the chevron icon. Defaults to CenterRight.</param>
        /// <remarks>
        /// Creates a text block header using <see cref="CreateHeader"/> and delegates to the component-based constructor.
        /// </remarks>
        public GUIAccordion(string title, RectTransform parent, string? tooltip = null, bool collapsed = false, Action<bool>? onToggle = null, Anchor iconAnchor = Anchor.CenterRight)
            : this(CreateHeader(parent, title), parent, collapsed, onToggle, iconAnchor)
        {
            if (tooltip != null) _headerButton.ToolTip = tooltip.Rich();
        }

        /// <summary>
        /// Creates a standard header text block for the accordion.
        /// </summary>
        /// <param name="parent">The parent rectangle transform.</param>
        /// <param name="title">The header title text.</param>
        /// <returns>A <see cref="GUITextBlock"/> with subheading font, white text, left alignment, and fixed height.</returns>
        /// <remarks>
        /// The text block has a left padding of 10 pixels and minimum/maximum height of <see cref="HeaderHeight"/> (28px).
        /// </remarks>
        private static GUITextBlock CreateHeader(RectTransform parent, string title)
        {
            var block = new GUITextBlock(new RectTransform(new Vector2(1f, 0f), parent), title, font: GUIStyle.SubHeadingFont, textColor: Color.White, textAlignment: Alignment.Left)
            {
                CanBeFocused = false
            };
            block.RectTransform.MinSize = new Point(0, HeaderHeight);
            block.RectTransform.MaxSize = new Point(int.MaxValue, HeaderHeight);
            block.Padding = new Vector4(10, 0, 0, 0);
            return block;
        }

        /// <summary>
        /// Toggles the accordion's collapsed state.
        /// </summary>
        /// <returns>Always returns <c>true</c>.</returns>
        /// <remarks>
        /// Calls <see cref="SetCollapsed"/> with the inverted current state.
        /// </remarks>
        public bool Toggle()
        {
            SetCollapsed(!_collapsed);
            return true;
        }

        /// <summary>
        /// Sets the accordion's collapsed state.
        /// </summary>
        /// <param name="collapsed">The new collapsed state.</param>
        /// <remarks>
        /// If the state is unchanged, returns immediately.
        /// Updates the chevron icon rotation (-90 degrees when collapsed, 0 when expanded).
        /// Shows/hides the content area and the accordion itself.
        /// Marks the accordion and its parent layout group (if any) as needing recalculation.
        /// Invokes the <see cref="_onToggle"/> callback if set.
        /// </remarks>
        public void SetCollapsed(bool collapsed)
        {
            if (_collapsed == collapsed) return;

            _collapsed = collapsed;
            if (_icon != null) _icon.Rotation = _collapsed ? MathHelper.ToRadians(-90f) : 0; // TODO: Agregar un nuevo Animacion para animar el cambio de rotacion.
            Content.Visible = !_collapsed;
            Visible = !_collapsed;
            NeedsToRecalculate = true;
            if (Parent is GUILayoutGroup layoutGroup) layoutGroup.NeedsToRecalculate = true;
            Logger.LogDebug($"GUIAccordion.SetCollapsed: collapsed={_collapsed}", level: LogLevel.Trace);
            _onToggle?.Invoke(_collapsed);
        }
    }
}
