// This file has a AI generated code, all content.
//   Are generated are free to use without licence 
//   requirements.
// All documentation was generated by AI. Revised, but may still contain errors.

using Barotrauma;
using Microsoft.Xna.Framework;

#pragma warning disable IDE0130

namespace SOS.GUI
{
    /// <summary>
    /// Extension methods for <see cref="GUIComponent"/> to start fluent animation sequences.
    /// </summary>
    /// <remarks>
    /// These methods create a <see cref="GUIAnimSequence"/> and immediately return it for chaining.
    /// The animation begins executing automatically on the next frame via <see cref="CoroutineManager"/>.
    /// </remarks>
    public static class GUIComponentExt
    {
        /// <summary>
        /// Creates a pause in the animation sequence.
        /// </summary>
        /// <param name="component">The component to animate.</param>
        /// <param name="duration">Duration in seconds to wait.</param>
        /// <returns>A <see cref="GUIAnimSequence"/> for chaining.</returns>
        public static GUIAnimSequence Wait(this GUIComponent component, float duration) => new GUIAnimSequence(component).Wait(duration);

        /// <summary>
        /// Animates the component's color to a target color over time.
        /// </summary>
        /// <param name="component">The component to animate.</param>
        /// <param name="targetColor">The target color to lerp to.</param>
        /// <param name="duration">Duration in seconds.</param>
        /// <param name="alsoChildren">If <c>true</c>, applies the animation to all children recursively.</param>
        /// <returns>A <see cref="GUIAnimSequence"/> for chaining.</returns>
        public static GUIAnimSequence ExLerpColor(this GUIComponent component, Color targetColor, float duration, bool alsoChildren = false)
            => new GUIAnimSequence(component).ExLerpColor(targetColor, duration, alsoChildren);

        /// <summary>
        /// Animates a <see cref="GUITextBlock"/>'s text color from a start color to a final color.
        /// </summary>
        /// <param name="component">The component to animate (must be a <see cref="GUITextBlock"/> for effect).</param>
        /// <param name="startColor">Optional start color. If <c>null</c>, uses current text color.</param>
        /// <param name="finalColor">The target text color.</param>
        /// <param name="duration">Duration in seconds.</param>
        /// <param name="alsoChildren">If <c>true</c>, applies to all <see cref="GUITextBlock"/> children.</param>
        /// <returns>A <see cref="GUIAnimSequence"/> for chaining.</returns>
        public static GUIAnimSequence ExLerpTextColor(this GUIComponent component, Color? startColor, Color finalColor, float duration, bool alsoChildren = false)
            => new GUIAnimSequence(component).ExLerpTextColor(startColor, finalColor, duration, alsoChildren);

        /// <summary>
        /// Shakes the component by randomly offsetting its screen position.
        /// </summary>
        /// <param name="component">The component to shake.</param>
        /// <param name="duration">Duration in seconds.</param>
        /// <param name="intensity">Maximum pixel offset. Defaults to 5.0.</param>
        /// <param name="alsoChildren">If <c>true</c>, applies to all children.</param>
        /// <returns>A <see cref="GUIAnimSequence"/> for chaining.</returns>
        public static GUIAnimSequence ExShake(this GUIComponent component, float duration, float intensity = 5.0f, bool alsoChildren = false)
            => new GUIAnimSequence(component).ExShake(duration, intensity, alsoChildren);

        /// <summary>
        /// Fades the component out to a target alpha factor.
        /// </summary>
        /// <param name="component">The component to fade.</param>
        /// <param name="duration">Duration in seconds.</param>
        /// <param name="targetFactor">Target alpha factor (0.0 = fully transparent, 1.0 = original). Defaults to 0.0.</param>
        /// <param name="alsoChildren">If <c>true</c>, applies to all children.</param>
        /// <returns>A <see cref="GUIAnimSequence"/> for chaining.</returns>
        public static GUIAnimSequence ExFadeOut(this GUIComponent component, float duration, float targetFactor = 0.0f, bool alsoChildren = false)
            => new GUIAnimSequence(component).ExFadeOut(duration, targetFactor, alsoChildren);

        /// <summary>
        /// Fades the component in from transparent to a target alpha factor.
        /// </summary>
        /// <param name="component">The component to fade.</param>
        /// <param name="duration">Duration in seconds.</param>
        /// <param name="targetFactor">Target alpha factor (1.0 = fully opaque). Defaults to 1.0.</param>
        /// <param name="alsoChildren">If <c>true</c>, applies to all children (except <see cref="GUIButton"/>).</param>
        /// <returns>A <see cref="GUIAnimSequence"/> for chaining.</returns>
        public static GUIAnimSequence ExFadeIn(this GUIComponent component, float duration, float? targetFactor = null, bool alsoChildren = false)
            => new GUIAnimSequence(component).ExFadeIn(duration, targetFactor, alsoChildren);

        /// <summary>
        /// Pulsates the component's scale between two vectors.
        /// </summary>
        /// <param name="component">The component to pulsate.</param>
        /// <param name="startScale">Starting scale vector.</param>
        /// <param name="endScale">Ending scale vector.</param>
        /// <param name="duration">Duration in seconds.</param>
        /// <param name="alsoChildren">If <c>true</c>, applies to all children.</param>
        /// <returns>A <see cref="GUIAnimSequence"/> for chaining.</returns>
        public static GUIAnimSequence ExPulsate(this GUIComponent component, Vector2 startScale, Vector2 endScale, float duration, bool alsoChildren = false)
            => new GUIAnimSequence(component).ExPulsate(startScale, endScale, duration, alsoChildren);

        /// <summary>
        /// Executes an action at the current point in the animation sequence.
        /// </summary>
        /// <param name="component">The component owning the sequence.</param>
        /// <param name="action">The action to execute.</param>
        /// <returns>A <see cref="GUIAnimSequence"/> for chaining.</returns>
        public static GUIAnimSequence Execute(this GUIComponent component, Action action)
            => new GUIAnimSequence(component).Execute(action);

        /// <summary>
        /// Applies a glitch effect (random color flashes and UV distortion).
        /// </summary>
        /// <param name="component">The component to glitch.</param>
        /// <param name="duration">Duration in seconds.</param>
        /// <param name="intensity">Effect intensity (0-1). Defaults to 1.0.</param>
        /// <param name="alsoChildren">If <c>true</c>, applies to all children.</param>
        /// <returns>A <see cref="GUIAnimSequence"/> for chaining.</returns>
        public static GUIAnimSequence ExGlitch(this GUIComponent component, float duration, float intensity = 1.0f, bool alsoChildren = false)
            => new GUIAnimSequence(component).ExGlitch(duration, intensity, alsoChildren);

        /// <summary>
        /// Flashes the component using Barotrauma's built-in flash effect.
        /// </summary>
        /// <param name="component">The component to flash.</param>
        /// <param name="color">Flash color. Defaults to white.</param>
        /// <param name="duration">Duration in seconds. Defaults to 1.5.</param>
        /// <param name="useRectangleFlash">Whether to use rectangular flash.</param>
        /// <param name="useCircularFlash">Whether to use circular flash.</param>
        /// <param name="flashRectInflate">Optional rectangle inflation for rectangular flash.</param>
        /// <param name="alsoChildren">If <c>true</c>, applies to all children.</param>
        /// <returns>A <see cref="GUIAnimSequence"/> for chaining.</returns>
        public static GUIAnimSequence ExFlash(this GUIComponent component, Color? color = null, float duration = 1.5f, bool useRectangleFlash = false, bool useCircularFlash = false, Vector2? flashRectInflate = null, bool alsoChildren = false)
            => new GUIAnimSequence(component).ExFlash(color, duration, useRectangleFlash, useCircularFlash, flashRectInflate, alsoChildren);

        /// <summary>
        /// Blinks the component by oscillating its alpha between min and max.
        /// </summary>
        /// <param name="component">The component to blink.</param>
        /// <param name="duration">Total duration in seconds.</param>
        /// <param name="minAlpha">Minimum alpha factor. Defaults to 0.0.</param>
        /// <param name="maxAlpha">Maximum alpha factor. Defaults to 1.0.</param>
        /// <param name="interval">Blink interval in seconds. Defaults to 0.5.</param>
        /// <param name="alsoChildren">If <c>true</c>, applies to all children.</param>
        /// <returns>A <see cref="GUIAnimSequence"/> for chaining.</returns>
        public static GUIAnimSequence ExBlink(this GUIComponent component, float duration, float minAlpha = 0.0f, float maxAlpha = 1.0f, float interval = 0.5f, bool alsoChildren = false)
            => new GUIAnimSequence(component).ExBlink(duration, minAlpha, maxAlpha, interval, alsoChildren);

        /// <summary>
        /// Logs a debug message with the component's type and text content at the current sequence point.
        /// </summary>
        /// <param name="component">The component.</param>
        /// <param name="color">The log message color.</param>
        /// <returns>A <see cref="GUIAnimSequence"/> for chaining.</returns>
        public static GUIAnimSequence LogMsg(this GUIComponent component, Color color)
            => new GUIAnimSequence(component).LogMsg(color);
    }

    /// <summary>
    /// Manages a chain of sequential and parallel animations for a <see cref="GUIComponent"/>.
    /// </summary>
    /// <remarks>
    /// Uses a step-based parallel execution model:
    /// <list type="bullet">
    /// <item>Each chained method adds an action to the current "step" (parallel block).</item>
    /// <item><see cref="WaitFinish"/> seals the current step; subsequent animations wait for it to complete.</item>
    /// <item><see cref="Wait(float)"/> inserts a timed delay as its own step.</item>
    /// <item>All coroutines are driven by <see cref="CoroutineManager"/>.</item>
    /// </list>
    /// <para>
    /// The sequence auto-starts on construction via <see cref="CoroutineManager.StartCoroutine"/>.
    /// Original colors/alphas are captured at construction for fade/restore operations.
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// component
    ///     .ExFadeIn(0.3f)
    ///     .Wait(0.5f)
    ///     .ExShake(0.2f, 8f)
    ///     .ExLerpColor(Color.Red, 0.3f)
    ///     .Execute(() => Logger.LogDebug("Done!"))
    ///     .ExFadeOut(0.2f);
    /// </code>
    /// </example>
    public class GUIAnimSequence
    {
        /// <summary>
        /// Gets the component being animated.
        /// </summary>
        public GUIComponent Component { get; private set; }

        private static readonly Dictionary<GUIComponent, Color> designColors = [];
        private static readonly Dictionary<GUIComponent, Color> designTextColors = [];
        private readonly float originalAlpha;
        private Color originalBaseColor;

        private readonly List<List<Func<IEnumerable<CoroutineStatus>>>> steps = [];
        private List<Func<IEnumerable<CoroutineStatus>>> currentStep = [];

        /// <summary>
        /// Creates a new animation sequence for the given component.
        /// </summary>
        /// <param name="component">The component to animate.</param>
        /// <remarks>
        /// Captures the component's original color and text color for fade/restore operations.
        /// Immediately starts the coroutine via <see cref="CoroutineManager.StartCoroutine"/>.
        /// </remarks>
        public GUIAnimSequence(GUIComponent component)
        {
            Component = component;
            if (!designColors.ContainsKey(component) || component.Color.A > 1)
            {
                designColors[component] = component.Color;
            }
            if (component is GUITextBlock tb)
            {
                if (!designTextColors.ContainsKey(tb) || tb.TextColor.A > 1)
                {
                    designTextColors[tb] = tb.TextColor;
                }
            }

            originalBaseColor = designColors.TryGetValue(component, out var c) ? c : component.Color;
            originalAlpha = originalBaseColor.A / 255f;
            if (originalAlpha < 0.001f) originalAlpha = 1.0f;

            CoroutineManager.StartCoroutine(ExecuteSequence());
        }

        // =========================================================================
        // MARK: - FLOW CONTROL
        // =========================================================================

        /// <summary>
        /// Adds an action to the current parallel step.
        /// </summary>
        /// <param name="action">A factory returning an enumerator of <see cref="CoroutineStatus"/>.</param>
        private void AddAction(Func<IEnumerable<CoroutineStatus>> action)
        {
            currentStep.Add(action);
            if (!steps.Contains(currentStep))
            {
                steps.Add(currentStep);
            }
        }

        /// <summary>
        /// Seals the current parallel block. Subsequent chained animations will execute after all actions in the current block complete.
        /// </summary>
        /// <returns>This sequence for chaining.</returns>
        public GUIAnimSequence WaitFinish()
        {
            if (currentStep.Count > 0)
            {
                currentStep = [];
            }
            return this;
        }

        /// <summary>
        /// Inserts a timed delay as a sequential step.
        /// </summary>
        /// <param name="duration">Delay in seconds.</param>
        /// <returns>This sequence for chaining.</returns>
        public GUIAnimSequence Wait(float duration)
        {
            WaitFinish();
            AddAction(() => GUIAnimSequence.DoWait(duration));
            WaitFinish();
            return this;
        }

        // =========================================================================
        // MARK: - CHAINABLE ANIMATIONS
        // =========================================================================

        /// <summary>
        /// Animates the component's color to a target color.
        /// </summary>
        /// <param name="targetColor">Target color.</param>
        /// <param name="duration">Duration in seconds.</param>
        /// <param name="alsoChildren">Apply to children recursively.</param>
        /// <returns>This sequence for chaining.</returns>
        public GUIAnimSequence ExLerpColor(Color targetColor, float duration, bool alsoChildren = false)
        {
            AddAction(() =>
            {
                if (alsoChildren) foreach (var child in Component.GetAllChildren()) child.ExLerpColor(targetColor, duration, false);
                return DoLerpColor(targetColor, duration);
            });
            return this;
        }

        /// <summary>
        /// Animates a <see cref="GUITextBlock"/>'s text color.
        /// </summary>
        /// <param name="startColor">Optional start color. If <c>null</c>, uses current text color.</param>
        /// <param name="finalColor">Target text color.</param>
        /// <param name="duration">Duration in seconds.</param>
        /// <param name="alsoChildren">Apply to child <see cref="GUITextBlock"/>s.</param>
        /// <returns>This sequence for chaining.</returns>
        public GUIAnimSequence ExLerpTextColor(Color? startColor, Color finalColor, float duration, bool alsoChildren = false)
        {
            AddAction(() =>
            {
                if (alsoChildren) foreach (var child in Component.GetAllChildren()) child.ExLerpTextColor(startColor, finalColor, duration, false);
                return DoLerpTextColor(startColor, finalColor, duration);
            });
            return this;
        }

        /// <summary>
        /// Shakes the component by randomly offsetting its screen position.
        /// </summary>
        /// <param name="duration">Duration in seconds.</param>
        /// <param name="intensity">Maximum pixel offset. Defaults to 5.0.</param>
        /// <param name="alsoChildren">Apply to children.</param>
        /// <returns>This sequence for chaining.</returns>
        public GUIAnimSequence ExShake(float duration, float intensity = 5.0f, bool alsoChildren = false)
        {
            AddAction(() =>
            {
                if (alsoChildren) foreach (var child in Component.GetAllChildren()) child.ExShake(duration, intensity, false);
                return DoShake(duration, intensity);
            });
            return this;
        }

        /// <summary>
        /// Fades the component in from transparent.
        /// </summary>
        /// <param name="duration">Duration in seconds.</param>
        /// <param name="targetFactor">Target alpha factor (default 1.0).</param>
        /// <param name="alsoChildren">Apply to children (skips <see cref="GUIButton"/>).</param>
        /// <returns>This sequence for chaining.</returns>
        /// <remarks>
        /// Immediately sets alpha to 0 for the component (and children if specified) to prevent flashing.
        /// Captures original colors of children before fading.
        /// </remarks>
        public GUIAnimSequence ExFadeIn(float duration, float? targetFactor = null, bool alsoChildren = false)
        {
            if (steps.Count == 0 || (steps.Count == 1 && currentStep.Count == 0))
            {
                GUIAnimSequence.ApplyAlphaInternal(Component, 0f);
                if (alsoChildren)
                {
                    foreach (var child in Component.GetAllChildren())
                    {
                        if (child is GUIButton) continue;
                        if (!designColors.ContainsKey(child) || child.Color.A > 0) designColors[child] = child.Color;
                        if (child is GUITextBlock tb && (!designTextColors.ContainsKey(tb) || tb.TextColor.A > 0)) designTextColors[tb] = tb.TextColor;
                        GUIAnimSequence.ApplyAlphaInternal(child, 0f);
                    }
                }
            }

            AddAction(() =>
            {
                if (alsoChildren)
                {
                    foreach (var child in Component.GetAllChildren())
                        if (child is GUIButton) continue;
                        else child.ExFadeIn(duration, targetFactor, false);
                }
                float finalFactor = targetFactor ?? 1.0f;
                return DoFadeInRecursive(duration, finalFactor);
            });
            return this;
        }

        /// <summary>
        /// Fades the component out to a target alpha factor.
        /// </summary>
        /// <param name="duration">Duration in seconds.</param>
        /// <param name="targetFactor">Target alpha factor (default 0.0).</param>
        /// <param name="alsoChildren">Apply to children.</param>
        /// <returns>This sequence for chaining.</returns>
        public GUIAnimSequence ExFadeOut(float duration, float targetFactor = 0.0f, bool alsoChildren = false)
        {
            AddAction(() =>
            {
                if (alsoChildren)
                {
                    foreach (var child in Component.GetAllChildren())
                        child.ExFadeOut(duration, targetFactor, false);
                }
                return DoFadeOutRecursive(duration, targetFactor);
            });
            return this;
        }

        private IEnumerable<CoroutineStatus> DoFadeInRecursive(float duration, float targetFactor)
        {
            float t = 0f;
            while (t < duration)
            {
                t += CoroutineManager.DeltaTime;
                GUIAnimSequence.ApplyAlphaInternal(Component, MathHelper.Lerp(0f, targetFactor, Math.Min(1.0f, t / duration)));
                yield return CoroutineStatus.Running;
            }
            GUIAnimSequence.ApplyAlphaInternal(Component, targetFactor);
            yield return CoroutineStatus.Success;
        }

        private IEnumerable<CoroutineStatus> DoFadeOutRecursive(float duration, float targetFactor)
        {
            float startFactor = Component.Color.A / (float)Math.Max((byte)1, originalBaseColor.A);
            float t = 0f;
            while (t < duration)
            {
                t += CoroutineManager.DeltaTime;
                GUIAnimSequence.ApplyAlphaInternal(Component, MathHelper.Lerp(startFactor, targetFactor, Math.Min(1.0f, t / duration)));
                yield return CoroutineStatus.Running;
            }
            GUIAnimSequence.ApplyAlphaInternal(Component, targetFactor);
            yield return CoroutineStatus.Success;
        }

        private static void ApplyAlphaInternal(GUIComponent comp, float factor)
        {
            if (designColors.TryGetValue(comp, out Color dc))
            {
                comp.Color = new Color(dc.R, dc.G, dc.B, (byte)(dc.A * factor));
            }
            else
            {
                Color c = comp.Color;
                comp.Color = new Color(c.R, c.G, c.B, (byte)(c.A * factor));
            }

            if (comp is GUITextBlock tb)
            {
                if (designTextColors.TryGetValue(tb, out Color dtc))
                {
                    tb.TextColor = new Color(dtc.R, dtc.G, dtc.B, (byte)(dtc.A * factor));
                }
            }
        }

        /// <summary>
        /// Pulsates the component's scale between two vectors.
        /// </summary>
        /// <param name="startScale">Starting scale.</param>
        /// <param name="endScale">Ending scale.</param>
        /// <param name="duration">Duration in seconds.</param>
        /// <param name="alsoChildren">Apply to children.</param>
        /// <returns>This sequence for chaining.</returns>
        public GUIAnimSequence ExPulsate(Vector2 startScale, Vector2 endScale, float duration, bool alsoChildren = false)
        {
            AddAction(() =>
            {
                if (alsoChildren) foreach (var child in Component.GetAllChildren()) child.ExPulsate(startScale, endScale, duration, false);
                return DoPulsate(startScale, endScale, duration);
            });
            return this;
        }

        /// <summary>
        /// Executes a C# action at this point in the sequence.
        /// </summary>
        /// <param name="action">The action to execute.</param>
        /// <returns>This sequence for chaining.</returns>
        public GUIAnimSequence Execute(Action action)
        {
            AddAction(() => GUIAnimSequence.DoExecute(action));
            return this;
        }

        /// <summary>
        /// Applies a glitch effect (random color flashes and UV distortion).
        /// </summary>
        /// <param name="duration">Duration in seconds.</param>
        /// <param name="intensity">Effect intensity (0-1). Defaults to 1.0.</param>
        /// <param name="alsoChildren">Apply to children.</param>
        /// <returns>This sequence for chaining.</returns>
        public GUIAnimSequence ExGlitch(float duration, float intensity = 1.0f, bool alsoChildren = false)
        {
            AddAction(() =>
            {
                if (alsoChildren) foreach (var child in Component.GetAllChildren()) child.ExGlitch(duration, intensity, false);
                return DoGlitch(duration, intensity);
            });
            return this;
        }

        /// <summary>
        /// Flashes the component using Barotrauma's built-in flash effect.
        /// </summary>
        /// <param name="color">Flash color (default white).</param>
        /// <param name="duration">Duration in seconds (default 1.5).</param>
        /// <param name="useRectangleFlash">Use rectangular flash.</param>
        /// <param name="useCircularFlash">Use circular flash.</param>
        /// <param name="flashRectInflate">Optional rectangle inflation for rectangular flash.</param>
        /// <param name="alsoChildren">Apply to children.</param>
        /// <returns>This sequence for chaining.</returns>
        public GUIAnimSequence ExFlash(Color? color = null, float duration = 1.5f, bool useRectangleFlash = false, bool useCircularFlash = false, Vector2? flashRectInflate = null, bool alsoChildren = false)
        {
            AddAction(() =>
            {
                if (alsoChildren) foreach (var child in Component.GetAllChildren()) child.ExFlash(color, duration, useRectangleFlash, useCircularFlash, flashRectInflate, true);
                return DoFlash(color, duration, useRectangleFlash, useCircularFlash, flashRectInflate);
            });
            return this;
        }

        /// <summary>
        /// Blinks the component by oscillating its alpha.
        /// </summary>
        /// <param name="duration">Total duration in seconds.</param>
        /// <param name="minAlpha">Minimum alpha factor (default 0.0).</param>
        /// <param name="maxAlpha">Maximum alpha factor (default 1.0).</param>
        /// <param name="interval">Blink interval in seconds (default 0.5).</param>
        /// <param name="alsoChildren">Apply to children.</param>
        /// <returns>This sequence for chaining.</returns>
        public GUIAnimSequence ExBlink(float duration, float minAlpha = 0.0f, float maxAlpha = 1.0f, float interval = 0.5f, bool alsoChildren = false)
        {
            AddAction(() =>
            {
                if (alsoChildren) foreach (var child in Component.GetAllChildren()) child.ExBlink(duration, minAlpha, maxAlpha, interval, false);
                return DoBlink(duration, minAlpha, maxAlpha, interval);
            });
            return this;
        }

        /// <summary>
        /// Logs a debug message at this sequence point.
        /// </summary>
        /// <param name="color">Log message color.</param>
        /// <returns>This sequence for chaining.</returns>
        public GUIAnimSequence LogMsg(Color color)
        {
            AddAction(() => DoLogMsg(color));
            return this;
        }

        // =========================================================================
        // MARK: - INTERNAL COROUTINES
        // =========================================================================

        private static IEnumerable<CoroutineStatus> DoWait(float duration)
        {
            float t = 0;
            while (t < duration)
            {
                t += CoroutineManager.DeltaTime;
                yield return CoroutineStatus.Running;
            }
            yield return CoroutineStatus.Success;
        }

        private IEnumerable<CoroutineStatus> DoLerpColor(Color targetColor, float duration)
        {
            Color startColor = Component.Color;
            float t = 0f;
            while (t < duration)
            {
                t += CoroutineManager.DeltaTime;
                float progress = Math.Min(1.0f, t / duration);
                GUIAnimSequence.ApplyColorRGB(Component, Color.Lerp(startColor, targetColor, progress));
                yield return CoroutineStatus.Running;
            }
            GUIAnimSequence.ApplyColorRGB(Component, targetColor);
            yield return CoroutineStatus.Success;
        }

        private IEnumerable<CoroutineStatus> DoLerpTextColor(Color? startColor, Color finalColor, float duration)
        {
            if (Component is not GUITextBlock textBlock) { yield return CoroutineStatus.Success; yield break; }
            Color initial = startColor ?? textBlock.TextColor;
            float t = 0f;
            while (t < duration)
            {
                t += CoroutineManager.DeltaTime;
                textBlock.TextColor = Color.Lerp(initial, finalColor, Math.Min(1.0f, t / duration));
                yield return CoroutineStatus.Running;
            }
            textBlock.TextColor = finalColor;
            yield return CoroutineStatus.Success;
        }

        private IEnumerable<CoroutineStatus> DoShake(float duration, float intensity)
        {
            float t = 0f;
            Random rand = new();
            Point originalOffset = Component.RectTransform.ScreenSpaceOffset;
            while (t < duration)
            {
                t += CoroutineManager.DeltaTime;
                float currentIntensity = MathHelper.Lerp(intensity, 0, t / duration);
                int offsetX = rand.Next(-(int)currentIntensity, (int)currentIntensity);
                int offsetY = rand.Next(-(int)currentIntensity, (int)currentIntensity);
                Component.RectTransform.ScreenSpaceOffset = new Point(originalOffset.X + offsetX, originalOffset.Y + offsetY);
                yield return CoroutineStatus.Running;
            }
            Component.RectTransform.ScreenSpaceOffset = originalOffset;
            Component.ForceLayoutRecalculation();
            yield return CoroutineStatus.Success;
        }

        private IEnumerable<CoroutineStatus> DoFadeIn(float duration, float targetAlpha)
        {
            float startAlpha = Component.Color.A / 255f;
            float t = 0f;
            while (t < duration)
            {
                t += CoroutineManager.DeltaTime;
                GUIAnimSequence.ApplyAlpha(Component, MathHelper.Lerp(startAlpha, targetAlpha, Math.Min(1.0f, t / duration)));
                yield return CoroutineStatus.Running;
            }
            GUIAnimSequence.ApplyAlpha(Component, targetAlpha);
            yield return CoroutineStatus.Success;
        }

        private IEnumerable<CoroutineStatus> DoFadeOut(float duration, float targetAlpha)
        {
            float startAlpha = Component.Color.A / 255f;
            float t = 0f;
            while (t < duration)
            {
                t += CoroutineManager.DeltaTime;
                float currentAlpha = MathHelper.Lerp(startAlpha, targetAlpha, Math.Min(1.0f, t / duration));
                GUIAnimSequence.ApplyAlpha(Component, currentAlpha);
                yield return CoroutineStatus.Running;
            }
            GUIAnimSequence.ApplyAlpha(Component, targetAlpha);
            yield return CoroutineStatus.Success;
        }

        private IEnumerable<CoroutineStatus> DoPulsate(Vector2 startScale, Vector2 endScale, float duration)
        {
            float t = 0f;
            while (t < duration)
            {
                t += CoroutineManager.DeltaTime;
                Component.RectTransform.Scale = Vector2.Lerp(startScale, endScale, t / duration);
                yield return CoroutineStatus.Running;
            }
            Component.RectTransform.Scale = endScale;
            yield return CoroutineStatus.Success;
        }

        private IEnumerable<CoroutineStatus> DoGlitch(float duration, float intensity)
        {
            float t = 0f;
            Random rand = new();
            Color origColor = Component.Color;
            Vector2 origUV = Component.UVOffset;

            while (t < duration)
            {
                t += CoroutineManager.DeltaTime;
                float currentIntensity = Math.Max(0, intensity * (1.0f - (t / duration)));
                if (rand.NextDouble() < 0.1 * currentIntensity)
                    Component.Color = rand.NextDouble() > 0.5 ? Color.Cyan : Color.Magenta;
                else
                    Component.Color = origColor;

                Component.UVOffset = new Vector2(
                    (float)(rand.NextDouble() * 2.0 - 1.0) * 100f * currentIntensity,
                    (float)(rand.NextDouble() * 2.0 - 1.0) * 10f * currentIntensity
                );
                yield return CoroutineStatus.Running;
            }
            Component.Color = origColor;
            Component.UVOffset = origUV;
            yield return CoroutineStatus.Success;
        }

        private IEnumerable<CoroutineStatus> DoFlash(Color? color, float duration, bool useRectangleFlash, bool useCircularFlash, Vector2? flashRectInflate)
        {
            Component.Flash(color, duration, useRectangleFlash, useCircularFlash, flashRectInflate);
            float t = 0f;
            while (t < duration) { t += CoroutineManager.DeltaTime; yield return CoroutineStatus.Running; }
            yield return CoroutineStatus.Success;
        }

        private IEnumerable<CoroutineStatus> DoBlink(float duration, float minFactor, float maxFactor, float interval)
        {
            float t = 0f;
            while (t < duration)
            {
                t += CoroutineManager.DeltaTime;
                float phase = (t / interval) * MathHelper.TwoPi;
                float alphaScale = (float)(Math.Sin(phase - MathHelper.PiOver2) + 1.0) / 2.0f;
                float currentFactor = MathHelper.Lerp(minFactor, maxFactor, alphaScale);
                GUIAnimSequence.ApplyAlphaInternal(Component, currentFactor);
                yield return CoroutineStatus.Running;
            }
            GUIAnimSequence.ApplyAlphaInternal(Component, 1.0f);
            yield return CoroutineStatus.Success;
        }

        private IEnumerable<CoroutineStatus> DoLogMsg(Color? color)
        {
            Logger.LogDebug($"Anim Sequence Progress on {Component.GetType().Name} ({(Component as GUITextBlock)?.Text ?? "NoText"})", color);
            yield return CoroutineStatus.Success;
        }

        private static IEnumerable<CoroutineStatus> DoExecute(Action action)
        {
            try { action?.Invoke(); }
            catch (Exception e) { DebugConsole.ThrowError("Error en ejecución de secuencia GUI", e); }
            yield return CoroutineStatus.Success;
        }

        private static void ApplyAlpha(GUIComponent comp, float alpha)
        {
            GUIAnimSequence.ApplyAlphaInternal(comp, alpha);
        }

        private static void ApplyColorRGB(GUIComponent comp, Color rgb)
        {
            comp.Color = new Color(rgb.R, rgb.G, rgb.B, comp.Color.A);
        }

        // =========================================================================
        // MARK: - MASTER EXECUTION ENGINE
        // =========================================================================

        private IEnumerable<CoroutineStatus> ExecuteSequence()
        {
            yield return CoroutineStatus.Running;

            int stepIndex = 0;
            while (stepIndex < steps.Count)
            {
                var step = steps[stepIndex];

                var activeCoroutines = new List<IEnumerator<CoroutineStatus>>();
                foreach (var action in step)
                {
                    activeCoroutines.Add(action().GetEnumerator());
                }

                while (activeCoroutines.Count > 0)
                {
                    for (int i = activeCoroutines.Count - 1; i >= 0; i--)
                    {
                        if (!activeCoroutines[i].MoveNext() || activeCoroutines[i].Current == CoroutineStatus.Success)
                        {
                            activeCoroutines.RemoveAt(i);
                        }
                    }

                    if (activeCoroutines.Count > 0)
                    {
                        yield return CoroutineStatus.Running;
                    }
                }

                stepIndex++;
            }

            yield return CoroutineStatus.Success;
        }

        /// <summary>
        /// Clears all cached design colors. Call when components are destroyed to prevent memory leaks.
        /// </summary>
        public static void ClearAll()
        {
            designColors.Clear();
            designTextColors.Clear();
        }
    }
}