// This file has been modified from game basecode.
// Original code extracted from [here](https://github.com/FakeFishGames/Barotrauma/blob/c8657caefa5c6928013a5152ac0ad301d99b405c/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIDropDown.cs)
// All rights from @FakeFishGames.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0079
#pragma warning disable IDE0290

using Barotrauma;
using EventInput;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;

using BGUI = Barotrauma.GUI;

namespace SOS.GUI
{
    /// <summary>
    /// A custom dropdown component with support for single/multiple selection, keyboard navigation, and custom styling.
    /// </summary>
    /// <remarks>
    /// Modified from the Barotrauma base GUIDropDown to add multi-select support, improved keyboard handling,
    /// and custom list box positioning. Supports both single and multiple selection modes with tick boxes.
    /// </remarks>
    public class GUIDropDown2 : GUIComponent, IKeyboardSubscriber
    {
        /// <summary>
        /// Delegate for handling item selection events.
        /// </summary>
        /// <param name="selected">The GUI component that was selected.</param>
        /// <param name="obj">The user data associated with the selected item.</param>
        /// <returns><c>true</c> if the selection was handled; <c>false</c> to cancel.</returns>
        public delegate bool OnSelectedHandler(GUIComponent? selected, object? obj);

        /// <summary>
        /// Invoked when an item is selected (before the dropdown closes).
        /// </summary>
        public OnSelectedHandler? OnSelected;

        /// <summary>
        /// Invoked after an item is selected (after the dropdown closes).
        /// </summary>
        public OnSelectedHandler? AfterSelected;

        /// <summary>
        /// Invoked when the dropdown is opened.
        /// </summary>
        public OnDroppedHandler? OnDropped;

        /// <summary>
        /// Delegate for handling dropdown open events.
        /// </summary>
        /// <param name="dropDown">The dropdown that was opened.</param>
        /// <param name="obj">The dropdown's user data.</param>
        /// <returns><c>true</c> if the event was handled.</returns>
        public delegate bool OnDroppedHandler(GUIDropDown2 dropDown, object? obj);

        private readonly GUIButton button;
        private readonly GUIImage? icon;
        private readonly GUIListBox listBox;

        private RectTransform? currentHighestParent;
        private List<RectTransform> parentHierarchy = [];

        private readonly bool selectMultiple;

        private bool dropped;
        public bool Dropped
        {
            get => dropped;
            set
            {
                if (dropped == value) return;
                dropped = value;
                if (icon != null)
                {
                    icon.SpriteEffects = dropped
                        ? SpriteEffects.FlipVertically
                        : SpriteEffects.None;
                }
            }
        }

        /// <summary>
        /// Gets the user data of the currently selected item.
        /// </summary>
        /// <returns>The selected item's user data, or null if no item is selected.</returns>
        public object? SelectedItemData
        {
            get
            {
                if (listBox.SelectedComponent == null) return null;
                return listBox.SelectedComponent.UserData;
            }
        }

        /// <summary>
        /// Gets or sets whether the dropdown is enabled.
        /// </summary>
        /// <remarks>
        /// Controls the enabled state of the internal list box.
        /// </remarks>
        public override bool Enabled
        {
            get { return listBox.Enabled; }
            set { listBox.Enabled = value; }
        }

        /// <summary>
        /// Gets or sets whether the dropdown button is enabled.
        /// </summary>
        /// <remarks>
        /// Controls the enabled state of the button and its icon independently of the list box.
        /// </remarks>
        public bool ButtonEnabled
        {
            get { return button.Enabled; }
            set
            {
                button.Enabled = value;
                if (icon != null) { icon.Enabled = value; }
            }
        }

        /// <summary>
        /// Gets the currently selected GUI component in the list box.
        /// </summary>
        /// <returns>The selected component, or null if none.</returns>
        public GUIComponent? SelectedComponent => listBox.SelectedComponent;

        public override bool Selected
        {
            get => Dropped;
            set => Dropped = value;
        }

        public GUIListBox ListBox => listBox;

        /// <summary>
        /// Gets the user data of the currently selected item (alias for <see cref="SelectedItemData"/>).
        /// </summary>
        /// <returns>The selected item's user data, or null if no item is selected.</returns>
        public object? SelectedData => listBox.SelectedComponent?.UserData;

        /// <summary>
        /// Gets the index of the currently selected item.
        /// </summary>
        /// <returns>The index of the selected item, or -1 if no item is selected.</returns>
        public int SelectedIndex
        {
            get
            {
                if (listBox.SelectedComponent == null) return -1;
                return listBox.Content.GetChildIndex(listBox.SelectedComponent);
            }
        }

        public void ReceiveTextInput(char inputChar) => BGUI.KeyboardDispatcher.Subscriber = null;
        public void ReceiveTextInput(string text) { }
        public void ReceiveCommandInput(char command) { }
        public void ReceiveEditingInput(string text, int start, int length) { }

        public void ReceiveSpecialInput(Keys key)
        {
            switch (key)
            {
                case Keys.Up:
                case Keys.Down:
                    listBox.ReceiveSpecialInput(key);
                    BGUI.KeyboardDispatcher.Subscriber = this;
                    break;
                default:
                    BGUI.KeyboardDispatcher.Subscriber = null;
                    break;
            }
        }

        private readonly List<object> selectedDataMultiple = [];
        public IEnumerable<object> SelectedDataMultiple => selectedDataMultiple;

        private readonly List<int> selectedIndexMultiple = [];
        public IEnumerable<int> SelectedIndexMultiple => selectedIndexMultiple;

        public bool MustSelectAtLeastOne;

        /// <summary>
        /// Gets or sets the tooltip for the dropdown, button, and list box.
        /// </summary>
        /// <remarks>
        /// Setting this property updates the tooltip on all three internal components.
        /// </remarks>
        public override RichString ToolTip
        {
            get => base.ToolTip;
            set
            {
                base.ToolTip = value;
                button.ToolTip = value;
                listBox.ToolTip = value;
            }
        }

        /// <summary>
        /// Creates a new dropdown component.
        /// </summary>
        /// <param name="rectT">The rectangle transform for positioning and sizing.</param>
        /// <param name="elementCount">The number of visible elements in the dropdown list. Defaults to 4.</param>
        /// <param name="style">The GUI style name. Defaults to empty string.</param>
        /// <param name="selectMultiple">Whether to enable multiple selection mode with tick boxes. Defaults to false.</param>
        /// <param name="dropAbove">Whether the dropdown list should open above the button. Defaults to false.</param>
        /// <param name="listBoxWidth">Optional fixed width for the dropdown list. Defaults to parent width or button width.</param>
        /// <param name="expandToRight">Whether the list should expand to the right. Defaults to auto-detect based on anchor.</param>
        /// <remarks>
        /// Creates a button with "GUIDropDown" style and a list box positioned relative to the button.
        /// In single-select mode, clicking an item selects it and closes the dropdown.
        /// In multi-select mode, tick boxes are used and <see cref="MustSelectAtLeastOne"/> can enforce at least one selection.
        /// The list box is attached to the highest parent in the GUI hierarchy for proper rendering.
        /// </remarks>
        public GUIDropDown2(RectTransform rectT, int elementCount = 4, string style = "", bool selectMultiple = false, bool dropAbove = false, int? listBoxWidth = null, bool? expandToRight = null) : base(style, rectT)
        {
            HoverCursor = CursorState.Hand;
            CanBeFocused = true;

            this.selectMultiple = selectMultiple;

            button = new GUIButton(new RectTransform(Vector2.One, rectT), "", Alignment.Center, style: "GUIDropDown")
            {
                OnClicked = OnClicked
            };
            GUIStyle.Apply(button, "", this);

            bool isRight;
            if (expandToRight.HasValue)
            {
                isRight = expandToRight.Value;
            }
            else
            {
                isRight = rectT.Anchor != Anchor.TopRight && rectT.Anchor != Anchor.CenterRight && rectT.Anchor != Anchor.BottomRight;
            }

            Anchor listAnchor;
            Pivot listPivot;

            if (isRight)
            {
                listAnchor = dropAbove ? Anchor.TopLeft : Anchor.BottomLeft;
                listPivot = dropAbove ? Pivot.BottomLeft : Pivot.TopLeft;
            }
            else
            {
                listAnchor = dropAbove ? Anchor.TopRight : Anchor.BottomRight;
                listPivot = dropAbove ? Pivot.BottomRight : Pivot.TopRight;
            }

            int finalWidth = listBoxWidth ?? (rectT.Parent != null ? rectT.Parent.Rect.Width : rectT.Rect.Width);
            int finalHeight = rectT.Rect.Height * MathHelper.Clamp(elementCount, 2, 10);

            listBox = new GUIListBox(new RectTransform(new Point(finalWidth, finalHeight), rectT, listAnchor, listPivot)
            { IsFixedSize = true }, style: null)
            {
                Enabled = !selectMultiple,
                PlaySoundOnSelect = true,
                Padding = new Vector4(2, 2, 2, 2)
            };

            if (!selectMultiple)
            {
                listBox.AfterSelected = (component, obj) =>
                {
                    SelectItem(component, obj);
                    AfterSelected?.Invoke(component, obj);
                    return true;
                };
            }
            GUIStyle.Apply(listBox, "GUIListBox", this);
            GUIStyle.Apply(listBox.ContentBackground, "GUIListBox", this);

            if (button.Style.ChildStyles.ContainsKey("dropdownicon".ToIdentifier()))
            {
                icon = new GUIImage(new RectTransform(new Vector2(0.8f, 0.8f), button.RectTransform, Anchor.Center, Pivot.Center, scaleBasis: ScaleBasis.BothHeight), null, scaleToFit: true);
                icon.ApplyStyle(button.Style.ChildStyles["dropdownicon".ToIdentifier()]);
            }

            currentHighestParent = FindHighestParent();
            currentHighestParent.GUIComponent.OnAddedToGUIUpdateList += AddListBoxToGUIUpdateList;
            rectT.ParentChanged += _ => RefreshListBoxParent();
        }

        private RectTransform FindHighestParent()
        {
            parentHierarchy.Clear();
            parentHierarchy = [RectTransform.Parent];
            RectTransform parent = parentHierarchy.Last();
            while (parent?.Parent != null)
            {
                parentHierarchy.Add(parent.Parent);
                parent = parent.Parent;
            }

            for (int i = parentHierarchy.Count - 1; i > 0; i--)
            {
                if (parentHierarchy[i] is GUICanvas ||
                    parentHierarchy[i].GUIComponent == null ||
                    parentHierarchy[i].GUIComponent.Style == null ||
                    parentHierarchy[i].GUIComponent == Screen.Selected?.Frame)
                {
                    parentHierarchy.RemoveAt(i);
                }
                else { break; }
            }
            return parentHierarchy.Count > 0 ? parentHierarchy.Last() : RectTransform;
        }

        /// <summary>
        /// Adds an item to the dropdown list.
        /// </summary>
        /// <param name="text">The display text for the item.</param>
        /// <param name="userData">Arbitrary user data associated with the item.</param>
        /// <param name="toolTip">Optional tooltip for the item.</param>
        /// <param name="color">Optional background color for the item.</param>
        /// <param name="textColor">Optional text color for the item.</param>
        /// <returns>The created GUI component (frame with tick box for multi-select, text block for single-select).</returns>
        /// <remarks>
        /// In multi-select mode (<see cref="selectMultiple"/> = true), creates a frame with a tick box.
        /// In single-select mode, creates a styled text block.
        /// The tick box enforces <see cref="MustSelectAtLeastOne"/> if set.
        /// </remarks>
        public GUIComponent AddItem(LocalizedString text, object userData, LocalizedString toolTip, Color? color, Color? textColor)
        {
            toolTip ??= "";
            int itemHeight = Math.Max(button.Rect.Height, 24);

            if (selectMultiple)
            {
                var frame = new GUIFrame(new RectTransform(new Point(listBox.Content.Rect.Width, itemHeight), listBox.Content.RectTransform) { IsFixedSize = false }, style: "ListBoxElement", color: color)
                {
                    UserData = userData,
                    ToolTip = toolTip
                };
                var tickBox = new GUITickBox(new RectTransform(new Vector2(1.0f, 0.8f), frame.RectTransform, anchor: Anchor.CenterLeft) { MaxSize = new Point(int.MaxValue, (int)(itemHeight * 0.8f)) }, text)
                {
                    UserData = userData,
                    ToolTip = toolTip,
                    OnSelected = tb =>
                    {
                        if (MustSelectAtLeastOne && selectedDataMultiple.Count <= 1 && !tb.Selected)
                        {
                            tb.Selected = true;
                            return false;
                        }

                        if (OnSelected != null && !OnSelected.Invoke(tb.Parent, tb.Parent.UserData)) { return false; }

                        selectedDataMultiple.Clear();
                        selectedIndexMultiple.Clear();
                        int i = 0;
                        foreach (GUIComponent child in ListBox.Content.Children)
                        {
                            var tickBoxItem = child.GetChild<GUITickBox>();
                            if (tickBoxItem is { Selected: true })
                            {
                                selectedDataMultiple.Add(child.UserData);
                                selectedIndexMultiple.Add(i);
                            }
                            i++;
                        }
                        AfterSelected?.Invoke(tb.Parent, SelectedData);
                        return true;
                    }
                };
                return frame;
            }
            else
            {
                return new GUITextBlock(new RectTransform(new Point(listBox.Content.Rect.Width, itemHeight), listBox.Content.RectTransform) { IsFixedSize = false }, text, style: "ListBoxElement", color: color, textColor: textColor)
                {
                    UserData = userData,
                    ToolTip = toolTip
                };
            }
        }

        /// <summary>
        /// Clears all items from the dropdown list.
        /// </summary>
        /// <remarks>
        /// Delegates to the internal list box's <see cref="GUIListBox.ClearChildren"/> method.
        /// </remarks>
        public override void ClearChildren() => listBox.ClearChildren();

        /// <summary>
        /// Gets the child components in the dropdown list.
        /// </summary>
        /// <returns>An enumerable of the list box's child components.</returns>
        public IEnumerable<GUIComponent> GetChildren() => listBox.Content.Children;

        /// <summary>
        /// Selects an item in the dropdown.
        /// </summary>
        /// <param name="component">The GUI component to select.</param>
        /// <param name="obj">The user data associated with the item.</param>
        /// <returns><c>true</c> if the item was selected.</returns>
        /// <remarks>
        /// In multi-select mode, updates the tick box states. In single-select mode, closes the dropdown.
        /// Invokes <see cref="OnSelected"/> and <see cref="AfterSelected"/> events.
        /// </remarks>
        private bool SelectItem(GUIComponent? component, object? obj)
        {
            if (selectMultiple)
            {
                foreach (GUIComponent child in ListBox.Content.Children)
                {
                    var tickBox = child.GetChild<GUITickBox>();
                    if (Equals(obj, child.UserData) && tickBox != null) { tickBox.Selected = true; }
                }
            }
            OnSelected?.Invoke(component, obj);
            Dropped = false;
            return true;
        }

        /// <summary>
        /// Selects an item by its user data.
        /// </summary>
        /// <param name="userData">The user data of the item to select.</param>
        /// <remarks>
        /// In multi-select mode, finds the item by user data and calls <see cref="SelectItem"/>.
        /// In single-select mode, uses the list box's built-in selection.
        /// Invokes <see cref="AfterSelected"/> after selection.
        /// </remarks>
        public void SelectItem(object userData)
        {
            if (selectMultiple)
            {
                SelectItem(listBox.Content.FindChild(userData), userData);
            }
            else
            {
                listBox.Select(userData);
            }
            AfterSelected?.Invoke(SelectedComponent, SelectedData);
        }

        /// <summary>
        /// Selects an item by its index.
        /// </summary>
        /// <param name="index">The index of the item to select.</param>
        /// <remarks>
        /// In multi-select mode, finds the child at the index and calls <see cref="SelectItem"/>.
        /// In single-select mode, uses the list box's built-in selection by index.
        /// Invokes <see cref="AfterSelected"/> after selection.
        /// </remarks>
        public void Select(int index)
        {
            if (selectMultiple)
            {
                var child = listBox.Content.GetChild(index);
                if (child != null) { SelectItem(child, child.UserData); }
            }
            else
            {
                listBox.Select(index);
            }
            AfterSelected?.Invoke(this, SelectedData);
        }

        private bool wasOpened;

        /// <summary>
        /// Handles button click to toggle the dropdown open/closed state.
        /// </summary>
        /// <param name="component">The clicked component (the button).</param>
        /// <param name="obj">The user data (unused).</param>
        /// <returns><c>true</c> if the click was handled.</returns>
        /// <remarks>
        /// Toggles the <see cref="Dropped"/> state. When opening, invokes <see cref="OnDropped"/>,
        /// updates list box dimensions, and sets keyboard focus. When closing, releases keyboard focus.
        /// </remarks>
        private bool OnClicked(GUIComponent component, object obj)
        {
            if (wasOpened) return false;
            wasOpened = true;
            Dropped = !Dropped;
            if (Dropped && Enabled)
            {
                OnDropped?.Invoke(this, UserData);
                listBox.UpdateDimensions();
                BGUI.KeyboardDispatcher.Subscriber = this;
            }
            else if (BGUI.KeyboardDispatcher.Subscriber == this)
            {
                BGUI.KeyboardDispatcher.Subscriber = null;
            }
            return true;
        }

        /// <summary>
        /// Refreshes the list box's parent hierarchy when the dropdown's parent changes.
        /// </summary>
        /// <remarks>
        /// Unsubscribes from the previous highest parent's <c>OnAddedToGUIUpdateList</c> event,
        /// finds the new highest parent, and subscribes to its event.
        /// If the dropdown has no parent, disposes the component.
        /// </remarks>
        public void RefreshListBoxParent()
        {
            if (RectTransform.Parent == null) { Dispose(); return; }
            if (currentHighestParent != null && currentHighestParent.GUIComponent != null)
            {
                currentHighestParent.GUIComponent.OnAddedToGUIUpdateList -= AddListBoxToGUIUpdateList;
            }

            currentHighestParent = FindHighestParent();
            if (currentHighestParent?.GUIComponent != null)
            {
                currentHighestParent.GUIComponent.OnAddedToGUIUpdateList += AddListBoxToGUIUpdateList;
            }
        }

        /// <summary>
        /// Adds the dropdown list box to the GUI update list when the parent is added to the GUI.
        /// </summary>
        /// <param name="parent">The parent GUI component that was added to the update list.</param>
        /// <remarks>
        /// Verifies the parent hierarchy is intact, then adds the list box to the GUI update list
        /// if the dropdown is currently dropped. This ensures the dropdown renders correctly
        /// even when nested in complex GUI hierarchies.
        /// </remarks>
        private void AddListBoxToGUIUpdateList(GUIComponent parent)
        {
            for (int i = 1; i < parentHierarchy.Count; i++)
            {
                if (parentHierarchy[i] != null && parentHierarchy[i - 1] != null && parentHierarchy[i].IsParentOf(parentHierarchy[i - 1], recursive: false))
                {
                    continue;
                }
                parent.OnAddedToGUIUpdateList -= AddListBoxToGUIUpdateList;
                return;
            }

            if (Dropped) { listBox.AddToGUIUpdateList(false, 1); }
        }

        /// <summary>
        /// Manually draws the dropdown button (and children if specified).
        /// </summary>
        /// <param name="spriteBatch">The sprite batch to draw with.</param>
        /// <param name="alsoChildren">Whether to also draw children. Defaults to false.</param>
        /// <param name="recursive">Whether to draw recursively. Defaults to true.</param>
        /// <remarks>
        /// If not visible, returns immediately. Sets <see cref="GUIComponent.AutoDraw"/> to false,
        /// draws the base component, then manually draws the button if <paramref name="alsoChildren"/> is true.
        /// </remarks>
        public override void DrawManually(SpriteBatch spriteBatch, bool alsoChildren = false, bool recursive = true)
        {
            if (!Visible) return;
            AutoDraw = false;
            Draw(spriteBatch);
            if (alsoChildren) { button.DrawManually(spriteBatch, alsoChildren, recursive); }
        }

        /// <summary>
        /// Adds the dropdown and its button to the GUI update list.
        /// </summary>
        /// <param name="ignoreChildren">Whether to ignore children. Defaults to false.</param>
        /// <param name="order">The update order. Defaults to 0.</param>
        /// <remarks>
        /// Adds the base component with children ignored, then adds the button without ignoring children.
        /// </remarks>
        public override void AddToGUIUpdateList(bool ignoreChildren = false, int order = 0)
        {
            base.AddToGUIUpdateList(true, order);
            if (!ignoreChildren) { button.AddToGUIUpdateList(false, order); }
        }

        /// <summary>
        /// Updates the dropdown, handling mouse clicks to close the dropdown when clicking outside.
        /// </summary>
        /// <param name="deltaTime">Time elapsed since the last update in seconds.</param>
        /// <remarks>
        /// Resets the <c>wasOpened</c> flag to prevent immediate re-toggling.
        /// If the dropdown is open and the primary mouse button is clicked outside both the list box
        /// and the button, closes the dropdown and releases keyboard focus.
        /// </remarks>
        public override void Update(float deltaTime)
        {
            if (!Visible || listBox == null || button == null) return;
            wasOpened = false;
            base.Update(deltaTime);
            if (Dropped && PlayerInput.PrimaryMouseButtonClicked())
            {
                Rectangle listBoxRect = listBox.Rect;
                if (!listBoxRect.Contains(PlayerInput.MousePosition) && !button.Rect.Contains(PlayerInput.MousePosition))
                {
                    Dropped = false;
                    if (BGUI.KeyboardDispatcher.Subscriber == this) { BGUI.KeyboardDispatcher.Subscriber = null; }
                }
            }
        }

        /// <summary>
        /// Disposes the dropdown, cleaning up event subscriptions and keyboard focus.
        /// </summary>
        /// <remarks>
        /// Unsubscribes from the highest parent's <c>OnAddedToGUIUpdateList</c> event.
        /// Releases keyboard focus if this dropdown is the current keyboard subscriber.
        /// </remarks>
        public void Dispose()
        {
            if (currentHighestParent != null && currentHighestParent.GUIComponent != null)
            {
                currentHighestParent.GUIComponent.OnAddedToGUIUpdateList -= AddListBoxToGUIUpdateList;
                currentHighestParent = null;
            }
            if (BGUI.KeyboardDispatcher.Subscriber == this)
            {
                BGUI.KeyboardDispatcher.Subscriber = null;
            }
        }
    }
}