// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using Barotrauma;
using Microsoft.Xna.Framework;

namespace SOS.GUI
{
    /// <summary>
    /// A layout group that automatically recalculates its height based on visible children.
    /// </summary>
    /// <remarks>
    /// Overrides <see cref="Update"/> to call <see cref="Recalculate"/> when <see cref="GUILayoutGroup.NeedsToRecalculate"/>
    /// is true, and then refreshes ancestor list boxes. The <see cref="Recalculate"/> method sums the heights
    /// of visible children plus spacing, and updates the MinSize/MaxSize accordingly.
    /// </remarks>
    public class GUILayoutGroupAuto : GUILayoutGroup
    {
        /// <summary>
        /// Creates a new auto-recalculating layout group.
        /// </summary>
        /// <param name="rectT">The rectangle transform for positioning and sizing.</param>
        /// <param name="isHorizontal">Whether the layout is horizontal. Defaults to false (vertical).</param>
        /// <param name="childAnchor">The anchor for child elements. Defaults to TopLeft.</param>
        /// <remarks>
        /// Passes parameters to the base <see cref="GUILayoutGroup"/> constructor.
        /// </remarks>
        public GUILayoutGroupAuto(RectTransform rectT, bool isHorizontal = false, Anchor childAnchor = Anchor.TopLeft) : base(rectT, isHorizontal: isHorizontal, childAnchor: childAnchor) { }

        /// <summary>
        /// Updates the layout group, recalculating if needed and refreshing ancestor list boxes.
        /// </summary>
        /// <param name="deltaTime">Time elapsed since the last update in seconds.</param>
        /// <remarks>
        /// If <see cref="GUILayoutGroup.NeedsToRecalculate"/> is true, calls <see cref="Recalculate"/> and then
        /// <see cref="RefreshAncestors"/> to notify parent list boxes of size changes.
        /// </remarks>
        public override void Update(float deltaTime)
        {
            if (NeedsToRecalculate && Recalculate()) RefreshAncestors();
            base.Update(deltaTime);
        }

        /// <summary>
        /// Recalculates the layout group's height based on visible children.
        /// </summary>
        /// <returns><c>true</c> if the MinSize changed; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// Sums the heights of all visible children plus <see cref="GUILayoutGroup.AbsoluteSpacing"/> between them,
        /// plus 10 pixels of bottom padding. Updates <see cref="RectTransform.MinSize"/> and <see cref="RectTransform.MaxSize"/>.
        /// If the size changed and the parent is a <see cref="GUILayoutGroup"/>, marks it as needing recalculation.
        /// </remarks>
        public new bool Recalculate()
        {
            int totalHeight = 0;
            foreach (GUIComponent child in Children)
            {
                if (!child.Visible) { continue; }
                totalHeight += child.Rect.Height + AbsoluteSpacing;
            }
            totalHeight += 10;

            var min = new Point(0, totalHeight);
            bool changed = RectTransform.MinSize != min;
            if (changed)
            {
                RectTransform.MinSize = min;
                RectTransform.MaxSize = new Point(int.MaxValue, totalHeight);
                Logger.LogDebug($"LayoutGroupAuto.Recalculate {GetType().Name}: MinSize.Y={RectTransform.MinSize.Y} (childs={Children.Count()})", level: LogLevel.Trace);
            }
            else
            {
                Logger.LogDebug($"LayoutGroupAuto.Recalculate {GetType().Name}: No changes (childs={Children.Count()})", level: LogLevel.Trace);
            }
            base.Recalculate();

            if (changed && Parent is GUILayoutGroup group)
            {
                group.NeedsToRecalculate = true;
            }

            return changed;
        }

        /// <summary>
        /// Refreshes all ancestor <see cref="GUIListBox"/> components up the hierarchy.
        /// </summary>
        /// <remarks>
        /// Traverses up the parent hierarchy and marks any <see cref="GUIListBox"/> ancestors
        /// as needing dimension recalculation by setting <c>dimensionsNeedsRecalculation</c> to true.
        /// This ensures the list box updates its scroll bar and content layout.
        /// </remarks>
        private void RefreshAncestors()
        {
            for (RectTransform? ancestor = RectTransform.Parent; ancestor != null; ancestor = ancestor.Parent)
            {
                if (ancestor.GUIComponent is GUIListBox listBox)
                {
                    Logger.LogDebug($"LayoutGroupAuto: refresh all of {nameof(GUIListBox)}", level: LogLevel.Trace);
                    listBox.dimensionsNeedsRecalculation = true;
                }
            }
        }
    }
}