// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using System.Text;
using Barotrauma;
using Microsoft.Xna.Framework;

namespace SOS.GUI
{
    /// <summary>
    /// A fluent declarative UI builder for creating standard Barotrauma GUI components in a list box.
    /// </summary>
    /// <remarks>
    /// Extends <see cref="GUILayoutGroupAuto"/> to provide a fluent API for building UI rows with
    /// common patterns: headers, label-value rows, badge rows, selector rows, separators, buttons,
    /// text boxes, dropdowns, tick boxes, and sliders. Implements <see cref="IDisposable"/> to
    /// auto-cleanup empty builders or recalculate layout on disposal.
    /// </remarks>
    /// <example>
    /// <code>
    /// using var builder = new GUILayoutBuilder(listBox);
    /// builder.Header("Section Title", Color.White);
    /// builder.Row("Label:", "Value", Color.Green);
    /// builder.BadgeRow("Tags:", new[] { "tag1", "tag2" });
    /// builder.Button("Click Me", () => Console.WriteLine("Clicked"));
    /// builder.Separator();
    /// </code>
    /// </example>
    public class GUILayoutBuilder : GUILayoutGroupAuto, IDisposable
    {
        /// <summary>
        /// Creates a new layout builder for the specified list box.
        /// </summary>
        /// <param name="listBox">The list box whose content area will contain the built UI.</param>
        /// <remarks>
        /// Creates a <see cref="RectTransform"/> anchored to the top center of the list box's content area,
        /// with full width and auto height.
        /// </remarks>
        public GUILayoutBuilder(GUIListBox listBox)
            : base(new RectTransform(new Vector2(1f, 0f), listBox.Content.RectTransform, Anchor.TopCenter))
        {
        }

        /// <summary>
        /// Creates a new layout builder with a custom rectangle transform.
        /// </summary>
        /// <param name="rectT">The rectangle transform to use as the parent for built components.</param>
        /// <remarks>
        /// Internal constructor used by <see cref="Accordion"/> methods to create nested builders.
        /// </remarks>
        internal GUILayoutBuilder(RectTransform rectT) : base(rectT) { }

        /// <summary>
        /// Adds a header text block with the specified title and color.
        /// </summary>
        /// <param name="title">The header text.</param>
        /// <param name="color">The text color.</param>
        /// <returns>The created <see cref="GUITextBlock"/> with subheading font, left alignment, and 30px fixed height.</returns>
        /// <remarks>
        /// The header has a left padding of 10 pixels and spans the full width of the builder.
        /// </remarks>
        public GUITextBlock Header(string title, Color color)
        {
            var titleBlock = new GUITextBlock(new RectTransform(new Vector2(1f, 0f), RectTransform), title, font: GUIStyle.SubHeadingFont, textColor: color, textAlignment: Alignment.Left)
            {
                CanBeFocused = false
            };
            titleBlock.RectTransform.MinSize = new Point(0, 30);
            titleBlock.RectTransform.MaxSize = new Point(int.MaxValue, 30);
            titleBlock.Padding = new Vector4(10, 0, 0, 0);
            return titleBlock;
        }

        /// <summary>
        /// Adds a label-value row with the specified label, value, and value color.
        /// </summary>
        /// <param name="label">The label text (left side).</param>
        /// <param name="value">The value text (right side). If null or empty, returns null.</param>
        /// <param name="valueColor">The color of the value text.</param>
        /// <returns>The created <see cref="GUIButton"/> row, or null if value is empty.</returns>
        /// <remarks>
        /// Creates a button-style row with a label on the left (gray) and value on the right (colored).
        /// The label width is automatically calculated based on the label text length, capped at 70% of row width.
        /// The row height auto-adjusts to fit the taller of the label or value text.
        /// </remarks>
        public GUIButton? Row(string label, string value, Color valueColor)
        {
            if (string.IsNullOrEmpty(value)) return null;

            var row = new GUIButton(new RectTransform(new Vector2(1f, 0f), RectTransform), style: null)
            {
                CanBeFocused = false
            };

            float rowWidth = Rect.Width > 0 ? Rect.Width : 400f;
            float labelW = GUIStyle.SmallFont.MeasureString(label).X + 8f;
            float labelRatio = Math.Min(labelW / rowWidth, 0.70f);

            var lblBlock = new GUITextBlock(
                new RectTransform(new Vector2(labelRatio, 1f), row.RectTransform, Anchor.CenterLeft),
                label, font: GUIStyle.SmallFont, textColor: Color.Gray, wrap: false)
            { CanBeFocused = false };

            var valBlock = new GUITextBlock(
                new RectTransform(new Vector2(1f - labelRatio, 1f), row.RectTransform, Anchor.CenterRight),
                value, font: GUIStyle.SmallFont, textColor: valueColor, textAlignment: Alignment.Right, wrap: true)
            { CanBeFocused = false };

            void UpdateHeight()
            {
                float h = Math.Max(lblBlock.TextSize.Y, valBlock.TextSize.Y) + 4f;
                row.RectTransform.MinSize = new Point(0, (int)h);
                row.RectTransform.MaxSize = new Point(int.MaxValue, (int)h);
            }
            UpdateHeight();
            lblBlock.RectTransform.SizeChanged += UpdateHeight;
            valBlock.RectTransform.SizeChanged += UpdateHeight;

            return row;
        }

        /// <summary>
        /// Adds a row with a label and multiple badge-style values that act as hyperlinks.
        /// </summary>
        /// <param name="label">The label text (left side).</param>
        /// <param name="values">The badge values to display. If null or empty, returns null.</param>
        /// <param name="displayNames">Optional display names for each value. If provided, must match <paramref name="values"/> count.</param>
        /// <param name="filterPrefix">Optional prefix to prepend to values when used as search filters.</param>
        /// <param name="linkColor">Optional color for the badge links. Defaults to LightSkyBlue.</param>
        /// <param name="onSearchFilter">Optional callback invoked when a badge is clicked, receiving the (prefixed) value.</param>
        /// <returns>The created <see cref="GUIButton"/> row, or null if no values.</returns>
        /// <remarks>
        /// Each badge is formatted as a colored hyperlink using RichText syntax. Badges are comma-separated.
        /// If only one badge is present, the entire row becomes clickable with hand cursor.
        /// The row height auto-adjusts to fit the badge text, with a minimum of 24px.
        /// </remarks>
        public GUIButton? BadgeRow(
            string label,
            IEnumerable<string> values,
            IEnumerable<string>? displayNames = null,
            char? filterPrefix = null,
            Color? linkColor = null,
            Action<string>? onSearchFilter = null)
        {
            if (values == null || !values.Any()) return null;

            var valList = values.ToList();
            var dispList = displayNames?.ToList();

            var data = valList.Select((val, i) => new
            {
                Target = filterPrefix.HasValue ? $"{filterPrefix}{val}" : val,
                Display = dispList != null && i < dispList.Count ? dispList[i] : val
            }).ToList();

            var row = new GUIButton(new RectTransform(new Vector2(1f, 0f), RectTransform), style: null)
            {
                CanBeFocused = false
            };
            _ = new GUITextBlock(new RectTransform(new Vector2(0.40f, 1f), row.RectTransform, Anchor.CenterLeft), label, font: GUIStyle.SmallFont, textColor: Color.Gray) { CanBeFocused = false };

            var sb = new StringBuilder();
            for (int i = 0; i < data.Count; i++)
            {
                var d = data[i];
                var c = linkColor ?? Color.LightSkyBlue;
                sb.Append($"‖color:{c.R},{c.G},{c.B}‖{d.Display}‖end‖");
                if (i < data.Count - 1)
                    sb.Append(", ");
            }

            var textBlock = new GUITextBlock(new RectTransform(new Vector2(0.60f, 0f), row.RectTransform, Anchor.CenterRight), "", wrap: true, font: GUIStyle.SmallFont, textAlignment: Alignment.TopLeft);
            textBlock.SetRichText(RichString.Rich(sb.ToString()));

            BindHyperlinks(textBlock, data, d => onSearchFilter?.Invoke(d.Target));

            void UpdateLayout()
            {
                int maxW = (int)(row.Rect.Width * 0.60f);
                if (maxW > 0)
                {
                    textBlock.RectTransform.NonScaledSize = new Point(maxW, (int)textBlock.TextSize.Y);
                    float lineH = GUIStyle.SmallFont.LineHeight;
                    if (textBlock.TextSize.Y <= lineH * 1.5f)
                    {
                        int paddingH = (int)(textBlock.Padding.X + textBlock.Padding.Z);
                        int fitW = Math.Min((int)Math.Ceiling(textBlock.TextSize.X + paddingH) + 4, maxW);
                        textBlock.RectTransform.NonScaledSize = new Point(fitW, (int)textBlock.TextSize.Y);
                    }
                }

                int h = Math.Max(24, (int)textBlock.TextSize.Y + 4);
                row.RectTransform.MinSize = new Point(0, h);
                row.RectTransform.MaxSize = new Point(int.MaxValue, h);
            }
            UpdateLayout();
            row.RectTransform.SizeChanged += UpdateLayout;

            if (data.Count == 1)
            {
                var single = data[0];
                row.CanBeFocused = true;
                row.HoverCursor = CursorState.Hand;
                row.OnClicked = (comp, obj) => { onSearchFilter?.Invoke(single.Target); return true; };
            }

            return row;
        }

        /// <summary>
        /// Adds a row with a label and multiple selectable items (prefabs or prefixed strings) acting as hyperlinks.
        /// </summary>
        /// <param name="label">The label text (left side).</param>
        /// <param name="ids">The item identifiers to display. If null or empty, returns null.</param>
        /// <param name="displayNames">Optional display names for each identifier. If provided, must match <paramref name="ids"/> count.</param>
        /// <param name="fallbackFilterPrefix">Optional prefix for identifiers that don't resolve to a known prefab.</param>
        /// <param name="labelColor">Optional color for the label. Defaults to Gray.</param>
        /// <param name="onPrimary">Callback for primary click on a resolved prefab.</param>
        /// <param name="onSecondary">Callback for secondary click on a resolved prefab.</param>
        /// <param name="onSearchFilter">Callback for click on a non-prefab identifier (prefixed string).</param>
        /// <returns>The created <see cref="GUIButton"/> row, or null if no identifiers.</returns>
        /// <remarks>
        /// Attempts to resolve each identifier to an <see cref="ItemPrefab"/> or <see cref="AfflictionPrefab"/>.
        /// Resolved prefabs use their name and icon color; unresolved identifiers use the display name or raw id
        /// with the fallback prefix and LightSkyBlue color.
        /// If only one item is present, the row becomes clickable with hand cursor.
        /// </remarks>
        public GUIButton? SelectorRow(
            string label,
            IEnumerable<string> ids,
            IEnumerable<string>? displayNames = null,
            char? fallbackFilterPrefix = null,
            Color? labelColor = null,
            Action<Prefab>? onPrimary = null,
            Action<Prefab>? onSecondary = null,
            Action<string>? onSearchFilter = null)
        {
            if (ids == null || !ids.Any()) return null;

            var idList = ids.ToList();
            var nameList = displayNames?.ToList();

            var data = new List<object>();
            for (int i = 0; i < idList.Count; i++)
            {
                string id = idList[i];
                Prefab? found = (Prefab?)AfflictionPrefab.List.FirstOrDefault(a => a.Identifier.Value == id)
                             ?? ItemPrefab.Prefabs.FirstOrDefault(p => p.Identifier.Value == id);

                if (found != null) data.Add(found);
                else data.Add(fallbackFilterPrefix.HasValue ? $"{fallbackFilterPrefix}{id}" : id);
            }

            string GetText(object obj, int index)
            {
                if (obj is ItemPrefab ip) return ip.Name.Value;
                if (obj is AfflictionPrefab ap) return ap.Name.Value;
                return (nameList != null && index < nameList.Count) ? nameList[index] : obj.ToString()!;
            }

            Color GetColor(object obj)
            {
                if (obj is ItemPrefab ip) return ip.InventoryIconColor;
                if (obj is AfflictionPrefab ap) return ap.IconColors?.FirstOrDefault() ?? Color.White;
                return Color.LightSkyBlue;
            }

            var row = new GUIButton(new RectTransform(new Vector2(1f, 0f), RectTransform), style: null)
            {
                CanBeFocused = false
            };
            _ = new GUITextBlock(new RectTransform(new Vector2(0.40f, 1f), row.RectTransform, Anchor.CenterLeft), label, font: GUIStyle.SmallFont, textColor: labelColor ?? Color.Gray) { CanBeFocused = false };

            var sb = new StringBuilder();
            for (int i = 0; i < data.Count; i++)
            {
                var obj = data[i];
                var c = GetColor(obj);
                sb.Append($"‖color:{c.R},{c.G},{c.B}‖{GetText(obj, i)}‖end‖");
                if (i < data.Count - 1)
                    sb.Append(", ");
            }

            var textBlock = new GUITextBlock(new RectTransform(new Vector2(0.60f, 0f), row.RectTransform, Anchor.CenterRight), "", wrap: true, font: GUIStyle.SmallFont, textAlignment: Alignment.TopLeft);
            textBlock.SetRichText(RichString.Rich(sb.ToString()));

            BindHyperlinks(
                textBlock,
                data,
                onPrimaryClick: obj => { if (obj is Prefab p) onPrimary?.Invoke(p); else onSearchFilter?.Invoke(obj.ToString()!); },
                onSecondaryClick: obj => { if (obj is Prefab p) onSecondary?.Invoke(p); }
            );

            void UpdateLayout()
            {
                int maxW = (int)(row.Rect.Width * 0.60f);
                if (maxW > 0)
                {
                    textBlock.RectTransform.NonScaledSize = new Point(maxW, (int)textBlock.TextSize.Y);
                    float lineH = GUIStyle.SmallFont.LineHeight;
                    if (textBlock.TextSize.Y <= lineH * 1.5f)
                    {
                        int paddingH = (int)(textBlock.Padding.X + textBlock.Padding.Z);
                        int fitW = Math.Min((int)Math.Ceiling(textBlock.TextSize.X + paddingH) + 4, maxW);
                        textBlock.RectTransform.NonScaledSize = new Point(fitW, (int)textBlock.TextSize.Y);
                    }
                }

                int h = Math.Max(24, (int)textBlock.TextSize.Y + 4);
                row.RectTransform.MinSize = new Point(0, h);
                row.RectTransform.MaxSize = new Point(int.MaxValue, h);
            }
            UpdateLayout();
            row.RectTransform.SizeChanged += UpdateLayout;

            if (data.Count == 1)
            {
                var single = data[0];
                row.CanBeFocused = true;
                row.HoverCursor = CursorState.Hand;
                row.OnClicked = (comp, obj) =>
                {
                    if (single is Prefab p) onPrimary?.Invoke(p);
                    else onSearchFilter?.Invoke(single.ToString()!);
                    return true;
                };
                row.OnSecondaryClicked = (comp, obj) =>
                {
                    if (single is Prefab p) onSecondary?.Invoke(p);
                    return true;
                };
            }

            return row;
        }

        /// <summary>
        /// Adds a rich text block with the specified content.
        /// </summary>
        /// <param name="text">The rich text to display. If null or empty, returns null.</param>
        /// <returns>The created <see cref="GUITextBlock"/>, or null if text is empty.</returns>
        /// <remarks>
        /// Uses <see cref="GUIStyle.SmallFont"/> with left alignment and wrapping enabled.
        /// The block height auto-adjusts to fit the text content with 10px padding.
        /// Marked TODO for removal in favor of TextBox.
        /// </remarks>
        public GUITextBlock? RichText(RichString text) //TODO: Eliminar en favor de TextBox.    
        {
            if (text.IsNullOrEmpty()) return null;

            var block = new GUITextBlock(new RectTransform(new Vector2(1f, 0f), RectTransform), RichString.Rich(text), font: GUIStyle.SmallFont, wrap: true, textAlignment: Alignment.Left)
            {
                CanBeFocused = false
            };

            void UpdateHeight()
            {
                int h = (int)block.TextSize.Y + 10;
                block.RectTransform.MinSize = new Point(0, h);
                block.RectTransform.MaxSize = new Point(int.MaxValue, h);
            }
            UpdateHeight();
            block.RectTransform.SizeChanged += UpdateHeight;

            return block;
        }

        //TODO: Hecho por IA, aún no revisado.
        #region Hecho por IA, aún no revisado.

        /// <summary>
        /// Adds a horizontal separator line.
        /// </summary>
        /// <returns>A 2px tall <see cref="GUIFrame"/> with a gray color, spanning the full width.</returns>
        /// <remarks>
        /// Uses the "GUIFrameBottom" style and sets color to 40% gray.
        /// </remarks>
        public GUIFrame Separator()
        {
            return new GUIFrame(new RectTransform(new Vector2(1f, 0f), RectTransform) { MinSize = new Point(0, 2), MaxSize = new Point(int.MaxValue, 2) }, style: "GUIFrameBottom")
            {
                Color = Color.Gray * 0.4f,
                CanBeFocused = false
            };
        }

        /// <summary>
        /// Adds a simple button with the specified text, click handler, and optional tooltip, color, and style.
        /// </summary>
        /// <param name="text">The button text.</param>
        /// <param name="onClick">The action to invoke when clicked.</param>
        /// <param name="tooltip">Optional tooltip text.</param>
        /// <param name="color">Optional button color.</param>
        /// <param name="style">The GUI style name. Defaults to "GUIButtonSmall".</param>
        /// <returns>The created <see cref="GUIButton"/> with 28px minimum height.</returns>
        public GUIButton Button(string text, Action onClick, string? tooltip = null, Color? color = null, string style = "GUIButtonSmall")
        {
            var btn = new GUIButton(new RectTransform(new Vector2(1f, 0f), RectTransform) { MinSize = new Point(0, 28) }, text, style: style)
            {
                CanBeFocused = true,
                OnClicked = (_, _) => { onClick(); return true; }
            };
            if (tooltip != null) btn.ToolTip = tooltip;
            if (color.HasValue) btn.Color = color.Value;
            return btn;
        }

        /// <summary>
        /// Adds a composite button row with an apply button and a delete button.
        /// </summary>
        /// <param name="text">The text for the apply button.</param>
        /// <param name="onClick">The action to invoke when the apply button is clicked.</param>
        /// <param name="applyTooltip">Tooltip for the apply button.</param>
        /// <param name="onDeleteClick">Action to invoke when the delete button is clicked.</param>
        /// <param name="deleteTooltip">Tooltip for the delete button.</param>
        /// <param name="color">Optional color for the apply button.</param>
        /// <param name="style">The GUI style name for the apply button. Defaults to "GUIButtonSmall".</param>
        /// <returns>The apply <see cref="GUIButton"/> (the delete button is created but not returned).</returns>
        /// <remarks>
        /// Creates a horizontal row containing the apply button (90% width) and a red "x" delete button (28px).
        /// The delete button uses "GUICancelButton" style with IndianRed color.
        /// </remarks>
        public GUIButton Button(string text, Action onClick, string applyTooltip, Action onDeleteClick, string deleteTooltip, Color? color = null, string style = "GUIButtonSmall")
        {
            var row = new GUIFrame(new RectTransform(new Vector2(1f, 0f), RectTransform) { MinSize = new Point(0, 28) }, style: null) { CanBeFocused = false };

            var apply = new GUIButton(new RectTransform(new Vector2(0.9f, 1f), row.RectTransform, Anchor.CenterLeft), text, style: style)
            {
                ToolTip = applyTooltip,
                CanBeFocused = true,
                OnClicked = (_, _) => { onClick(); return true; }
            };
            if (color.HasValue) apply.Color = color.Value;

            _ = new GUIButton(new RectTransform(new Point(28, 28), row.RectTransform, Anchor.CenterRight), "x", style: "GUICancelButton", color: Color.IndianRed)
            {
                ToolTip = deleteTooltip,
                CanBeFocused = true,
                OnClicked = (_, _) => { onDeleteClick(); return true; }
            };

            return apply;
        }

        /// <summary>
        /// Adds a labeled text box with an on-change handler.
        /// </summary>
        /// <param name="label">The label text (left side, gray).</param>
        /// <param name="initialValue">The initial text box value.</param>
        /// <param name="onChange">Action invoked when the text changes, receiving the new text.</param>
        /// <returns>The created <see cref="GUITextBox"/> with small font.</returns>
        /// <remarks>
        /// Creates a row with the label (35% width) and text box (60% width).
        /// </remarks>
        public GUITextBox TextBox(string label, string initialValue, Action<string> onChange)
        {
            var row = new GUIFrame(new RectTransform(new Vector2(1f, 0f), RectTransform) { MinSize = new Point(0, 28) }, style: null) { CanBeFocused = false };
            _ = new GUITextBlock(new RectTransform(new Vector2(0.35f, 1f), row.RectTransform, Anchor.CenterLeft), label, font: GUIStyle.SmallFont, textColor: Color.Gray) { CanBeFocused = false };
            var textBox = new GUITextBox(new RectTransform(new Vector2(0.6f, 1f), row.RectTransform, Anchor.CenterRight), initialValue, font: GUIStyle.SmallFont);
            textBox.OnTextChanged += (tb, text) => { onChange(text); return true; };
            return textBox;
        }

        /// <summary>
        /// Adds a labeled dropdown with the specified items and selection handler.
        /// </summary>
        /// <param name="label">The label text (left side, gray).</param>
        /// <param name="items">The list of item strings to display in the dropdown.</param>
        /// <param name="selected">The initially selected item, or null for no selection.</param>
        /// <param name="onSelect">Action invoked when an item is selected, receiving the selected string.</param>
        /// <param name="tooltips">Optional tooltips for each item. Must match <paramref name="items"/> count if provided.</param>
        /// <returns>The created <see cref="GUIDropDown"/> with small font.</returns>
        /// <remarks>
        /// Creates a row with the label (35% width) and dropdown (60% width).
        /// The dropdown shows up to the number of items, with each item having an optional tooltip.
        /// </remarks>
        public GUIDropDown Dropdown(string label, IReadOnlyList<string> items, string? selected, Action<string> onSelect, IReadOnlyList<string?>? tooltips = null)
        {
            var row = new GUIFrame(new RectTransform(new Vector2(1f, 0f), RectTransform) { MinSize = new Point(0, 28) }, style: null) { CanBeFocused = false };
            _ = new GUITextBlock(new RectTransform(new Vector2(0.35f, 1f), row.RectTransform, Anchor.CenterLeft), label, font: GUIStyle.SmallFont, textColor: Color.Gray) { CanBeFocused = false };

            var dropdown = new GUIDropDown(new RectTransform(new Vector2(0.6f, 1f), row.RectTransform, Anchor.CenterRight), text: "", elementCount: items.Count) { CanBeFocused = true, Font = GUIStyle.SmallFont };
            for (var i = 0; i < items.Count; i++)
            {
                string tooltipText = (tooltips?.Count >= i) ? tooltips?[i] ?? "" : "";
                var item = items[i];
                dropdown.AddItem(item, item, tooltipText);
                if (item == selected) dropdown.SelectItem(item);
            }
            dropdown.OnSelected = (comp, obj) =>
            {
                if (obj is string s) onSelect(s);
                return true;
            };
            return dropdown;
        }

        /// <summary>
        /// Adds a labeled tick box (checkbox) with a toggle handler.
        /// </summary>
        /// <param name="label">The label text for the tick box.</param>
        /// <param name="selected">The initial checked state.</param>
        /// <param name="onToggle">Action invoked when the tick box state changes, receiving the new state.</param>
        /// <returns>The created <see cref="GUITickBox"/> with small font.</returns>
        /// <remarks>
        /// Creates a row with the tick box spanning the full width (100%).
        /// The label is the tick box's text, not a separate label column.
        /// </remarks>
        public GUITickBox TickBox(string label, bool selected, Action<bool> onToggle)
        {
            var row = new GUIFrame(new RectTransform(new Vector2(1f, 0f), RectTransform) { MinSize = new Point(0, 26) }, style: null) { CanBeFocused = false };
            var tick = new GUITickBox(new RectTransform(new Vector2(1f, 1f), row.RectTransform, Anchor.CenterLeft), label, font: GUIStyle.SmallFont)
            {
                Selected = selected,
                CanBeFocused = true,
                OnSelected = (tb) => { onToggle(tb.Selected); return true; }
            };
            return tick;
        }

        /// <summary>
        /// Adds a labeled horizontal slider with a value display and change handler.
        /// </summary>
        /// <param name="label">The label text (left side, gray).</param>
        /// <param name="min">The minimum slider value.</param>
        /// <param name="max">The maximum slider value.</param>
        /// <param name="value">The initial slider value.</param>
        /// <param name="onChange">Action invoked when the slider value changes, receiving the new value.</param>
        /// <returns>The created <see cref="GUIScrollBar"/> styled as a slider.</returns>
        /// <remarks>
        /// Creates a row with the label (35% width), slider (55% width), and value display (10% width).
        /// The slider uses "GUISlider" style with 0.1 bar size.
        /// The value display shows the value formatted with zero decimal places.
        /// </remarks>
        public GUIScrollBar Slider(string label, float min, float max, float value, Action<float> onChange)
        {
            var row = new GUIFrame(new RectTransform(new Vector2(1f, 0f), RectTransform) { MinSize = new Point(0, 28) }, style: null) { CanBeFocused = false };
            _ = new GUITextBlock(new RectTransform(new Vector2(0.35f, 1f), row.RectTransform, Anchor.CenterLeft), label, font: GUIStyle.SmallFont, textColor: Color.Gray) { CanBeFocused = false };

            var slider = new GUIScrollBar(new RectTransform(new Vector2(0.55f, 0.6f), row.RectTransform, Anchor.CenterRight), barSize: 0.1f, style: "GUISlider", isHorizontal: true)
            {
                MinValue = min,
                MaxValue = max,
                BarScroll = (value - min) / (max - min),
                OnMoved = (sb, val) =>
                {
                    float v = min + val * (max - min);
                    onChange(v);
                    return true;
                }
            };

            var valText = new GUITextBlock(new RectTransform(new Vector2(0.1f, 1f), row.RectTransform, Anchor.CenterRight), value.FormatZeroDecimal(), font: GUIStyle.SmallFont, textAlignment: Alignment.CenterRight) { CanBeFocused = false };
            slider.OnMoved = (sb, val) =>
            {
                float v = min + val * (max - min);
                valText.Text = ((int)v).ToString();
                onChange(v);
                return true;
            };
            return slider;
        }

        #endregion

        private static void BindHyperlinks<T>(
            GUITextBlock textBlock,
            IEnumerable<T> items,
            Action<T> onPrimaryClick,
            Action<T>? onSecondaryClick = null)
        {
            var list = items.ToList();

            void ApplyLinks()
            {
                if (textBlock.RichTextData == null) return;
                textBlock.ClickableAreas.Clear();

                int index = 0;
                foreach (var data in textBlock.RichTextData)
                {
                    if (data.StartIndex >= data.EndIndex || data.StartIndex < 0 || data.Color == null) continue;
                    if (index >= list.Count) break;

                    var target = list[index];
                    textBlock.ClickableAreas.Add(new GUITextBlock.ClickableArea()
                    {
                        Data = data,
                        OnClick = (tb, area) => { onPrimaryClick?.Invoke(target); },
                        OnSecondaryClick = onSecondaryClick != null ? ((tb, area) => { onSecondaryClick.Invoke(target); }) : null
                    });
                    index++;
                }
            }

            ApplyLinks();
            textBlock.RectTransform.SizeChanged += ApplyLinks;
        }

        /// <summary>
        /// Creates an accordion (collapsible section) with a header and returns its content builder.
        /// </summary>
        /// <param name="title">The accordion header title.</param>
        /// <param name="tooltip">Optional tooltip for the header.</param>
        /// <param name="collapsed">Whether the accordion starts collapsed. Defaults to false.</param>
        /// <param name="onToggle">Optional callback invoked when the accordion is toggled, receiving the new collapsed state.</param>
        /// <param name="iconAnchor">The anchor for the expand/collapse chevron icon. Defaults to CenterRight.</param>
        /// <returns>A new <see cref="GUILayoutBuilder"/> for the accordion's content area.</returns>
        /// <remarks>
        /// Creates a <see cref="GUIAccordion"/> with the specified title and settings.
        /// The returned builder can be used to add content inside the accordion.
        /// </remarks>
        public GUILayoutBuilder Accordion(string title, string? tooltip = null, bool collapsed = false, Action<bool>? onToggle = null, Anchor iconAnchor = Anchor.CenterRight)
        {
            var accordion = new GUIAccordion(title, RectTransform, tooltip, collapsed, onToggle, iconAnchor);
            return accordion.Content;
        }

        /// <summary>
        /// Creates an accordion (collapsible section) with a custom header component and returns its content builder.
        /// </summary>
        /// <param name="header">The custom header component to use.</param>
        /// <param name="collapsed">Whether the accordion starts collapsed. Defaults to false.</param>
        /// <param name="onToggle">Optional callback invoked when the accordion is toggled, receiving the new collapsed state.</param>
        /// <param name="iconAnchor">The anchor for the expand/collapse chevron icon. Defaults to CenterRight.</param>
        /// <returns>A new <see cref="GUILayoutBuilder"/> for the accordion's content area.</returns>
        /// <remarks>
        /// Creates a <see cref="GUIAccordion"/> with the specified header component and settings.
        /// The returned builder can be used to add content inside the accordion.
        /// </remarks>
        public GUILayoutBuilder Accordion(GUIComponent header, bool collapsed = false, Action<bool>? onToggle = null, Anchor iconAnchor = Anchor.CenterRight)
        {
            var accordion = new GUIAccordion(header, RectTransform, collapsed, onToggle, iconAnchor);
            return accordion.Content;
        }

        /// <summary>
        /// Disposes the layout builder, removing it from its parent if empty or recalculating layout.
        /// </summary>
        /// <remarks>
        /// If the builder has no children, it is removed from its parent.
        /// Otherwise, <see cref="Recalculate"/> is called to update the layout.
        /// Suppresses finalization to prevent the finalizer from running.
        /// </remarks>
        public void Dispose()
        {
            if (!Children.Any())
                Parent?.RemoveChild(this);
            else
                Recalculate();

            GC.SuppressFinalize(this);
        }

        /// <summary>
        /// Finalizer that calls <see cref="Dispose"/>.
        /// </summary>
        ~GUILayoutBuilder() => Dispose();
    }
}