// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using Barotrauma;
using Microsoft.Xna.Framework;

namespace SOS.GUI
{
    /// <summary>
    /// A navigation history component with back/forward buttons for tracking and navigating through a history of items.
    /// </summary>
    /// <typeparam name="T">The type of items in the history. Must not be null.</typeparam>
    /// <remarks>
    /// Provides a UI with back and forward buttons, keyboard shortcuts (Alt+Left/Right, Backspace, Mouse 4/5),
    /// and events for navigation actions. The history is maintained as a list with a current index pointer.
    /// Thread-safe: this component is not thread-safe; all operations must be called from the UI thread.
    /// </remarks>
    public sealed class GUINavigationHistory<T> : GUICustomComponent where T : notnull
    {
        /// <summary>
        /// The history list storing all navigated items.
        /// </summary>
        private readonly List<T> _history = [];

        /// <summary>
        /// Flag indicating whether a navigation action is in progress.
        /// </summary>
        /// <remarks>
        /// Prevents re-entrant calls during <see cref="OnNavigateBack"/> and <see cref="OnNavigateForward"/> events.
        /// </remarks>
        private bool _isNavigating = false;

        /// <summary>
        /// The back navigation button.
        /// </summary>
        private readonly GUIButton _btnBack;

        /// <summary>
        /// The forward navigation button.
        /// </summary>
        private readonly GUIButton _btnForward;

        /// <summary>
        /// The layout group containing the back and forward buttons.
        /// </summary>
        private readonly GUILayoutGroup _layoutGroup;

        /// <summary>
        /// Event invoked when navigating back in history.
        /// </summary>
        /// <remarks>
        /// The parameter is the item being navigated to (the previous item in history).
        /// </remarks>
        public event Action<T?>? OnNavigateBack;

        /// <summary>
        /// Event invoked when navigating forward in history.
        /// </summary>
        /// <remarks>
        /// The parameter is the item being navigated to (the next item in history).
        /// </remarks>
        public event Action<T?>? OnNavigateForward;

        /// <summary>
        /// Event invoked when the history changes (item added, removed, or index changed).
        /// </summary>
        public event Action? OnHistoryChanged;

        /// <summary>
        /// Gets whether navigation back is possible (current index > 0).
        /// </summary>
        public bool CanNavigateBack => Index > 0;

        /// <summary>
        /// Gets whether navigation forward is possible (index &gt;= 0 and index &lt; history count - 1).
        /// </summary>
        public bool CanNavigateForward => Index >= 0 && Index < _history.Count - 1;

        /// <summary>
        /// Gets the read-only history list.
        /// </summary>
        public IReadOnlyList<T> History => _history;

        /// <summary>
        /// Gets or sets the current history index.
        /// </summary>
        /// <remarks>
        /// Setting the index directly does not trigger navigation events. Use <see cref="NavigateBack"/>,
        /// <see cref="NavigateForward"/>, or <see cref="Push"/> for eventful navigation.
        /// </remarks>
        public int Index { get; private set; }

        /// <summary>
        /// Gets the current history index (alias for <see cref="Index"/>).
        /// </summary>
        public int CurrentIndex => Index;

        /// <summary>
        /// Gets the number of items in the history.
        /// </summary>
        public int Count => _history.Count;

        /// <summary>
        /// Optional function to dynamically generate the back button's tooltip based on the item that would be navigated to.
        /// </summary>
        public Func<T?, RichString>? OnChangeToolTipBack;

        /// <summary>
        /// Optional function to dynamically generate the forward button's tooltip based on the item that would be navigated to.
        /// </summary>
        public Func<T?, RichString>? OnChangeToolTipForward;

        /// <summary>
        /// Gets the item that would be navigated to when going back, without actually navigating.
        /// </summary>
        /// <returns>The previous item in history, or default if at the beginning.</returns>
        public T? PeekBack() => CanNavigateBack ? _history[Index - 1] : default;

        /// <summary>
        /// Gets the item that would be navigated to when going forward, without actually navigating.
        /// </summary>
        /// <returns>The next item in history, or default if at the end.</returns>
        public T? PeekForward() => CanNavigateForward ? _history[Index + 1] : default;

        /// <summary>
        /// Creates a new navigation history component.
        /// </summary>
        /// <param name="recT">The rectangle transform for positioning and sizing.</param>
        /// <param name="history">Optional initial history items. If provided, they are added to the history list.</param>
        /// <param name="index">The initial history index. Defaults to 0.</param>
        /// <remarks>
        /// Creates a horizontal layout group with back and forward toggle buttons.
        /// Back button uses "GUIButtonToggleLeft" style, forward uses "GUIButtonToggleRight".
        /// Buttons have tooltips with keyboard shortcuts and click handlers for navigation.
        /// </remarks>
        public GUINavigationHistory(RectTransform recT, IEnumerable<T>? history = null, int index = 0) : base(recT)
        {
            CanBeFocused = false;
            if (history != null) _history.AddRange(history);
            Index = index;

            _layoutGroup = new GUILayoutGroup(new RectTransform(Vector2.One, RectTransform), isHorizontal: true)
            {
                Stretch = true,
                AbsoluteSpacing = 4,
                CanBeFocused = false
            };

            _btnBack = new GUIButton(new RectTransform(new Vector2(0.5f, 1f), _layoutGroup.RectTransform), "", style: "GUIButtonToggleLeft")
            {
                ToolTip = $"{Texts.Get("sos.window.back", "Back").SetColor(Color.Gray)}\n{Texts.Get("sos.window.back.shortcuts", "Shortcuts:\n- Alt + Left Arrow\n- Backspace\n- Mouse 4")}".Rich(),
                OnClicked = (_, _) => { NavigateBack(); return true; },
            };
            if (_btnBack.Children.FirstOrDefault() is GUIImage imgB) imgB.SpriteEffects = Microsoft.Xna.Framework.Graphics.SpriteEffects.FlipHorizontally;

            _btnForward = new GUIButton(new RectTransform(new Vector2(0.5f, 1f), _layoutGroup.RectTransform), "", style: "GUIButtonToggleRight")
            {
                ToolTip = $"{Texts.Get("sos.window.forward", "Forward").SetColor(Color.Gray)}\n{Texts.Get("sos.window.forward.shortcuts", "Shortcuts:\n- Alt + Right Arrow\n- Shift + Backspace\n- Mouse 5")}".Rich(),
                OnClicked = (_, _) => { NavigateForward(); return true; },
            };

            UpdateButtonStates();
        }

        /// <summary>
        /// Adds an item to the history, removing any forward history and duplicates.
        /// </summary>
        /// <param name="item">The item to add to history. If null, the method returns without changes.</param>
        /// <remarks>
        /// If currently not at the end of history (can navigate forward), all items after the current index
        /// are removed. If the item already exists in history, it is removed from its old position
        /// before being added to the end. The index is updated to point to the new item.
        /// Does nothing if a navigation is in progress or if the item is already the current item.
        /// </remarks>
        public void Push(T? item)
        {
            if (item == null || _isNavigating ||
                (Index >= 0 && Index < _history.Count && (_history[Index].Equals(item))))
                return;

            if (CanNavigateForward)
                _history.RemoveRange(Index + 1, _history.Count - Index - 1);

            _history.Remove(item);
            _history.Add(item);
            Index = _history.Count - 1;

            Logger.LogDebug($"[NavigationHistory] Pushed '{item}' to History. Index: {Index}, Count: {_history.Count}", level: LogLevel.Trace);
            OnHistoryChanged?.Invoke();
            UpdateButtonStates();
        }

        /// <summary>
        /// Navigates to the previous item in history.
        /// </summary>
        /// <remarks>
        /// Decrements the index, invokes <see cref="OnNavigateBack"/> with the previous item,
        /// then invokes <see cref="OnHistoryChanged"/> and updates button states.
        /// Does nothing if already at the beginning of history.
        /// </remarks>
        public void NavigateBack()
        {
            if (!CanNavigateBack) return;
            Index--;
            var prev = _history[Index];
            _isNavigating = true;
            OnNavigateBack?.Invoke(prev);
            _isNavigating = false;
            OnHistoryChanged?.Invoke();
            UpdateButtonStates();
        }

        /// <summary>
        /// Navigates to the next item in history.
        /// </summary>
        /// <remarks>
        /// Increments the index, invokes <see cref="OnNavigateForward"/> with the next item,
        /// then invokes <see cref="OnHistoryChanged"/> and updates button states.
        /// Does nothing if already at the end of history.
        /// </remarks>
        public void NavigateForward()
        {
            if (!CanNavigateForward) return;
            Index++;
            var next = _history[Index];
            _isNavigating = true;
            OnNavigateForward?.Invoke(next);
            _isNavigating = false;
            OnHistoryChanged?.Invoke();
            UpdateButtonStates();
        }

        /// <summary>
        /// Clears all history items and resets the index.
        /// </summary>
        /// <remarks>
        /// Empties the history list, sets the index to -1 (no current item), invokes
        /// <see cref="OnHistoryChanged"/>, and updates button states.
        /// </remarks>
        public void Clear()
        {
            _history.Clear();
            Index = -1;
            OnHistoryChanged?.Invoke();
            UpdateButtonStates();
        }

        /// <summary>
        /// Sets the history index directly.
        /// </summary>
        /// <param name="index">The new index. Must be between -1 and <see cref="Count"/> - 1.</param>
        /// <remarks>
        /// If the index is out of bounds, the method returns without changes.
        /// Does not trigger navigation events (<see cref="OnNavigateBack"/> or <see cref="OnNavigateForward"/>),
        /// but does invoke <see cref="OnHistoryChanged"/> and updates button states.
        /// </remarks>
        public void SetIndex(int index)
        {
            if (index < -1 || index >= _history.Count) return;
            Index = index;
            OnHistoryChanged?.Invoke();
            UpdateButtonStates();
        }

        /// <summary>
        /// Updates the enabled state and tooltips of the back and forward buttons.
        /// </summary>
        /// <remarks>
        /// Enables/disables buttons based on <see cref="CanNavigateBack"/> and <see cref="CanNavigateForward"/>.
        /// If <see cref="OnChangeToolTipBack"/> or <see cref="OnChangeToolTipForward"/> are set, updates
        /// the button tooltips by calling them with the item that would be navigated to.
        /// </remarks>
        public void UpdateButtonStates()
        {
            _btnBack.Enabled = CanNavigateBack;
            _btnForward.Enabled = CanNavigateForward;
            if (OnChangeToolTipBack != null) _btnBack.ToolTip = OnChangeToolTipBack(PeekBack());
            if (OnChangeToolTipForward != null) _btnForward.ToolTip = OnChangeToolTipForward(PeekForward());
        }
    }
}