// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using Barotrauma;
using Microsoft.Xna.Framework;

namespace SOS.GUI
{
    /// <summary>
    /// A tabbed interface container for displaying multiple tabs, each handling a specific type of item.
    /// </summary>
    /// <typeparam name="T">The type of item that tabs can handle.</typeparam>
    /// <remarks>
    /// Manages a list of <see cref="ITab{T}"/> instances, providing a button bar for tab selection
    /// and a content area for the active tab. Tabs are filtered by their <see cref="ITab{T}.CanHandle"/> method.
    /// </remarks>
    public class GUITab<T> : GUIFrame, IDisposable
    {
        /// <summary>
        /// The layout group arranging the button area and content area vertically.
        /// </summary>
        private readonly GUILayoutGroup _verticalLayout;
        /// <summary>
        /// The list box containing tab buttons.
        /// </summary>
        private readonly GUIListBox _buttonArea;

        /// <summary>
        /// The content area where the active tab's UI is displayed.
        /// </summary>
        private readonly GUIFrame _contentArea;

        /// <summary>
        /// The list of registered tabs.
        /// </summary>
        private readonly List<ITab<T>> tabs = [];

        /// <summary>
        /// Gets the currently active tab, or null if no tab is selected.
        /// </summary>
        public ITab<T>? ActiveTab { get; private set; }

        /// <summary>
        /// Event invoked when the active tab changes.
        /// </summary>
        /// <remarks>
        /// The parameter is the newly selected tab.
        /// </remarks>
        public Action<ITab<T>>? OnTabSelected;

        /// <summary>
        /// The currently selected item being displayed in the active tab.
        /// </summary>
        private T? _currentTarget;

        /// <summary>
        /// Action invoked when a primary interaction occurs on a prefab in the active tab.
        /// </summary>
        public Action<T> OnPrimary;

        /// <summary>
        /// Action invoked when a secondary interaction occurs on a prefab in the active tab.
        /// </summary>
        public Action<T> OnSecondary;

        /// <summary>
        /// Creates a new tabbed interface container.
        /// </summary>
        /// <param name="rectT">The rectangle transform for positioning and sizing.</param>
        /// <param name="onPrimary">Action to invoke on primary interaction with a tab item.</param>
        /// <param name="onSecondary">Action to invoke on secondary interaction with a tab item.</param>
        /// <remarks>
        /// Initializes a vertical layout with a button area (8% height) and content area (92% height).
        /// The button area is a horizontal list box with 32px fixed height for tab buttons.
        /// </remarks>
        public GUITab(RectTransform rectT, Action<T> onPrimary, Action<T> onSecondary) : base(rectT, style: null)
        {
            CanBeFocused = false;
            OnPrimary = onPrimary;
            OnSecondary = onSecondary;

            _verticalLayout = new GUILayoutGroup(new RectTransform(Vector2.One, RectTransform))
            {
                Stretch = true,
                CanBeFocused = false
            };

            _buttonArea = new GUIListBox(new RectTransform(new Vector2(1f, 0.08f), _verticalLayout.RectTransform), isHorizontal: true, style: null)
            {
                Spacing = 5,
                Padding = new Vector4(5, 0, 5, 0),
                CanBeFocused = true
            };
            _buttonArea.RectTransform.MinSize = new Point(0, 32);
            _buttonArea.RectTransform.MaxSize = new Point(int.MaxValue, 32);

            _contentArea = new GUIFrame(new RectTransform(new Vector2(1f, 0.92f), _verticalLayout.RectTransform), style: null)
            {
                CanBeFocused = false
            };
        }

        /// <summary>
        /// Registers a tab with the tab container.
        /// </summary>
        /// <param name="tab">The tab to register.</param>
        /// <remarks>
        /// Calls <see cref="ITab{T}.Init"/> with the content area, then adds the tab to the internal list.
        /// If initialization throws an exception, it is caught and logged via <see cref="Logger"/>.
        /// </remarks>
        public void RegisterTab(ITab<T> tab)
        {
            try
            {
                tab.Init(_contentArea);
                tabs.Add(tab);
            }
            catch (Exception ex)
            {
                Logger.LogReleaseError(ex.Message);
                Logger.LogDebugError(ex.StackTrace ?? ex.Message);
            }
        }

        /// <summary>
        /// Updates the tab list for a new target item, filtering tabs by their <see cref="ITab{T}.CanHandle"/> method.
        /// </summary>
        /// <param name="target">The new target item to display.</param>
        /// <remarks>
        /// Clears the button area and rebuilds it with tabs that can handle the target.
        /// If the current active tab can't handle the new target, the first valid tab is selected.
        /// If there's only one valid tab, the button area is hidden and the content area fills the full height.
        /// </remarks>
        public void UpdateTabs(T target)
        {
            _currentTarget = target;

            _buttonArea.Content.ClearChildren();
            List<ITab<T>> validTabs = [.. tabs.Where(t => t.CanHandle(target))];

            if (ActiveTab == null || !validTabs.Contains(ActiveTab))
                ActiveTab = validTabs.FirstOrDefault();

            if (validTabs.Count > 1)
            {
                _buttonArea.Visible = true;
                _buttonArea.RectTransform.MinSize = new Point(0, 32);
                _buttonArea.RectTransform.MaxSize = new Point(int.MaxValue, 32);
                _contentArea.RectTransform.RelativeSize = new Vector2(1f, 0.92f);

                foreach (var tab in validTabs)
                    _ = tab.CreateTabButton(tab.TabName, _buttonArea.Content.RectTransform, tab == ActiveTab, () => SelectTab(tab), tab.ToolTip);

                _buttonArea.RecalculateChildren();
            }
            else
            {
                _buttonArea.Visible = false;
                _buttonArea.RectTransform.MinSize = Point.Zero;
                _buttonArea.RectTransform.MaxSize = Point.Zero;
                _contentArea.RectTransform.RelativeSize = Vector2.One;
            }

            _verticalLayout.Recalculate();
            RefreshTabContent();
        }

        /// <summary>
        /// Attempts to select a tab by its identifier.
        /// </summary>
        /// <param name="tabId">The identifier of the tab to select.</param>
        /// <returns><c>true</c> if the tab was found and selected; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// Returns <c>false</c> if there is no current target, the tab ID is not found, or the tab
        /// cannot handle the current target.
        /// </remarks>
        public bool TrySelectTab(string tabId)
        {
            if (_currentTarget == null) return false;
            var tab = tabs.FirstOrDefault(t => t.Id == tabId);
            if (tab == null) return false;
            if (!tab.CanHandle(_currentTarget)) return false;
            return SelectTab(tab);
        }

        /// <summary>
        /// Attempts to select a specific tab instance.
        /// </summary>
        /// <param name="tab">The tab to select.</param>
        /// <returns><c>true</c> if the tab was found and selected; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// Returns <c>false</c> if the tab is not registered, or if it cannot handle the current target.
        /// </remarks>
        public bool TrySelectTab(ITab<T> tab)
        {
            if (!tabs.Contains(tab)) return false;
            if (_currentTarget != null && !tab.CanHandle(_currentTarget)) return false;
            return SelectTab(tab);
        }

        /// <summary>
        /// Selects the specified tab as the active tab.
        /// </summary>
        /// <param name="tab">The tab to select.</param>
        /// <returns><c>true</c> if the tab was selected (or was already active).</returns>
        /// <remarks>
        /// If the tab is already active, returns <c>true</c> immediately.
        /// Otherwise, sets the tab as active, invokes <see cref="OnTabSelected"/>, rebuilds the button
        /// area with the new active state, and refreshes the tab content.
        /// </remarks>
        public bool SelectTab(ITab<T> tab)
        {
            if (ActiveTab == tab) return true;

            ActiveTab = tab;
            OnTabSelected?.Invoke(tab);
            if (_currentTarget != null)
            {
                var validTabs = tabs.Where(t => t.CanHandle(_currentTarget));
                _buttonArea.Content.ClearChildren();
                if (validTabs.Count() > 1)
                {
                    foreach (var t in validTabs)
                        _ = t.CreateTabButton(t.TabName, _buttonArea.Content.RectTransform, t == ActiveTab, () => SelectTab(t), t.ToolTip);
                    _buttonArea.RecalculateChildren();
                }
                RefreshTabContent();
            }
            else
            {
                RefreshTabContent();
            }
            return true;
        }

        /// <summary>
        /// Refreshes the visible content of all tabs, showing the active tab and hiding others.
        /// </summary>
        /// <remarks>
        /// Calls <see cref="ITab{T}.Show"/> on the active tab and <see cref="ITab{T}.Hide"/> on all other tabs.
        /// </remarks>
        private void RefreshTabContent()
        {
            if (_currentTarget == null) return;

            foreach (var tab in tabs)
            {
                if (tab == ActiveTab)
                    tab.Show(_currentTarget, OnPrimary, OnSecondary);
                else
                    tab.Hide();
            }
        }

        /// <summary>
        /// Disposes the tab container and all registered tabs.
        /// </summary>
        /// <remarks>
        /// Clears the button area, disposes all tabs that implement <see cref="IDisposable"/>,
        /// clears the tab list, and suppresses finalization.
        /// </remarks>
        public void Dispose()
        {
            _buttonArea.Content.ClearChildren();
            foreach (var tab in tabs)
                if (tab is IDisposable d) d.Dispose();
            tabs.Clear();
            GC.SuppressFinalize(this);
        }

        /// <summary>
        /// Finalizer that calls <see cref="Dispose"/>.
        /// </summary>
        ~GUITab() => Dispose();
    }
}