// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using Barotrauma;
using Microsoft.Xna.Framework;

namespace SOS.GUI
{
    /// <summary>
    /// A tabbed interface container for displaying multiple tabs, each handling a specific type of item.
    /// </summary>
    /// <typeparam name="T">The type of item that tabs can handle.</typeparam>
    /// <remarks>
    /// Manages a list of <see cref="ITab{T}"/> instances, providing a button bar for tab selection
    /// and a content area for the active tab. Tabs are filtered by their <see cref="ITab{T}.CanHandle"/> method.
    /// Each tab button is created once in <see cref="RegisterTab"/> and stored alongside its tab.
    /// </remarks>
    public class GUITab<T> : GUIFrame, IDisposable
    {
        /// <summary>
        /// The layout group arranging the button area and content area vertically.
        /// </summary>
        private readonly GUILayoutGroup _verticalLayout;
        /// <summary>
        /// The list box containing tab buttons.
        /// </summary>
        private readonly GUIListBox _buttonArea;

        /// <summary>
        /// The content area where the active tab's UI is displayed.
        /// </summary>
        private readonly GUIFrame _contentArea;

        /// <summary>
        /// The registered tabs alongside their content frames and buttons.
        /// </summary>
        private readonly List<(ITab<T> Tab, GUIFrame Content, GUIButton Button)> tabs = [];

        /// <summary>
        /// Gets the currently active tab, or null if no tab is selected.
        /// </summary>
        public ITab<T>? ActiveTab { get; private set; }

        /// <summary>
        /// Event invoked when the active tab changes.
        /// </summary>
        /// <remarks>
        /// The parameter is the newly selected tab.
        /// </remarks>
        public Action<ITab<T>>? OnTabSelected;

        /// <summary>
        /// The currently selected item being displayed in the active tab.
        /// </summary>
        private T? _currentTarget;

        /// <summary>
        /// Creates a new tabbed interface container.
        /// </summary>
        /// <param name="rectT">The rectangle transform for positioning and sizing.</param>
        /// <remarks>
        /// Initializes a vertical layout with a button area (8% height) and content area (92% height).
        /// The button area is a horizontal list box with 32px fixed height for tab buttons.
        /// </remarks>
        public GUITab(RectTransform rectT) : base(rectT, style: null)
        {
            CanBeFocused = false;

            _verticalLayout = new GUILayoutGroup(new RectTransform(Vector2.One, RectTransform))
            {
                Stretch = true,
                CanBeFocused = false
            };

            _buttonArea = new GUIListBox(new RectTransform(new Vector2(1f, 0.08f), _verticalLayout.RectTransform), isHorizontal: true, style: null)
            {
                Spacing = 5,
                Padding = new Vector4(5, 0, 5, 0),
                CanBeFocused = true
            };
            _buttonArea.RectTransform.MinSize = new Point(0, 32);
            _buttonArea.RectTransform.MaxSize = new Point(int.MaxValue, 32);

            _contentArea = new GUIFrame(new RectTransform(new Vector2(1f, 0.92f), _verticalLayout.RectTransform), style: null)
            {
                CanBeFocused = false
            };
        }

        /// <summary>
        /// Registers a tab with the tab container.
        /// </summary>
        /// <param name="tab">The tab to register.</param>
        /// <remarks>
        /// Calls <see cref="ITab{T}.Init"/> with the content area, creates its button a single time via
        /// <see cref="ITab{T}.CreateTabButton"/>, wires the click handler once, then stores both in the internal list.
        /// If initialization throws an exception, it is caught and logged via <see cref="Logger"/> and the tab is ignored.
        /// </remarks>
        public void RegisterTab(ITab<T> tab)
        {
            var content = new GUIFrame(new RectTransform(Vector2.One, _contentArea.RectTransform), style: null)
            {
                Visible = false,
                CanBeFocused = false
            };
            GUIButton? button = null;
            try
            {
                button = tab.CreateTabButton(_buttonArea.Content.RectTransform, tab.Id);
                button.UserData = tab;
                button.OnClicked += WhenClicked;

                tab.Init(content, button);

                tabs.Add((tab, content, button));

                //if (_currentTarget != null && tab.CanHandle(_currentTarget))
                //    tab.Update(_currentTarget);
                //_buttonArea.RecalculateChildren();
            }
            catch (Exception ex)
            {
                try
                {
                    _contentArea.RemoveChild(content);
                    _buttonArea.Content.RemoveChild(button);
                    if (button != null) tabs.Remove((tab, content, button));
                }
                catch (Exception ex2) { Logger.LogError($"Error when trying to remove conflicted `ITab<{typeof(T).Name}>` of Type {tab.GetType().FullOrName()}.\n {ex2.StackTrace}"); }
                Logger.LogWarning($"Exception as ocurred when called 'RegisterTab' in tab '{tab.Id}', this tab was ignored to prevent more errors...\n {ex.Message}");
                Logger.LogDebugError(ex.StackTrace);
            }
        }

        private bool WhenClicked(GUIButton _, object userData)
        {
            if (userData is ITab<T> tab) SelectTab(tab);
            else return false;
            return true;
        }

        /// <summary>
        /// Gets the button stored for the given tab.
        /// </summary>
        /// <param name="tab">The tab whose button to retrieve.</param>
        /// <returns>The stored <see cref="GUIButton"/>; or <c>null</c> if the tab is not registered.</returns>
        public GUIButton? GetTabButton(ITab<T> tab)
        {
            foreach (var (t, _, b) in tabs)
                if (t == tab) return b;
            return null;
        }

        /// <summary>
        /// Gets the button stored for the tab matching the given identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the tab (see <see cref="IIdentifier.Id"/>).</param>
        /// <returns>The stored <see cref="GUIButton"/>; or <c>null</c> if no tab matches <paramref name="id"/>.</returns>
        public GUIButton? GetTabButton(string id)
        {
            foreach (var (t, _, b) in tabs)
                if (t.Id == id) return b;
            return null;
        }

        /// <summary>
        /// Updates the tab list for a new target item, filtering tabs by their <see cref="ITab{T}.CanHandle"/> method.
        /// </summary>
        /// <param name="target">The new target item to display.</param>
        /// <remarks>
        /// Toggles stored button visibility for tabs that can handle the target instead of rebuilding buttons.
        /// If the current active tab can't handle the new target, the first valid tab is selected.
        /// If there's only one valid tab, the button area is hidden and the content area fills the full height.
        /// </remarks>
        public void UpdateTabs(T target)
        {
            bool sameTarget = ReferenceEquals(target, _currentTarget);
            _currentTarget = target;

            int countValidTabs = 0;
            (ITab<T> tab, GUIFrame content, GUIButton button)? first = null;
            bool activeStillValid = false;

            foreach (var (tab, content, button) in tabs)
            {
                if (tab.CanHandle(target))
                {
                    first ??= (tab, content, button);
                    bool isActive = tab == ActiveTab;
                    activeStillValid |= isActive;
                    content.Visible = isActive;
                    button.Selected = isActive;
                    button.Visible = true;
                    countValidTabs++;
                }
                else
                {
                    button.Selected = false;
                    button.Visible = false;
                    content.Visible = false;
                }
            }

            if (!activeStillValid)
            {
                if (first.HasValue)
                {
                    var (tab, content, button) = first.Value;
                    ActiveTab = tab;
                    content.Visible = true;
                    button.Selected = true;
                }
                else ActiveTab = null;
            }

            if (!sameTarget && ActiveTab != null)
            {
                try
                {
                    ActiveTab.Update(target);
                }
                catch (Exception ex)
                {
                    Logger.LogWarning($"Exception as ocurred when called 'Update' in tab '{ActiveTab.Id}', its content was hidden to prevent more errors...\n {ex.Message}");
                    Logger.LogDebugError(ex.StackTrace);
                    foreach (var (tab, content, _) in tabs)
                        if (tab == ActiveTab) content.Visible = false;
                }
            }

            if (countValidTabs > 1)
            {
                _buttonArea.Visible = true;
                _buttonArea.RectTransform.MinSize = new Point(0, 32);
                _buttonArea.RectTransform.MaxSize = new Point(int.MaxValue, 32);
                _contentArea.RectTransform.RelativeSize = new Vector2(1f, 0.92f);
            }
            else
            {
                _buttonArea.Visible = false;
                _buttonArea.RectTransform.MinSize = Point.Zero;
                _buttonArea.RectTransform.MaxSize = Point.Zero;
                _contentArea.RectTransform.RelativeSize = Vector2.One;
            }

            _verticalLayout.Recalculate();
        }

        /// <summary>
        /// Attempts to select a tab by its identifier.
        /// </summary>
        /// <param name="tabId">The identifier of the tab to select.</param>
        /// <returns><c>true</c> if the tab was found and selected; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// Returns <c>false</c> if there is no current target, the tab ID is not found, or the tab
        /// cannot handle the current target.
        /// </remarks>
        public bool TrySelectTab(string tabId)
        {
            if (_currentTarget == null) return false;
            ITab<T>? tab = null;
            foreach (var (t, _, _) in tabs)
                if (t.Id == tabId) { tab = t; break; }
            if (tab == null) return false;
            if (!tab.CanHandle(_currentTarget)) return false;
            return SelectTab(tab);
        }

        /// <summary>
        /// Attempts to select a specific tab instance.
        /// </summary>
        /// <param name="tab">The tab to select.</param>
        /// <returns><c>true</c> if the tab was found and selected; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// Returns <c>false</c> if the tab is not registered, or if it cannot handle the current target.
        /// </remarks>
        public bool TrySelectTab(ITab<T> tab)
        {
            bool registered = false;
            foreach (var (t, _, _) in tabs)
                if (t == tab) { registered = true; break; }
            if (!registered) return false;
            if (_currentTarget != null && !tab.CanHandle(_currentTarget)) return false;
            return SelectTab(tab);
        }

        /// <summary>
        /// Selects the specified tab as the active tab.
        /// </summary>
        /// <param name="tab">The tab to select.</param>
        /// <returns><c>true</c> if the tab was selected (or was already active).</returns>
        /// <remarks>
        /// If the tab is already active, returns <c>true</c> immediately.
        /// Otherwise, sets the tab as active, invokes <see cref="OnTabSelected"/>, flips the stored
        /// button selection states, and refreshes the tab content. Buttons are never rebuilt here.
        /// </remarks>
        public bool SelectTab(ITab<T> tab)
        {
            if (ActiveTab == tab) return true;

            ActiveTab = tab;
            OnTabSelected?.Invoke(tab);
            foreach (var (t, c, b) in tabs)
            {
                c.Visible = (t == ActiveTab);
                b.Selected = (t == ActiveTab);
            }
            if (_currentTarget != null)
            {
                try
                {
                    tab.Update(_currentTarget);
                }
                catch (Exception ex)
                {
                    Logger.LogWarning($"Exception as ocurred when called 'Update' in tab '{tab.Id}', its content was hidden to prevent more errors...\n {ex.Message}");
                    Logger.LogDebugError(ex.StackTrace);
                    foreach (var (t, c, _) in tabs)
                        if (t == tab) c.Visible = false;
                }
            }
            _verticalLayout.Recalculate();
            return true;
        }

        /// <summary>
        /// Disposes the tab container and all registered tabs.
        /// </summary>
        /// <remarks>
        /// Clears the button area, disposes all tabs that implement <see cref="IDisposable"/>,
        /// clears the tab list, and suppresses finalization.
        /// </remarks>
        public void Dispose()
        {
            _buttonArea.Content.ClearChildren();
            _contentArea.ClearChildren();
            foreach (var (tab, _, _) in tabs)
                if (tab is IDisposable d) d.Dispose();
            tabs.Clear();
            ActiveTab = null;
            _currentTarget = default;
            GC.SuppressFinalize(this);
        }

        /// <summary>
        /// Finalizer that calls <see cref="Dispose"/>.
        /// </summary>
        ~GUITab() => Dispose();
    }
}