// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using Barotrauma;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

using BGUI = Barotrauma.GUI;

namespace SOS.GUI
{
    /// <summary>
    /// A zoomable, scrollable rich-text viewer with syntax highlighting support.
    /// </summary>
    /// <remarks>
    /// Extends <see cref="GUITextBlock"/> with horizontal and vertical scroll bars, zoom functionality
    /// (Ctrl+Mouse Wheel), and horizontal scrolling (Shift+Mouse Wheel). Supports context menus
    /// via the <see cref="ContentMenu"/> event on right-click.
    /// </remarks>
    public class GUITextViewer : GUITextBlock
    {
        /// <summary>
        /// Gets the horizontal scroll bar used for scrolling wide content.
        /// </summary>
        public GUIScrollBar HorizontalScrollBar { get; private set; }

        /// <summary>
        /// Gets the vertical scroll bar used for scrolling tall content.
        /// </summary>
        public GUIScrollBar VerticalScrollBar { get; private set; }

        /// <summary>
        /// Indicates whether the scroll bars need to be recalculated on the next update.
        /// </summary>
        /// <remarks>
        /// Set to <c>true</c> when the content size, scale, or view rect changes.
        /// </remarks>
        public bool scrollBarsNeedsRecalculation = true;

        /// <summary>
        /// Stores the original padding from the applied style, used for recalculating layout when scroll bars appear.
        /// </summary>
        private Vector4 originalPadding;

        /// <summary>
        /// Tracks whether the original padding has been captured from the style.
        /// </summary>
        private bool paddingInitialized = false;

        /// <summary>
        /// Minimum text scale factor (40%).
        /// </summary>
        private const float MinScale = 0.4f;

        /// <summary>
        /// Maximum text scale factor (200%).
        /// </summary>
        private const float MaxScale = 2.0f;

        /// <summary>
        /// Scale increment/decrement step for zoom operations.
        /// </summary>
        private const float ZoomStep = 0.05f;

        /// <summary>
        /// Event invoked when the text scale changes.
        /// </summary>
        /// <remarks>
        /// The parameter is the new scale factor.
        /// </remarks>
        public Action<float>? OnScaleChanged;

        /// <summary>
        /// Event invoked when the context menu is requested (right-click on the viewer).
        /// </summary>
        /// <remarks>
        /// The parameter is the <see cref="GUITextViewer"/> instance that was clicked.
        /// </remarks>
        public Action<GUITextViewer>? ContentMenu;

        /// <summary>
        /// Gets the thickness of the scroll bars, scaled by the GUI scale factor.
        /// </summary>
        /// <returns>The scroll bar thickness in pixels, capped at 1/3 of the view height.</returns>
        /// <remarks>
        /// The thickness is the average of the desired base size (20px) and the scaled size,
        /// ensuring readability at different UI scales.
        /// </remarks>
        private int ScrollBarThickness
        {
            get
            {
                float desiredSize = 20.0f;
                float scaledSize = desiredSize * BGUI.Scale;
                return (int)Math.Min((desiredSize + scaledSize) / 2.0f, Rect.Height / 3);
            }
        }

        /// <summary>
        /// Creates a new <see cref="GUITextViewer"/> with the specified rectangle, text, font, and style.
        /// </summary>
        /// <param name="rectT">The rectangle transform for positioning and sizing.</param>
        /// <param name="text">The initial text content. Defaults to empty string.</param>
        /// <param name="font">The font to use for rendering text. Defaults to null (uses style default).</param>
        /// <param name="style">The GUI style name. Defaults to "InnerFrame".</param>
        /// <remarks>
        /// Initializes the viewer with overflow clipping, no text wrapping, and focus enabled.
        /// Creates horizontal and vertical scroll bars with the "GUIScrollBar" style.
        /// Subscribes to size and scale changes to trigger scroll bar recalculation.
        /// </remarks>
        public GUITextViewer(RectTransform rectT, string text = "", GUIFont? font = null, string style = "InnerFrame")
            : base(rectT, text, font: font, textAlignment: Alignment.TopLeft, wrap: false, style: style)
        {
            OverflowClip = true;
            Wrap = false;
            CanBeFocused = true;

            HorizontalScrollBar = new GUIScrollBar(new RectTransform(Vector2.One, rectT), isHorizontal: true, style: "GUIScrollBar", color: Color.White);
            VerticalScrollBar = new GUIScrollBar(new RectTransform(Vector2.One, rectT), isHorizontal: false, style: "GUIScrollBar", color: Color.White);

            RectTransform.SizeChanged += () => scrollBarsNeedsRecalculation = true;
            RectTransform.ScaleChanged += () => scrollBarsNeedsRecalculation = true;

            Enabled = true;
        }

        /// <summary>
        /// Applies a GUI component style and captures the original padding for scroll bar layout calculations.
        /// </summary>
        /// <param name="componentStyle">The style to apply. If null, the method returns without changes.</param>
        /// <remarks>
        /// Captures the style's padding as the original padding for later use in scroll bar layout.
        /// Ensures text color is visible (defaults to white if transparent or black).
        /// Ensures background color is visible (defaults to semi-transparent black if too transparent).
        /// Marks scroll bars as needing recalculation.
        /// </remarks>
        public override void ApplyStyle(GUIComponentStyle componentStyle)
        {
            if (componentStyle == null) return;
            base.ApplyStyle(componentStyle);

            originalPadding = componentStyle.Padding;
            paddingInitialized = true;

            if (HorizontalScrollBar != null && VerticalScrollBar != null)
            {
                if (TextColor.A == 0 || TextColor == Color.Black) TextColor = Color.White;
                if (Color.A < 100) Color = Color.Black * 0.6f;
                scrollBarsNeedsRecalculation = true;
            }
        }

        /// <summary>
        /// Gets or sets the rich text content, marking scroll bars for recalculation when changed.
        /// </summary>
        /// <remarks>
        /// When the text is set to a new value, <see cref="scrollBarsNeedsRecalculation"/> is set to <c>true</c>
        /// to trigger a scroll bar layout update on the next frame.
        /// </remarks>
        public new RichString Text
        {
            get => base.Text;
            set
            {
                if (base.Text != value)
                {
                    base.Text = value;
                    scrollBarsNeedsRecalculation = true;
                }
            }
        }

        /// <summary>
        /// Updates the visibility, position, and size of the scroll bars based on content and view size.
        /// </summary>
        /// <remarks>
        /// Calculates whether horizontal and vertical scroll bars are needed based on the scaled text size
        /// versus the available view area. Adjusts the component's padding to account for scroll bar space.
        /// Positions scroll bars at the bottom (horizontal) and right (vertical) edges of the content area.
        /// Sets the scroll bar thumb size (BarSize) proportional to the view size / content size ratio.
        /// </remarks>
        private void UpdateScrollbars()
        {
            scrollBarsNeedsRecalculation = false;
            if (HorizontalScrollBar == null || VerticalScrollBar == null) return;

            int sbSize = ScrollBarThickness;
            Vector4 currentPadding = paddingInitialized ? originalPadding : Padding;

            float availableWidth = Rect.Width - currentPadding.X - currentPadding.Z;
            float availableHeight = Rect.Height - currentPadding.Y - currentPadding.W;
            float actualWidth = TextSize.X * TextScale;
            float actualHeight = TextSize.Y * TextScale;

            bool needH = actualWidth > availableWidth;
            bool needV = actualHeight > availableHeight;

            if (needH && (actualHeight > (availableHeight - sbSize))) needV = true;
            if (needV && (actualWidth > (availableWidth - sbSize))) needH = true;

            Padding = new Vector4(
                currentPadding.X,
                currentPadding.Y,
                currentPadding.Z + (needV ? sbSize : 0),
                currentPadding.W + (needH ? sbSize : 0)
            );

            HorizontalScrollBar.Visible = needH;
            HorizontalScrollBar.Enabled = needH;
            if (needH)
            {
                HorizontalScrollBar.RectTransform.Resize(new Point((int)(Rect.Width - currentPadding.X - currentPadding.Z - (needV ? sbSize : 0)), sbSize));
                HorizontalScrollBar.RectTransform.SetPosition(Anchor.BottomLeft);
                HorizontalScrollBar.RectTransform.AbsoluteOffset = new Point((int)currentPadding.X, (int)currentPadding.W);
                HorizontalScrollBar.BarSize = Math.Max(0.1f, (Rect.Width - Padding.X - Padding.Z) / actualWidth);
            }

            VerticalScrollBar.Visible = needV;
            VerticalScrollBar.Enabled = needV;
            if (needV)
            {
                VerticalScrollBar.RectTransform.Resize(new Point(sbSize, (int)(Rect.Height - currentPadding.Y - currentPadding.W - (needH ? sbSize : 0))));
                VerticalScrollBar.RectTransform.SetPosition(Anchor.TopRight);
                VerticalScrollBar.RectTransform.AbsoluteOffset = new Point((int)currentPadding.Z, (int)currentPadding.Y);
                VerticalScrollBar.BarSize = Math.Max(0.1f, (Rect.Height - Padding.Y - Padding.W) / actualHeight);
            }
        }

        /// <summary>
        /// Updates the viewer, handling scroll bar recalculation, zoom, scrolling, and context menu interactions.
        /// </summary>
        /// <param name="deltaTime">Time elapsed since the last update in seconds.</param>
        /// <remarks>
        /// <list type="bullet">
        /// <item>Recalculates scroll bars if needed.</item>
        /// <item>Handles right-click to invoke <see cref="ContentMenu"/>.</item>
        /// <item>Handles Ctrl+Middle Mouse to reset zoom to 0.9x.</item>
        /// <item>Handles Ctrl+Mouse Wheel for zoom (clamped to <c>MinScale</c> and <c>MaxScale</c>).</item>
        /// <item>Handles Shift+Mouse Wheel for horizontal scrolling.</item>
        /// <item>Handles Mouse Wheel for vertical scrolling.</item>
        /// <item>Updates <c>TextOffset</c> based on scroll bar positions.</item>
        /// </list>
        /// </remarks>
        public override void Update(float deltaTime)
        {
            if (scrollBarsNeedsRecalculation) UpdateScrollbars();
            base.Update(deltaTime);

            if (!Visible) return;

            if (BGUI.IsMouseOn(this))
            {
                if (ContentMenu != null && PlayerInput.SecondaryMouseButtonClicked())
                {
                    ContentMenu(this);
                }

                if (PlayerInput.IsCtrlDown() && PlayerInput.MidButtonClicked())
                {
                    TextScale = 0.9f;
                    scrollBarsNeedsRecalculation = true;
                    OnScaleChanged?.Invoke(TextScale);
                    return;
                }

                if (PlayerInput.ScrollWheelSpeed != 0)
                {
                    if (PlayerInput.IsCtrlDown())
                    {
                        float oldScale = TextScale;
                        TextScale = MathHelper.Clamp(TextScale + Math.Sign(PlayerInput.ScrollWheelSpeed) * ZoomStep, MinScale, MaxScale);

                        if (Math.Abs(oldScale - TextScale) > 0.001f)
                        {
                            scrollBarsNeedsRecalculation = true;
                            OnScaleChanged?.Invoke(TextScale);
                        }
                    }
                    else if (PlayerInput.IsShiftDown() && HorizontalScrollBar.Enabled)
                    {
                        HorizontalScrollBar.BarScroll -= Math.Sign(PlayerInput.ScrollWheelSpeed) * 0.075f;
                    }
                    else if (VerticalScrollBar.Enabled)
                    {
                        VerticalScrollBar.BarScroll -= Math.Sign(PlayerInput.ScrollWheelSpeed) * 0.1f;
                    }
                }
                float maxScrollX = Math.Max(0, (TextSize.X * TextScale) - (Rect.Width - Padding.X - Padding.Z));
                float maxScrollY = Math.Max(0, (TextSize.Y * TextScale) - (Rect.Height - Padding.Y - Padding.W));

                TextOffset = new Vector2(
                    (float)Math.Round(-HorizontalScrollBar.BarScroll * maxScrollX),
                    (float)Math.Round(-VerticalScrollBar.BarScroll * maxScrollY)
                );
            }
        }

        /// <summary>
        /// Draws the text viewer and its visible scroll bars.
        /// </summary>
        /// <param name="spriteBatch">The sprite batch to draw with.</param>
        /// <remarks>
        /// Draws the base text block content, then manually draws the horizontal and vertical scroll bars
        /// if they are visible. Uses <see cref="GUIComponent.DrawManually"/> for scroll bars to ensure
        /// they are rendered on top of the text content.
        /// </remarks>
        public override void Draw(SpriteBatch spriteBatch)
        {
            if (!Visible) return;

            base.Draw(spriteBatch);

            if (HorizontalScrollBar.Visible) HorizontalScrollBar.DrawManually(spriteBatch, alsoChildren: true, recursive: true);
            if (VerticalScrollBar.Visible) VerticalScrollBar.DrawManually(spriteBatch, alsoChildren: true, recursive: true);
        }

        /// <summary>
        /// Sets the alpha (transparency) of the text viewer and its scroll bars.
        /// </summary>
        /// <param name="a">The alpha value (0.0 = fully transparent, 1.0 = fully opaque).</param>
        /// <remarks>
        /// Propagates the alpha to both horizontal and vertical scroll bars if they exist.
        /// </remarks>
        public override void SetAlpha(float a)
        {
            base.SetAlpha(a);
            HorizontalScrollBar?.SetAlpha(a);
            VerticalScrollBar?.SetAlpha(a);
        }
    }
}