// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using System.ComponentModel;
using Barotrauma;
using Microsoft.Xna.Framework;
using SOS.Prefabs;

namespace SOS
{
    #region AutoRegister


    /// <summary>
    /// Attribute used to automatically register mod components (sections, tabs, configs, prefab providers, window profiles)
    /// during first SOS window opening via <see cref="IPluginManagementService"/>.
    /// </summary>
    /// <param name="id">Optional unique identifier. If <c>null</c>, the type's full name is used.</param>
    /// <param name="order">Registration order. Lower values appear first in sorted output. Defaults to 0.0.</param>
    /// <param name="active">Whether the component is initially active. Defaults to true.</param>
    /// <remarks>
    /// When a type is decorated with this attribute, the SDK will discover it during the <see cref="API.Initialize"/>
    /// call and register it in the appropriate <see cref="SortedFactory{T}"/> registry using the attribute's values.
    /// </remarks>
    [AttributeUsage(AttributeTargets.Class)]
    public class AutoRegisterAttribute : Attribute
    {
        public readonly string? Id;
        public readonly double Order;
        public readonly bool Active;
        public AutoRegisterAttribute(string? id = null, double order = 0.0, bool active = true)
        {
            Id = id;
            Order = order;
            Active = active;
        }
    }

    #endregion

    #region Interfaces

    /// <summary>
    /// Provides a unique identifier for mod components.
    /// </summary>
    /// <remarks>
    /// The default implementation returns the type's full name (<see cref="Type.FullName"/>) or type name (<see cref="Type.Name"/>)
    /// if the full name is null. Implementers can override this property to provide a custom identifier string.
    /// </remarks>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public interface IIdentifier
    {
        string Id => GetType().FullOrName();
    }

    /// <summary>
    /// Defines a tab interface for modular UI tab pages.
    /// </summary>
    /// <typeparam name="T">The type of object this tab can handle.</typeparam>
    /// <remarks>
    /// The tab lifecycle methods are:
    /// <list type="bullet">
    /// <item><term><see cref="Get_TabName"/>:</term><description>Getter to tab showed Name.</description></item>
    /// <item><term><see cref="Get_ToolTip"/>:</term><description>Getter to tab tooltip to tab button.</description></item>
    /// <item><term><see cref="CanHandle"/>:</term><description>Called when the tab needs evaluate if will be showed or not in tab. True/False.</description></item>
    /// <item><term><see cref="Init"/>:</term><description>Called once when the tab is initialized with the content container.</description></item>
    /// <item><term><see cref="Show"/>:</term><description>Called when the tab becomes the active tab for a given item.</description></item>
    /// <item><term><see cref="Hide"/>:</term><description>Called when the tab is no longer the active tab.</description></item>
    /// <item><term><see cref="CreateTabButton"/>:</term><description>Called when needs to draw tab button, cam redefine how this button is showed.(Optional)</description></item>
    /// </list>
    /// </remarks>
    [EditorBrowsable(EditorBrowsableState.Never), DefaultClass<TabDefaults>]
    public interface ITab<T> : IIdentifier
    {
        string TabName { get; }

        string ToolTip => "";
        bool CanHandle(T item);
        void Init(GUIComponent contentContainer);
        void Show(T item, Action<T> onPrimary, Action<T> onSecondary);
        void Hide();

        GUIButton CreateTabButton(string tabName, RectTransform parent, bool isActive, Action onClick, string toolTip = "")
            => TabDefaults.CreateTabButton(tabName, parent, isActive, onClick, toolTip);
    }

    /// <summary>
    /// Defines a modular inspector section that extracts and renders metadata for a selected prefab
    /// in the S.O.S. information sidebar.
    /// </summary>
    /// <remarks>
    /// Implementations are registered via <see cref="AutoRegisterAttribute"/> and are treated a rendering service
    /// cached in the SDK registry.
    /// </remarks>
    public interface ISOSStatSection
    {
        /// <summary>
        /// Analyzes and renders the specified prefab into the GUI list container.
        /// </summary>
        /// <param name="contentPanel">The GUI list container to draw into.</param>
        /// <param name="prefab">The prefab to analyze and render.</param>
        /// <param name="onPrimary">Primary click handler for the prefab.</param>
        /// <param name="onSecondary">Secondary click handler for the prefab.</param>
        /// <returns>True if this section has valid data to display; otherwise, false.</returns>
        bool Draw(GUIListBox contentPanel, Prefab prefab, Action<Prefab> onPrimary, Action<Prefab> onSecondary);
    }


    /// <summary>
    /// Extension of <see cref="ITab{T}"/> specifically for <see cref="Prefab"/> items.
    /// </summary>
    /// <remarks>
    /// These Tabs are registered via <see cref="API.RegisterTab"/> and retrieved via <see cref="API.GetTab"/>.
    /// This interface is automatically satisfied when a class implements <see cref="ITab{T}"/> with
    /// <typeparamref name="T"/> = <see cref="Prefab"/>. Tabs of this type appear in the left sidebar browser
    /// for prefab inspection.
    /// </remarks>
    public interface ISOSTab : ITab<Prefab>;

    [DefaultClass<ConfigDefaults>]
    /// <summary>
    /// Defines interface for mod settings with a standard lifecycle.
    /// </summary>
    /// <remarks>
    /// Implementations are registered via <see cref="AutoRegisterAttribute"/> and are managed through the SDK's
    /// configuration system. The default implementation of <see cref="Reset"/> does nothing (<see cref="bool.DrawSettings"/>)
    /// and returns false, indicating no custom settings UI was drawn.
    /// </remarks>
    /// <example>
    /// <code>
    /// [AutoRegister(order: 5.0)]
    /// public class MyConfig : ISOSConfig
    /// {
    ///     public void Load() { /* load settings */ }
    ///     public void Save() { /* save settings */ }
    ///     public bool DrawSettings(GUIListBox container)
    ///     {
    ///         // draw custom settings UI
    ///         return true;
    ///     }
    /// }
    /// </code>
    /// </example>
    public interface ISOSConfig
    {
        void Load();
        void Save();
        void Reset() { }
        bool DrawSettings(GUIListBox container) => false;
    }

    /// <summary>
    /// Filter specification for selecting prefabs in the left sidebar browser.
    /// </summary>
    /// <remarks>
    /// Each field contains a list of terms that are matched against prefab properties using ordinal ignore case comparison.
    /// A prefab matches the filter if all non-empty lists contain the corresponding term.
    /// <list type="bullet">
    /// <item><term>General:</term><description>General search terms matched against name, identifier, and mod name.</description></item>
    /// <item><term>Mod:</term><description>Mod name filter.</description></item>
    /// <item><term>Category:</term><description>Category filter.</description></item>
    /// <item><term>Tag:</term><description>Tag filter.</description></item>
    /// <item><term>Slot:</term><description>Slot filter.</description></item>
    /// <item><term>ID:</term><description>Identifier filter.</description></item>
    /// <item><term>PrefabType:</term><description>Prefab type filter.</description></item>
    /// </list>
    /// </remarks>
    public interface ISOSPrefabFilter
    {
        List<string> General { get; }
        List<string> Mod { get; }
        List<string> Category { get; }
        List<string> Tag { get; }
        List<string> Slot { get; }
        List<string> ID { get; }
        List<string> PrefabType { get; }
    }

    /// <summary>
    /// Defines an extension interface for custom prefab providers in the left sidebar browser.
    /// </summary>
    /// <remarks>
    /// Implementations provide a way for modders to add custom prefabs to the SOS prefab list.
    /// The <see cref="PrefabType"/> property indicates the type of prefab (Item, Affliction, etc.).
    /// The <see cref="GetAll"/> method returns an enumerable of prefab instances matching the applied filter.
    /// <list type="bullet">
    /// <item><term><see cref="PrefabType"/>:</term><description>The type of prefab this provider handles.</description></item>
    /// <item><term><see cref="Header"/>:</term><description>The display header shown in the sidebar browser.</description></item>
    /// <item><term><see cref="GetAll"/>:</term><description>Returns all prefab instances matching the filter.</description></item>
    /// </list>
    /// </remarks>
    public interface ISOSPrefab
    {
        Type PrefabType { get; }
        string Header { get; }
        IEnumerable<Prefab> GetAll(ISOSPrefabFilter filter);

        [DefaultClass<PrefabDefaults>]
        List<ContextMenuOption> BuildContextOptions(Prefab prefab) => PrefabDefaults.BuildContextOptions(prefab);
    }

    /// <summary>
    /// Defines an extension interface for interchangeable visual window layouts.
    /// </summary>
    /// <remarks>
    /// Implementations provide alternative window profile configurations that can be swapped at runtime.
    /// The <see cref="DisplayName"/> and <see cref="Description"/> properties are used for display in the profile selector.
    /// The <see cref="ProfileConfig"/> property provides optional configuration specific to the profile type; by default
    /// it returns <c>null</c>.
    /// <list type="bullet">
    /// <item><term><see cref="Init"/>:</term><description>Called once during profile initialization.</description></item>
    /// <item><term><see cref="Update"/>:</term><description>Called each update cycle to allow profile state updates.</description></item>
    /// </list>
    /// </remarks>
    [DefaultClass<WindowProfileDefaults>]
    public interface ISOSWindowProfile : IIdentifier, IDisposable
    {
        string DisplayName { get; }
        string Description { get; }
        ISOSConfig? ProfileConfig => null;
        void Init();
        void Update();
    }

    #endregion

    #region Default Proxy Classes

    /// <summary>
    /// Default values for ordenable identifier configurations for generic Objects.
    /// </summary>
    internal sealed class IdentifierOrdenableDefaults
    {
        private IdentifierOrdenableDefaults() { }
        public static double Order => 0;
    }

    /// <summary>
    /// Default implementation for tab button creation and tool tip provision for generic Objects.
    /// </summary>
    internal sealed class TabDefaults
    {
        private TabDefaults() { }
        public static string ToolTip => "";
        public static GUIButton CreateTabButton(string tabName, RectTransform parent, bool isActive, Action onClick, string toolTip = "")
        {
            Vector2 textSize = GUIStyle.SmallFont.MeasureString(tabName);
            int width = (int)textSize.X + 24;
            var tabBtn = new GUIButton(new RectTransform(new Point(width, 32), parent) { IsFixedSize = true }, tabName, style: "MainMenuNotificationButton")
            {
                Selected = isActive,
                OnClicked = (_, _) => { onClick(); return true; },
            };
            if (!toolTip.IsNullOrEmpty())
                tabBtn.ToolTip = toolTip;
            return tabBtn;
        }
    }

    /// <summary>
    /// Default implementation for configuration resetting and settings drawing for generic Objects.
    /// </summary>
    internal sealed class ConfigDefaults
    {
        public static void Reset() { }
        public static bool DrawSettings(GUIListBox _) => false;
    }

    /// <summary>
    /// Default implementation for building context menu options for prefabs for generic Objects.
    /// </summary>
    internal sealed class PrefabDefaults
    {
        public static List<ContextMenuOption> BuildContextOptions(Prefab prefab)
        {
            var options = new List<ContextMenuOption>
            {
                new(Texts.Get("sos.context.view_recipes", "View Recipes").Value, isEnabled: true, onSelected: () => API.Emit(CommKeys.SelectTarget, prefab))
            };

            string targetId = prefab.Identifier.Value;
            bool isFav = PrefabHelper.IsFavorite(targetId);
            string favText = isFav ? Texts.Get("sos.context.remove_favorite", "Remove from Favorites").Value : Texts.Get("sos.context.add_favorite", "Add to Favorites").Value;

            options.Add(new ContextMenuOption(favText, true, () => { PrefabHelper.ToggleFavorite(targetId); }));

            return options;
        }
    }

    /// <summary>
    /// Default implementation for profile configuration for generic Objects.
    /// </summary>
    internal sealed class WindowProfileDefaults
    {
        public static ISOSConfig? ProfileConfig => null;
    }

    #endregion
}
