// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using System.ComponentModel;
using Barotrauma;
using Microsoft.Xna.Framework;
using SOS.Prefabs;

namespace SOS
{
    #region AutoRegister

    /// <summary>
    /// Instructs the S.O.S. discovery engine to automatically register the decorated class into its corresponding <see cref="API"/> factory.
    /// </summary>
    /// <remarks>
    /// <para>
    /// During mod first opening (<see cref="API.Initialize"/>), the LuaCs plugin management service scans loaded assemblies
    /// for classes decorated with this attribute that implement one of the core extension interfaces:
    /// <list type="bullet">
    /// <item><description><see cref="ISOSTab"/> (or <see cref="ITab{T}"/>): Registered as a browser tab.</description></item>
    /// <item><description><see cref="ISOSStatSection"/>: Registered as an inspector wiki section.</description></item>
    /// <item><description><see cref="ISOSPrefab"/>: Registered as a prefab data provider in the browser.</description></item>
    /// <item><description><see cref="ISOSWindowProfile"/>: Registered as a visual window layout profile.</description></item>
    /// <item><description><see cref="ISOSConfig"/>: Registered as a reactive configuration unit.</description></item>
    /// </list>
    /// </para>
    /// <para>
    /// <b>Deferred Instantiation:</b> Decorating a type with this attribute registers its factory delegate without constructing an instance immediately.
    /// Actual construction is deferred until the component is first requested by the user or the active profile.
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// [AutoRegister("MyMod.RadiationSection", order: 5.0, active: true)]
    /// public class RadiationSection : ISOSStatSection
    /// {
    ///     // ...
    /// }
    /// </code>
    /// </example>
    [AttributeUsage(AttributeTargets.Class)]
    public class AutoRegisterAttribute : Attribute
    {
        /// <summary>
        /// Gets the unique string identifier used as the dictionary key in the internal registries.
        /// If <c>null</c>, the SDK automatically defaults to <c>Type.FullName ?? Type.Name</c>.
        /// </summary>
        public readonly string? Id;

        /// <summary>
        /// Gets the numerical sorting order that determines the component's execution or layout sequence relative to others.
        /// Lower values appear earlier or execute first. Defaults to <c>0.0</c>.
        /// </summary>
        public readonly double Order;

        /// <summary>
        /// Gets a value indicating whether the component is enabled upon initial discovery.
        /// If <c>false</c>, the component is registered but ignored during queries until explicitly activated via <see cref="API"/>.
        /// Defaults to <c>true</c>.
        /// </summary>
        public readonly bool Active;

        /// <summary>
        /// Initializes a new instance of the <see cref="AutoRegisterAttribute"/> class with specified registration metadata.
        /// </summary>
        /// <param name="id">Optional unique identifier. If <c>null</c> or whitespace, defaults to the declaring class's full name.</param>
        /// <param name="order">Priority order determining placement in UI lists or execution chains. Lower values appear first. Defaults to <c>0.0</c>.</param>
        /// <param name="active">Whether the component is initially enabled. Defaults to <c>true</c>.</param>
        public AutoRegisterAttribute(string? id = null, double order = 0.0, bool active = true)
        {
            Id = id;
            Order = order;
            Active = active;
        }
    }

    #endregion

    #region Interfaces

    /// <summary>
    /// Exposes an identifier property used to uniquely distinguish a component within the S.O.S. ecosystem.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public interface IIdentifier
    {
        /// <summary>
        /// Gets the unique string identifier of this instance.
        /// By default, returns the full name of the implementing runtime type.
        /// </summary>
        string Id => GetType().FullOrName();
    }

    /// <summary>
    /// Defines a modular, generic UI tab capable of inspecting and interacting with entities of type <typeparamref name="T"/>.
    /// </summary>
    /// <typeparam name="T">The data entity type inspected by this tab (e.g., <see cref="Barotrauma.Prefab"/> or <see cref="Barotrauma.Character"/>).</typeparam>
    /// <remarks>
    /// <para>
    /// <b>Lifecycle Flow:</b>
    /// <list type="number">
    /// <item><description><see cref="Init"/>: Invoked once when the hosting tab widget (<see cref="GUI.GUITab{T}"/>) is constructed.</description></item>
    /// <item><description><see cref="CanHandle"/>: Evaluated whenever a new target entity is selected to determine if this tab applies.</description></item>
    /// <item><description><see cref="Show"/>: Invoked when the user selects this tab (or when target changes while this tab is active) to construct or refresh UI elements.</description></item>
    /// <item><description><see cref="Hide"/>: Invoked when switching away from this tab to suspend visual updates or hide containers.</description></item>
    /// <item><description><see cref="IDisposable.Dispose"/>: (If implemented) Invoked when the parent window profile or widget is closed to release Monogame textures or frames.</description></item>
    /// </list>
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// [AutoRegister("MyMod.SubmarineTab", order: 10.0)]
    /// public class SubmarineTab : ITab&lt;SubmarineInfo&gt;
    /// {
    ///     public string TabName => "DETAILS";
    ///     public bool CanHandle(SubmarineInfo sub) => sub != null;
    ///     public void Init(GUIComponent container) { /* Build persistent frame */ }
    ///     public void Show(SubmarineInfo sub, Action&lt;SubmarineInfo&gt; onPrimary, Action&lt;SubmarineInfo&gt; onSecondary) { /* Draw sub stats */ }
    ///     public void Hide() { /* Hide frame */ }
    /// }
    /// </code>
    /// </example>
    [EditorBrowsable(EditorBrowsableState.Never), DefaultClass<TabDefaults>]
    public interface ITab<T> : IIdentifier
    {
        /// <summary>
        /// Gets the localized or display title rendered on the tab's selector button.
        /// </summary>
        string TabName { get; }

        /// <summary>
        /// Gets an optional tooltip description displayed when hovering over the tab's selector button.
        /// Defaults to an empty string.
        /// </summary>
        string ToolTip => "";

        /// <summary>
        /// Evaluates whether this tab is capable of displaying meaningful information for the given <paramref name="item"/>.
        /// </summary>
        /// <param name="item">The target entity currently selected.</param>
        /// <returns><c>true</c> if this tab should appear in the tab bar for this entity; otherwise, <c>false</c>.</returns>
        bool CanHandle(T item);

        /// <summary>
        /// Initializes persistent UI containers when the tab widget is constructed.
        /// </summary>
        /// <param name="contentContainer">The parent <see cref="Barotrauma.GUIComponent"/> where this tab's visual hierarchy must be attached.</param>
        void Init(GUIComponent contentContainer);

        /// <summary>
        /// Populates or updates the tab's visual content for the active <paramref name="item"/>.
        /// </summary>
        /// <param name="item">The entity to inspect and visualize.</param>
        /// <param name="onPrimary">Callback invoked when a related entity is primary-clicked (e.g., navigating to an ingredient).</param>
        /// <param name="onSecondary">Callback invoked when a related entity is secondary-clicked (e.g., opening its context menu).</param>
        void Show(T item, Action<T> onPrimary, Action<T> onSecondary);

        /// <summary>
        /// Hides the tab UI when another tab becomes active.
        /// </summary>
        void Hide();

        /// <summary>
        /// Creates and styles the header button representing this tab in the tab bar.
        /// </summary>
        /// <param name="tabName">The label displayed on the button.</param>
        /// <param name="parent">The parent <see cref="Barotrauma.RectTransform"/> layout container.</param>
        /// <param name="isActive">Whether this tab is currently the active view.</param>
        /// <param name="onClick">Action invoked when the player clicks this tab button.</param>
        /// <param name="toolTip">Optional tooltip text displayed on hover.</param>
        /// <returns>A configured <see cref="Barotrauma.GUIButton"/> instance.</returns>
        GUIButton CreateTabButton(string tabName, RectTransform parent, bool isActive, Action onClick, string toolTip = "")
            => TabDefaults.CreateTabButton(tabName, parent, isActive, onClick, toolTip);
    }

    /// <summary>
    /// Defines a modular, completely stateless wiki inspector section rendered in the right-hand panel of S.O.S.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Zero-Allocation Stateless Architecture:</b> Implementations must be <b>100% stateless</b>. Instances are cached as reusable
    /// services in the SDK registry; therefore, implementations must not store per-prefab analysis data in class fields.
    /// All parsing, filtering, and visual row construction must occur locally within <see cref="Draw"/>.
    /// </para>
    /// <para>
    /// <b>Rendering Pipeline:</b> When the player selects a prefab, the active window profile iterates all active sections:
    /// <list type="bullet">
    /// <item><description>If the prefab contains relevant data (e.g., medical treatments, weapon stats, container capacities), the section renders rows into <c>contentPanel</c> using <see cref="GUI.GUILayoutBuilder"/> and returns <c>true</c>.</description></item>
    /// <item><description>If the prefab is not applicable, the section returns <c>false</c> immediately without appending any empty frames or layout dividers.</description></item>
    /// </list>
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// [AutoRegister(order: 2.0)]
    /// public class RadiationStatSection : ISOSStatSection
    /// {
    ///     public bool Draw(GUIListBox contentPanel, Prefab prefab, Action&lt;Prefab&gt; onPrimary, Action&lt;Prefab&gt; onSecondary)
    ///     {
    ///         if (prefab is not ItemPrefab item || !item.Tags.Contains("radioactive"))
    ///             return false;
    ///
    ///         using var l = new GUILayoutBuilder(contentPanel);
    ///         l.Header("RADIATION HAZARD", Color.GreenYellow);
    ///         l.Row("Radiation Output:", "High", Color.Red);
    ///         return true;
    ///     }
    /// }
    /// </code>
    /// </example>
    public interface ISOSStatSection
    {
        /// <summary>
        /// Analyzes the specified <paramref name="prefab"/> and appends visual layout rows into <paramref name="contentPanel"/> if applicable.
        /// </summary>
        /// <param name="contentPanel">The parent list box container where layout components will be added.</param>
        /// <param name="prefab">The target entity currently being inspected.</param>
        /// <param name="onPrimary">Callback invoked when a referenced prefab is left-clicked (e.g., selecting a required item or treatment).</param>
        /// <param name="onSecondary">Callback invoked when a referenced prefab is right-clicked (e.g., opening a contextual action menu).</param>
        /// <returns><c>true</c> if the section was applicable and visual elements were added; otherwise, <c>false</c>.</returns>
        bool Draw(GUIListBox contentPanel, Prefab prefab, Action<Prefab> onPrimary, Action<Prefab> onSecondary);
    }

    /// <summary>
    /// Defines a modular prefab inspection tab (type alias for <see cref="ITab{T}"/> where <c>T</c> is <see cref="Barotrauma.Prefab"/>).
    /// </summary>
    public interface ISOSTab : ITab<Prefab>;

    /// <summary>
    /// Defines an extensible configuration unit with lifecycle persistence, factory defaults, and declarative UI rendering.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Implementations are managed through <see cref="API"/> and integrate with <see cref="Configs.ConfigDirtySaver"/>
    /// to buffer changes and persist them safely using Barotrauma's LuaCs config service.
    /// </para>
    /// <para>
    /// <b>Lifecycle Methods:</b>
    /// <list type="bullet">
    /// <item><term><see cref="Load"/>:</term><description>Invoked during client startup (<see cref="Configs.ConfigHelper.LoadConfigs"/>) to load saved values into memory.</description></item>
    /// <item><term><see cref="Save"/>:</term><description>Invoked on window dismissal or round transitions to serialize modified values to disk.</description></item>
    /// <item><term><see cref="Reset"/>:</term><description>Restores all settings managed by this unit to their default values.</description></item>
    /// <item><term><see cref="DrawSettings"/>:</term><description>Constructs the interactive configuration UI in the settings window using <see cref="GUI.GUILayoutBuilder"/>.</description></item>
    /// </list>
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// [AutoRegister("MyMod.Settings", order: 5.0)]
    /// public class MyModSettings : ConfigDirtySaver, ISOSConfig
    /// {
    ///     public void Load() { /* ... */ }
    ///     public void Save() { /* ... */ }
    ///     public void Reset() { /* ... */ }
    ///     public bool DrawSettings(GUIListBox container)
    ///     {
    ///         using var l = new GUILayoutBuilder(container);
    ///         l.Header("MY MOD CONFIG", Color.Gold);
    ///         l.ButtonToResetSection(this);
    ///         return true;
    ///     }
    /// }
    /// </code>
    /// </example>
    [DefaultClass<ConfigDefaults>]
    public interface ISOSConfig
    {
        /// <summary>
        /// Loads saved settings from persistent storage into runtime memory.
        /// </summary>
        void Load();

        /// <summary>
        /// Persists modified configuration properties to disk.
        /// </summary>
        void Save();

        /// <summary>
        /// Reverts all settings managed by this configuration back to their factory default values.
        /// </summary>
        void Reset() { }

        /// <summary>
        /// Declaratively draws the interactive settings controls for this configuration unit into the specified container.
        /// </summary>
        /// <param name="container">The list box container in the settings window where controls will be appended.</param>
        /// <returns><c>true</c> if any UI controls were drawn; otherwise, <c>false</c>.</returns>
        bool DrawSettings(GUIListBox container) => false;
    }

    /// <summary>
    /// Represents parsed search criteria used by <see cref="ISOSPrefab.GetAll(ISOSPrefabFilter)"/> to filter entities in the browser.
    /// </summary>
    /// <remarks>
    /// Supports advanced search prefixes parsed by <c>PrefabFilterHelper.SearchFilter</c>:
    /// <list type="bullet">
    /// <item><term>@</term><description>Filters by Content Package / Mod Name (<see cref="Mod"/>).</description></item>
    /// <item><term>#</term><description>Filters by Category enum string (<see cref="Category"/>).</description></item>
    /// <item><term>$</term><description>Filters by item or affliction tag (<see cref="Tag"/>).</description></item>
    /// <item><term>&amp;</term><description>Filters by equipment slot string (<see cref="Slot"/>).</description></item>
    /// <item><term>!</term><description>Filters by exact or partial identifier string (<see cref="ID"/>).</description></item>
    /// <item><term>%</term><description>Filters by Prefab type name (<see cref="PrefabType"/>).</description></item>
    /// </list>
    /// </remarks>
    public interface ISOSPrefabFilter
    {
        /// <summary>
        /// Gets general search keywords that match across names, identifiers, or content package titles.
        /// </summary>
        List<string> General { get; }

        /// <summary>
        /// Gets content package / mod name filter tokens (prefixed with '@').
        /// </summary>
        List<string> Mod { get; }

        /// <summary>
        /// Gets entity category filter tokens (prefixed with '#').
        /// </summary>
        List<string> Category { get; }

        /// <summary>
        /// Gets tag filter tokens (prefixed with '$').
        /// </summary>
        List<string> Tag { get; }

        /// <summary>
        /// Gets equipment inventory slot filter tokens (prefixed with '&amp;').
        /// </summary>
        List<string> Slot { get; }

        /// <summary>
        /// Gets exact identifier filter tokens (prefixed with '!').
        /// </summary>
        List<string> ID { get; }

        /// <summary>
        /// Gets entity prefab type filter tokens (prefixed with '%').
        /// </summary>
        List<string> PrefabType { get; }
    }

    /// <summary>
    /// Defines an extensible prefab data source that feeds entities into the S.O.S. left sidebar browser.
    /// </summary>
    /// <remarks>
    /// By implementing this interface and decorating the class with <see cref="AutoRegisterAttribute"/>,
    /// third-party mods can introduce new browsable entity types (such as custom subassemblies, event prefabs, or jobs)
    /// into the main S.O.S. interface.
    /// </remarks>
    /// <example>
    /// <code>
    /// [AutoRegister("MyMod.JobProvider", order: 3.0)]
    /// public class JobPrefabProvider : ISOSPrefab
    /// {
    ///     public Type PrefabType => typeof(JobPrefab);
    ///     public string Header => "Jobs &amp; Roles";
    ///     public IEnumerable&lt;Prefab&gt; GetAll(ISOSPrefabFilter filter)
    ///     {
    ///         return JobPrefab.Prefabs.Where(j => filter.General.Count == 0 || j.Name.Value.Contains(filter.General[0]));
    ///     }
    /// }
    /// </code>
    /// </example>
    public interface ISOSPrefab
    {
        /// <summary>
        /// Gets the base entity type provided by this source (e.g., <see cref="Barotrauma.ItemPrefab"/> or <see cref="Barotrauma.AfflictionPrefab"/>).
        /// </summary>
        Type PrefabType { get; }

        /// <summary>
        /// Gets the section header title rendered above this provider's items in the browser list.
        /// </summary>
        string Header { get; }

        /// <summary>
        /// Queries and yields all prefabs provided by this source that satisfy the specified <paramref name="filter"/>.
        /// </summary>
        /// <param name="filter">The structured search filter containing text, category, tag, and mod tokens.</param>
        /// <returns>An enumerable sequence of matching <see cref="Barotrauma.Prefab"/> instances.</returns>
        IEnumerable<Prefab> GetAll(ISOSPrefabFilter filter);

        /// <summary>
        /// Constructs right-click contextual action options for an entity belonging to this provider.
        /// </summary>
        /// <param name="prefab">The prefab being right-clicked.</param>
        /// <returns>A list of context menu options (e.g., "View Recipes", "Add to Favorites", "Track to HUD").</returns>
        [DefaultClass<PrefabDefaults>]
        List<ContextMenuOption> BuildContextOptions(Prefab prefab) => PrefabDefaults.BuildContextOptions(prefab);
    }

    /// <summary>
    /// Defines an interchangeable visual presentation layout for the S.O.S. window.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Implementations inherit from <see cref="GUI.GUIWindow"/> and define how the screen space is partitioned
    /// (e.g., 3-column browser view, compact single-column inspector, or floating HUD tool).
    /// </para>
    /// <para>
    /// <b>Hot-Swapping:</b> Profiles can be changed dynamically at runtime via <see cref="API.Emit{T}(string, T, double?, bool)"/>
    /// using <see cref="CommKeys.ChangeProfile"/>. When switching profiles, the outgoing profile is disposed and the incoming profile
    /// is instantiated, initialized via <see cref="Init"/>, and opened seamlessly.
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// [AutoRegister("MyMod.CompactProfile", order: 20.0)]
    /// public class CompactProfile : GUIWindow, ISOSWindowProfile
    /// {
    ///     public string DisplayName => "Compact Inspector";
    ///     public string Description => "Minimalist floating window.";
    ///     public void Init() { /* Build UI */ }
    ///     public void Update() { /* Frame update */ }
    /// }
    /// </code>
    /// </example>
    [DefaultClass<WindowProfileDefaults>]
    public interface ISOSWindowProfile : IIdentifier, IDisposable
    {
        /// <summary>
        /// Gets the localized or display name of this window profile, shown in the profile selection dropdown.
        /// </summary>
        string DisplayName { get; }

        /// <summary>
        /// Gets a localized description detailing the visual layout and intended usage of this profile.
        /// </summary>
        string Description { get; }

        /// <summary>
        /// Gets optional profile-specific configuration settings (e.g., custom panel widths, saved layout presets).
        /// Returns <c>null</c> if the profile does not require persistent settings.
        /// </summary>
        ISOSConfig? ProfileConfig => null;

        /// <summary>
        /// Initializes the profile's visual hierarchy, event subscriptions, and geometry state.
        /// Invoked immediately after construction when the profile becomes active.
        /// </summary>
        void Init();

        /// <summary>
        /// Performs frame-by-frame updates, layout checks, input handling, and debouncing while the window is visible.
        /// </summary>
        void Update();
    }

    #endregion

    #region Default Proxy Classes

    /// <summary>
    /// Provides default fallback implementations for tab components when adapted via <see cref="DuckProxy{T}"/>.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal sealed class TabDefaults
    {
        private TabDefaults() { }

        /// <summary>
        /// Default empty tooltip for tabs.
        /// </summary>
        public static string ToolTip => "";

        /// <summary>
        /// Creates a standard tab button styled with the "MainMenuNotificationButton" template.
        /// </summary>
        /// <param name="tabName">The label displayed on the button.</param>
        /// <param name="parent">The parent rectangle transform.</param>
        /// <param name="isActive">Whether this tab is currently selected.</param>
        /// <param name="onClick">Callback invoked when the button is clicked.</param>
        /// <param name="toolTip">Optional tooltip text.</param>
        /// <returns>A configured <see cref="Barotrauma.GUIButton"/>.</returns>
        public static GUIButton CreateTabButton(string tabName, RectTransform parent, bool isActive, Action onClick, string toolTip = "")
        {
            Vector2 textSize = GUIStyle.SmallFont.MeasureString(tabName);
            int width = (int)textSize.X + 24;
            var tabBtn = new GUIButton(new RectTransform(new Point(width, 32), parent) { IsFixedSize = true }, tabName, style: "MainMenuNotificationButton")
            {
                Selected = isActive,
                OnClicked = (_, _) => { onClick(); return true; },
            };
            if (!toolTip.IsNullOrEmpty())
                tabBtn.ToolTip = toolTip;
            return tabBtn;
        }
    }

    /// <summary>
    /// Provides default fallback implementations for configuration contracts when adapted via <see cref="DuckProxy{T}"/>.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal sealed class ConfigDefaults
    {
        /// <summary>
        /// Default no-op reset implementation.
        /// </summary>
        public static void Reset() { }

        /// <summary>
        /// Default settings render implementation returning <c>false</c> (no UI drawn).
        /// </summary>
        /// <param name="_">The GUI list box container (ignored).</param>
        /// <returns>Always <c>false</c>.</returns>
        public static bool DrawSettings(GUIListBox _) => false;
    }

    /// <summary>
    /// Provides default fallback implementations for prefab right-click contextual actions.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal sealed class PrefabDefaults
    {
        /// <summary>
        /// Constructs the baseline context menu options for a prefab: "View Recipes" and "Add/Remove from Favorites".
        /// </summary>
        /// <param name="prefab">The target prefab.</param>
        /// <returns>A list of standard <see cref="Barotrauma.ContextMenuOption"/> actions.</returns>
        public static List<ContextMenuOption> BuildContextOptions(Prefab prefab)
        {
            var options = new List<ContextMenuOption>
            {
                new(Texts.Get("sos.context.view_recipes", "View Recipes").Value, isEnabled: true, onSelected: () => API.Emit(CommKeys.SelectTarget, prefab))
            };

            string targetId = prefab.Identifier.Value;
            bool isFav = PrefabHelper.IsFavorite(targetId);
            string favText = isFav ? Texts.Get("sos.context.remove_favorite", "Remove from Favorites").Value : Texts.Get("sos.context.add_favorite", "Add to Favorites").Value;

            options.Add(new ContextMenuOption(favText, true, () => { PrefabHelper.ToggleFavorite(targetId); }));

            return options;
        }
    }

    /// <summary>
    /// Provides default fallback implementations for window profiles when adapted via <see cref="DuckProxy{T}"/>.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal sealed class WindowProfileDefaults
    {
        /// <summary>
        /// Default profile configuration accessor returning <c>null</c>.
        /// </summary>
        public static ISOSConfig? ProfileConfig => null;
    }

    #endregion
}