// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using System.Reflection;
using MoonSharp.Interpreter;

namespace SOS
{
    /// <summary>
    /// Base attribute for default class resolution in DuckProxy.
    /// </summary>
    /// <remarks>
    /// This attribute is used by <see cref="DuckProxy{T}"/> to resolve fallback methods when a target method or property
    /// is not directly found on the adapted object. The fallback resolution chain is:
    /// <list type="bullet">
    /// <item><term>Parameter-based lookup:</term><description>Gets the method's parameter types and searches for a matching static method on the helper type.</description></item>
    /// <item><term>Property-based lookup:</term><description>If the interface method is a property getter, searches the declaring type's properties for a matching getter.</description></item>
    /// <item><term>Type-level fallback attribute:</term><description>Searches the declaring type or its parents for a <see cref="DefaultClassAttributeBase"/> decoration.</description></item>
    /// </list>
    /// </remarks>
    [AttributeUsage(AttributeTargets.Interface | AttributeTargets.Method | AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public abstract class DefaultClassAttributeBase : Attribute
    {
        internal abstract Type HelperType { get; }

        internal MethodInfo? GetMethod(MethodInfo interfaceMethod)
        {
            ArgumentNullException.ThrowIfNull(interfaceMethod);

            var parameterTypes = interfaceMethod.GetParameters()
                .Select(p => p.ParameterType)
                .ToArray();

            return HelperType.GetMethod(
                interfaceMethod.Name,
                BindingFlags.Public | BindingFlags.Static,
                null,
                parameterTypes,
                null
            );
        }
    }

    /// <summary>
    /// Attribute specifying a default (fallback) static method for resolving DuckProxy handlers.
    /// </summary>
    /// <remarks>
    /// When a target method or property is not found directly on the adapted object, the DuckProxy will search for
    /// a static method on the helper type decorated with this attribute. The static method signature must match the
    /// interface method signature (parameter types and return type).
    /// </remarks>
    /// <example>
    /// <code>
    /// public interface IMyService
    /// {
    ///     int GetValue();
    /// }
    ///
    /// public static class MyServiceHelper
    /// {
    ///     [DefaultClass]
    ///     public static int GetValue() => 42;
    /// }
    ///
    /// // Usage: DuckProxy&lt;IMyService&gt;.Create(someObject);
    /// </code>
    /// </example>
    public sealed class DefaultClassAttribute : DefaultClassAttributeBase
    {
        internal override Type HelperType { get; }

        internal DefaultClassAttribute(Type helperType)
            => HelperType = helperType ?? throw new ArgumentNullException(nameof(helperType));
    }

    /// <summary>
    /// Generic version of <see cref="DefaultClassAttribute"/> that resolves to a specific helper type via a generic parameter.
    /// </summary>
    /// <typeparam name="THelper">The concrete helper type that provides fallback methods.</typeparam>
    /// <remarks>
    /// The helper type is resolved at compile time via the generic parameter <typeparamref name="THelper"/>.
    /// This is a convenient alternative to explicitly decorating interface methods with <see cref="DefaultClassAttribute"/>.
    /// </remarks>
    public sealed class DefaultClassAttribute<THelper> : DefaultClassAttributeBase where THelper : class
    {
        internal override Type HelperType => typeof(THelper);
    }

    /// <summary>
    /// A DispatchProxy-based adapter that dynamic MoonSharp Lua tables and external assemblies to C# interfaces at runtime.
    /// </summary>
    /// <typeparam name="T">The C# interface type that the proxy adapts.</typeparam>
    /// <remarks>
    /// The proxy uses <see cref="DispatchProxy"/> infrastructure to dynamically intercept method calls and property accesses
    /// on the target interface type. At initialization, the proxy configures handlers for each interface method:
    /// <list type="bullet">
    /// <item><term>CLR objects:</term><description>Uses reflection to find matching methods on the target object, with fallback
    /// resolution via <see cref="DefaultClassAttributeBase"/> if methods are missing.</description></item>
    /// <item><term>MoonSharp Lua tables:</term><description>Extracts values from the Lua table, supporting property access (get/set)
    /// and function calls. Falls back to static helper methods if table entries are missing.</description></item>
    /// </list>
    /// Thread-safety: The proxy uses a handler map (_handlerMap) to cache method-to-delegate mappings. The map is populated
    /// during initialization and read-only thereafter, ensuring thread-safe invocation.
    /// </remarks>
    /// <example>
    /// <code>
    /// // Create a proxy for a Lua table
    /// var luaTable = script.GetTable("my_table");
    /// var service = DuckProxy&lt;IMyService&gt;.Create(luaTable);
    ///
    /// // Create a proxy for a CLR object
    /// var clrObject = new MyClrImplementation();
    /// var service2 = DuckProxy&lt;IMyService&gt;.Create(clrObject);
    /// </code>
    /// </example>
    internal class DuckProxy<T> : DispatchProxy where T : class
    {
        private readonly Dictionary<MethodInfo, Func<object?[], object?>> _handlerMap = [];

        public DuckProxy() { }

        public static T Create(object target)
        {
            var instance = Create<T, DuckProxy<T>>();

            ((DuckProxy<T>)(object)instance).Initialize(target);

            return instance;
        }

        private void Initialize(object target)
        {
            switch (target)
            {
                case null:
                    throw new ArgumentNullException(nameof(target));

                case Table luaTable:
                    ConfigureLuaTable(luaTable);
                    break;

                default:
                    ConfigureClrObject(target);
                    break;
            }
        }

        private static IEnumerable<MethodInfo> GetAllInterfaceMethods(Type type)
        {
            foreach (var method in type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly))
                yield return method;
            foreach (var parent in type.GetInterfaces())
                foreach (var method in GetAllInterfaceMethods(parent))
                    yield return method;
        }

        private void ConfigureClrObject(object target)
        {
            var targetType = target.GetType();
            var interfaceType = typeof(T);
            var errors = new List<string>();

            foreach (var interfaceMethod in GetAllInterfaceMethods(interfaceType))
            {
                var parameterTypes = interfaceMethod.GetParameters()
                    .Select(p => p.ParameterType)
                    .ToArray();

                var targetMethod = targetType.GetMethod(interfaceMethod.Name, parameterTypes);

                if (targetMethod == null)
                {
                    if (TryResolveFallback(interfaceMethod, out var fallbackHandler))
                        _handlerMap[interfaceMethod] = fallbackHandler!;
                    else
                        errors.Add($"Missing method or property: '{interfaceMethod.Name}'");

                    continue;
                }

                if (targetMethod.ReturnType != interfaceMethod.ReturnType)
                {
                    errors.Add($"Return type mismatch on '{interfaceMethod.Name}'. Expected: {interfaceMethod.ReturnType.Name}, Found: {targetMethod.ReturnType.Name}");
                    continue;
                }

                _handlerMap[interfaceMethod] = args => targetMethod.Invoke(target, args);
            }

            if (errors.Count > 0)
            {
                throw new InvalidCastException(
                    $"Type '{targetType.FullName}' does not satisfy contract of '{interfaceType.FullName}':\n" +
                    string.Join("\n", errors));
            }
        }

        private void ConfigureLuaTable(Table table)
        {
            var interfaceType = typeof(T);
            var errors = new List<string>();

            foreach (var interfaceMethod in GetAllInterfaceMethods(interfaceType))
            {
                var methodName = interfaceMethod.Name;
                var returnType = interfaceMethod.ReturnType;

                if (methodName.StartsWith("get_"))
                {
                    var propName = methodName[4..];


                    if (table.Get(propName).IsNil())
                    {
                        if (TryResolveFallback(interfaceMethod, out var fallbackHandler))
                            _handlerMap[interfaceMethod] = fallbackHandler!;
                        else
                            errors.Add($"Missing property '{propName}' in Lua table.");

                        continue;
                    }

                    _handlerMap[interfaceMethod] = _ => table.Get(propName).ToObject(returnType);
                }
                else if (methodName.StartsWith("set_"))
                {
                    var propName = methodName[4..];

                    _handlerMap[interfaceMethod] = args =>
                    {
                        table.Set(propName, DynValue.FromObject(table.OwnerScript, args.FirstOrDefault()));
                        return null;
                    };
                }
                else
                {
                    var luaFunc = table.Get(methodName);

                    if (luaFunc.Type != DataType.Function && luaFunc.Type != DataType.ClrFunction)
                    {
                        if (TryResolveFallback(interfaceMethod, out var fallbackHandler))
                            _handlerMap[interfaceMethod] = fallbackHandler!;
                        else
                            errors.Add($"Missing function '{methodName}' in Lua table.");

                        continue;
                    }

                    _handlerMap[interfaceMethod] = args =>
                    {
                        var result = table.OwnerScript.Call(luaFunc, args);
                        return returnType == typeof(void) ? null : result.ToObject(returnType);
                    };
                }
            }

            if (errors.Count > 0)
            {
                throw new InvalidCastException(
                    $"Lua table does not satisfy contract of '{interfaceType.FullName}':\n" +
                    string.Join("\n", errors));
            }
        }

        protected override object? Invoke(MethodInfo? targetMethod, object?[]? args)
        {
            if (targetMethod != null && _handlerMap.TryGetValue(targetMethod, out var handler))
                return handler(args ?? []);

            throw new NotImplementedException($"Operation '{targetMethod?.Name}' is not supported.");
        }

        private static bool TryResolveFallback(MethodInfo interfaceMethod, out Func<object?[], object?>? handler)
        {
            handler = null;
            var fallbackAttr = interfaceMethod.GetCustomAttribute<DefaultClassAttributeBase>();

            if (fallbackAttr == null)
            {
                var declaringType = interfaceMethod.DeclaringType;
                if (declaringType != null)
                {
                    var property = declaringType.GetProperties()
                        .FirstOrDefault(p => p.GetMethod == interfaceMethod);
                    fallbackAttr = property?.GetCustomAttribute<DefaultClassAttributeBase>();
                }
            }

            if (fallbackAttr == null)
            {
                var declaringType = interfaceMethod.DeclaringType;
                if (declaringType != null)
                {
                    fallbackAttr = declaringType.GetCustomAttribute<DefaultClassAttributeBase>(inherit: true);
                }
            }

            if (fallbackAttr == null) return false;

            var staticFallbackMethod = fallbackAttr.GetMethod(interfaceMethod);
            if (staticFallbackMethod == null) return false;

            handler = args => staticFallbackMethod.Invoke(null, args);
            return true;
        }
    }

    /// <summary>
    /// Extension methods for creating and managing DuckProxies.
    /// </summary>
    /// <remarks>
    /// Provides strongly-typed methods for creating DuckProxies from target objects (Lua tables or CLR objects)
    /// and for type-safe casting attempts.
    /// </remarks>
    internal static class DuckExtensions
    {
        internal static T Cast<T>(this object target) where T : class
        {
            ArgumentNullException.ThrowIfNull(target);

            if (target is T native)
                return native;

            T proxy = DuckProxy<T>.Create(target);
            return proxy;
        }

        internal static bool TryCast<T>(this object target, out T? a) where T : class
        {
            try
            {
                a = target.Cast<T>();
                return true;
            }
            catch
            {
                a = null;
                return false;
            }
        }
    }
}