// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using System.Diagnostics.CodeAnalysis;
using System.Text.RegularExpressions;
using Barotrauma;
using Barotrauma.LuaCs.Data;
using Microsoft.Xna.Framework;

namespace SOS
{
    public static class RichStringExt
    {
        public static RichString Rich(this string text) => RichString.Rich(text);

        public static string SetHyperlink(this string text, Color? color = null)
            => text.SetColor(color ?? Color.LightSkyBlue);

        public static LocalizedString SetHyperlink(this LocalizedString text, Color? color = null)
            => text.SetColor(color ?? Color.LightSkyBlue);

        public static string SetColor(this string text, string colorName)
        => $"‖color:{colorName}‖{text}‖end‖";

        public static string SetColor(this string text, Color color)
            => $"‖color:{color.R},{color.G},{color.B}‖{text}‖end‖";

        public static string SetColorHex(this string text, string hexCode)
            => $"‖color:{hexCode}‖{text}‖end‖";

        public static string SetBold(this string text)
            => $"‖bold‖{text}‖end‖";

        public static string SetItalic(this string text)
            => $"‖italic‖{text}‖end‖";

        public static string SetUnderline(this string text)
            => $"‖underline‖{text}‖end‖";

        public static string SetStrikethrough(this string text)
            => $"‖strikethrough‖{text}‖end‖";

        public static LocalizedString SetColor(this LocalizedString text, string colorName)
        => $"‖color:{colorName}‖{text}‖end‖";

        public static LocalizedString SetColor(this LocalizedString text, Color color)
            => $"‖color:{color.R},{color.G},{color.B}‖{text}‖end‖";

        public static LocalizedString SetColorHex(this LocalizedString text, string hexCode)
            => $"‖color:{hexCode}‖{text}‖end‖";

        public static LocalizedString SetBold(this LocalizedString text)
            => $"‖bold‖{text}‖end‖";

        public static LocalizedString SetItalic(this LocalizedString text)
            => $"‖italic‖{text}‖end‖";

        public static LocalizedString SetUnderline(this LocalizedString text)
            => $"‖underline‖{text}‖end‖";

        public static LocalizedString SetStrikethrough(this LocalizedString text)
            => $"‖strikethrough‖{text}‖end‖";

    }

    public static class HyperlinkExtensions
    {
        public static RichString JoinToRichString<T>(
            this IEnumerable<T> items,
            string separator,
            Func<T, string> textSelector,
            Func<T, Color> colorSelector)
        {
            var sb = new System.Text.StringBuilder();
            var list = items.ToList();

            for (int i = 0; i < list.Count; i++)
            {
                var item = list[i];
                Color color = colorSelector(item);
                string text = textSelector(item).Replace("‖", "");

                // Formateo simple por color.
                sb.Append(text.SetColor(color));

                if (i < list.Count - 1) sb.Append(separator);
            }

            return RichString.Rich(sb.ToString());
        }

        public static void BindHyperlinks<T>(
            this GUITextBlock textBlock,
            IEnumerable<T> items,
            Action<T> onPrimaryClick,
            Action<T>? onSecondaryClick = null)
        {
            var list = items.ToList();

            void ApplyLinks()
            {
                if (textBlock.RichTextData == null) return;
                textBlock.ClickableAreas.Clear();

                int index = 0;
                foreach (var data in textBlock.RichTextData)
                {
                    if (data.StartIndex >= data.EndIndex || data.StartIndex < 0 || data.Color == null) continue;
                    if (index >= list.Count) break;

                    var target = list[index];
                    textBlock.ClickableAreas.Add(new GUITextBlock.ClickableArea()
                    {
                        Data = data,
                        OnClick = (tb, area) => { onPrimaryClick?.Invoke(target); },
                        OnSecondaryClick = onSecondaryClick != null ? ((tb, area) => { onSecondaryClick.Invoke(target); }) : null
                    });
                    index++;
                }
            }

            ApplyLinks();
            textBlock.RectTransform.SizeChanged += ApplyLinks;
        }
    }

    // This Class has been generated by AI, does not affect the copyright or copyleft.
    public static partial class XMLHighlighter
    {
        // Syntax colors (IDE "Dark Theme" style palette)
        private static readonly Color ColNode = Color.CornflowerBlue;   // <Item>
        private static readonly Color ColAttr = Color.LightSkyBlue;     // identifier=
        private static readonly Color ColValue = Color.LightSalmon;     // "steel"
        private static readonly Color ColComment = Color.DarkSeaGreen;  // <!-- comment -->
        private static readonly Color ColPunctuation = Color.LightGray; // < > / =

        public static RichString FormatToXMLCode(this string rawXml)
        {
            if (string.IsNullOrWhiteSpace(rawXml)) return RichString.Rich("");

            // 1. Scape Barotrauma RichText characters (the ‖ symbol)
            // If the raw XML had this symbol for some reason, it would break the parser.
            string safeXml = rawXml.Replace("‖", "||");

            // 2. Highlight Strings (Values between quotes)
            safeXml = RegexValue().Replace(safeXml, match
                => match.Value.SetColor(ColValue));

            // 3. Highlight Attributes
            safeXml = RegexAttribute().Replace(safeXml, match
                => match.Value.SetColor(ColAttr));

            // 4. Highlight Node Names (<Node)
            safeXml = RegexNodeName().Replace(safeXml, match
                => match.Value.SetColor(ColNode));

            // 5. Highlight Punctuation (Angles and equals signs)
            // NOTE: To avoid replacing our own color tags (‖color:Hex‖), 
            // the regex will not touch anything between ‖ symbols.
            // A safer way is to do punctuation first, but it interferes with HTML.
            // To simplify, we color the basic punctuation.
            safeXml = RegexPunctuation().Replace(safeXml, match
                => match.Value.SetColor(ColPunctuation));

            // 6. Highlight Comments (They have priority and overwrite any internal color)
            safeXml = RegexComment().Replace(safeXml, match
                => CleanComment().Replace(match.Value, "").SetColor(ColComment));

            return safeXml.Rich();
        }

        [GeneratedRegex(@"<!--[\s\S]*?-->", RegexOptions.Compiled)]
        private static partial Regex RegexComment();
        [GeneratedRegex(@"(?<=<|</)[a-zA-Z0-9_\-]+", RegexOptions.Compiled)]
        private static partial Regex RegexNodeName();
        [GeneratedRegex(@"([a-zA-Z0-9_\-]+)(?=\s*=)", RegexOptions.Compiled)]
        private static partial Regex RegexAttribute();
        [GeneratedRegex(@"""[^""]*""", RegexOptions.Compiled)]
        private static partial Regex RegexValue();
        [GeneratedRegex(@"<|>|/|=", RegexOptions.Compiled)]
        private static partial Regex RegexPunctuation();
        [GeneratedRegex(@"‖color:[^‖]+‖|‖color:end‖")]
        private static partial Regex CleanComment();
    }
    // End of AI Code.

    internal static class FloatExt
    {
        internal static string ToMeters(this float value) => (value / 10f).ToValue() + 'm';
        internal static string ToValue(this float value) => value.ToString("0.###");
        internal static string ToSignedValue(this float value) => ((value > 0) ? '+' : (value < 0) ? '-' : ' ') + value.ToValue();
    }

    internal static class PrefabExt
    {

        public static (string Name, Color TextColor) SafeName(this Prefab? prefab, Color defaultColor)
        {
            return prefab switch
            {
                ItemPrefab item => item.Name.IsNullOrEmpty()
                                        ? ($"[{item.Identifier}]", Color.Red)
                                        : (item.Name.Value, defaultColor),
                AfflictionPrefab affliction => affliction.Name.IsNullOrEmpty()
                                        ? ($"[{affliction.Identifier}]", Color.Red)
                                        : (affliction.Name.Value, defaultColor),
                _ => (Texts.Get("sos.gen.unknown", "???").Value, defaultColor),
            };
        }
        public static string Name(this Prefab prefab)
        {
            return prefab switch
            {
                ItemPrefab item => item.Name.ToString(),
                AfflictionPrefab affliction => affliction.Name.ToString(),
                _ => prefab.Identifier.ToString()
            };
        }
        public static Sprite? Icon(this Prefab? prefab)
        {
            return prefab switch
            {
                ItemPrefab item => item.InventoryIcon ?? item.sprite,
                AfflictionPrefab affliction => affliction.Icon,
                _ => null
            };
        }
        public static Color IconColor(this Prefab? prefab)
        {
            return prefab switch
            {
                ItemPrefab item => item.InventoryIconColor,
                AfflictionPrefab affliction => affliction.IconColors?.FirstOrDefault(Color.White),
                _ => null
            } ?? Color.White;
        }

        public static ContentXElement? ConfigElement(this Prefab prefab)
        {
            return prefab switch
            {
                ItemPrefab item => item.ConfigElement,
                AfflictionPrefab affliction => affliction.configElement,
                _ => null
            };
        }
    }

    internal static class TypeExt
    {
        internal static string FullOrName(this Type type) => type.FullName ?? type.Name;
    }

    public static class IEnumerableExt
    {
        public static string ToCsv<T>(this IEnumerable<T> collection, char separator = ',')
        {
            return string.Join(separator, collection);
        }
    }

    public static class IDictionaryExt
    {
        public static T? GetValueLocked<S, T>(this IDictionary<S, T> dict, S key) where S : notnull
        {
            lock (dict)
                if (dict.TryGetValue(key, out var value))
                    return value;
            return default;
        }
    }

    public static class ISettingBaseExt
    {
        public static bool SetIfNotEqual<T>([NotNullWhen(false)] this ISettingBase<T> setting, T value) where T : IEquatable<T>, IConvertible
            => (!setting.Value?.Equals(value) ?? true) && setting.TrySetValue(value);

        public static bool SetIfNotEqual([NotNullWhen(false)] this ISettingControl setting, KeyOrMouse value)
            => (!setting.Value?.Equals(value) ?? true) && setting.TrySetValue(value);
    }
}