// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using System.Diagnostics.CodeAnalysis;
using System.Text.RegularExpressions;
using Barotrauma;
using Barotrauma.LuaCs.Data;
using Microsoft.Xna.Framework;

namespace SOS
{
    /// <summary>
    /// Rich text formatting extension methods utilizing Barotrauma's native RichText formatting tags.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Barotrauma requires the specific Unicode double vertical bar character <c>‖</c> (<c>\u2016</c>) as the tag delimiter.
    /// Standard ASCII pipe characters (<c>|</c>) are not recognized by the engine and will render as raw text.
    /// </para>
    /// <para>
    /// Formats produced:
    /// <list type="bullet">
    /// <item><description>Color: <c>‖color:R,G,B‖text‖end‖</c> or <c>‖color:ColorName‖text‖end‖</c></description></item>
    /// <item><description>Style: <c>‖bold‖text‖end‖</c>, <c>‖italic‖text‖end‖</c>, <c>‖underline‖text‖end‖</c>, <c>‖strikethrough‖text‖end‖</c></description></item>
    /// </list>
    /// </para>
    /// </remarks>
    public static class RichStringExt
    {
        /// <summary>
        /// Converts a plain string to a <see cref="RichString"/> with basic formatting.
        /// </summary>
        /// <param name="text">The source string to convert.</param>
        /// <returns>A <see cref="RichString"/> instance initialized with the source text.</returns>
        /// <remarks>
        /// This is an alias for <c>RichString.Rich(string)</c>.
        /// </remarks>
        public static RichString Rich(this string text) => RichString.Rich(text);

        /// <summary>
        /// Sets a hyperlink color on a string. If no color is specified, defaults to <see cref="Color.LightSkyBlue"/>.
        /// </summary>
        /// <param name="text">The source string to apply the hyperlink color to.</param>
        /// <param name="color">Optional color for the hyperlink. Defaults to <see cref="Color.LightSkyBlue"/>.</param>
        /// <returns>A string with hyperlink color formatting applied (‖color:R,G,B‖...‖end‖).</returns>
        /// <remarks>
        /// The formatting uses Barotrauma's RichText syntax. The ‖ symbol is the RichText color tag delimiter.
        /// </remarks>
        public static string SetHyperlink(this string text, Color? color = null)
            => text.SetColor(color ?? Color.LightSkyBlue);

        /// <summary>
        /// Sets a hyperlink color on a localized string. If no color is specified, defaults to <see cref="Color.LightSkyBlue"/>.
        /// </summary>
        /// <param name="text">The localized string to apply the hyperlink color to.</param>
        /// <param name="color">Optional color for the hyperlink. Defaults to <see cref="Color.LightSkyBlue"/>.</param>
        /// <returns>A localized string with hyperlink color formatting applied.</returns>
        /// <remarks>
        /// The formatting uses Barotrauma's RichText syntax. The ‖ symbol is the RichText color tag delimiter.
        /// </remarks>
        public static LocalizedString SetHyperlink(this LocalizedString text, Color? color = null)
                => text.SetColor(color ?? Color.LightSkyBlue);

        /// <summary>
        /// Sets a color on a string using a color name.
        /// </summary>
        /// <param name="text">The source string to apply the color to.</param>
        /// <param name="colorName">The name of the color (e.g., "Red", "Green", "Blue").</param>
        /// <returns>A string with color formatting applied (‖color:R,G,B‖...‖end‖).</returns>
        /// <remarks>
        /// The formatting uses Barotrauma's RichText syntax. The ‖ symbol is the RichText color tag delimiter.
        /// </remarks>
        public static string SetColor(this string text, string colorName)
            => $"‖color:{colorName}‖{text}‖end‖";

        /// <summary>
        /// Sets a color on a string using a <see cref="Color"/> struct.
        /// </summary>
        /// <param name="text">The source string to apply the color to.</param>
        /// <param name="color">The color to apply.</param>
        /// <returns>A string with color formatting applied (‖color:R,G,B‖...‖end‖).</returns>
        /// <remarks>
        /// The formatting uses Barotrauma's RichText syntax. The ‖ symbol is the RichText color tag delimiter.
        /// </remarks>
        public static string SetColor(this string text, Color color)
            => $"‖color:{color.R},{color.G},{color.B}‖{text}‖end‖";

        /// <summary>
        /// Sets a color on a string using a hex color code.
        /// </summary>
        /// <param name="text">The source string to apply the color to.</param>
        /// <param name="hexCode">The hex color code (e.g., "FF0000" for red).</param>
        /// <returns>A string with color formatting applied (‖color:R,G,B‖...‖end‖).</returns>
        /// <remarks>
        /// The formatting uses Barotrauma's RichText syntax. The ‖ symbol is the RichText color tag delimiter.
        /// </remarks>
        public static string SetColorHex(this string text, string hexCode)
            => $"‖color:{hexCode}‖{text}‖end‖";

        /// <summary>
        /// Sets bold formatting on a string.
        /// </summary>
        /// <param name="text">The source string to make bold.</param>
        /// <returns>A string with bold formatting applied (‖bold‖...‖end‖).</returns>
        /// <remarks>
        /// The formatting uses Barotrauma's RichText syntax. The ‖ symbol is the RichText formatting tag delimiter.
        /// </remarks>
        public static string SetBold(this string text)
            => $"‖bold‖{text}‖end‖";

        /// <summary>
        /// Sets italic formatting on a string.
        /// </summary>
        /// <param name="text">The source string to make italic.</param>
        /// <returns>A string with italic formatting applied (‖italic‖...‖end‖).</returns>
        /// <remarks>
        /// The formatting uses Barotrauma's RichText syntax. The ‖ symbol is the RichText formatting tag delimiter.
        /// </remarks>
        public static string SetItalic(this string text)
            => $"‖italic‖{text}‖end‖";

        /// <summary>
        /// Sets underline formatting on a string.
        /// </summary>
        /// <param name="text">The source string to underline.</param>
        /// <returns>A string with underline formatting applied (‖underline‖...‖end‖).</returns>
        /// <remarks>
        /// The formatting uses Barotrauma's RichText syntax. The ‖ symbol is the RichText formatting tag delimiter.
        /// </remarks>
        public static string SetUnderline(this string text)
            => $"‖underline‖{text}‖end‖";

        /// <summary>
        /// Sets strikethrough formatting on a string.
        /// </summary>
        /// <param name="text">The source string to strikethrough.</param>
        /// <returns>A string with strikethrough formatting applied (‖strikethrough‖...‖end‖).</returns>
        /// <remarks>
        /// The formatting uses Barotrauma's RichText syntax. The ‖ symbol is the RichText formatting tag delimiter.
        /// </remarks>
        public static string SetStrikethrough(this string text)
            => $"‖strikethrough‖{text}‖end‖";

        /// <summary>
        /// Sets a color on a localized string using a color name.
        /// </summary>
        /// <param name="text">The localized string to apply the color to.</param>
        /// <param name="colorName">The name of the color.</param>
        /// <returns>A localized string with color formatting applied.</returns>
        /// <remarks>
        /// The formatting uses Barotrauma's RichText syntax. The ‖ symbol is the RichText color tag delimiter.
        /// </remarks>
        public static LocalizedString SetColor(this LocalizedString text, string colorName)
            => $"‖color:{colorName}‖{text}‖end‖";

        /// <summary>
        /// Sets a color on a localized string using a <see cref="Color"/> struct.
        /// </summary>
        /// <param name="text">The localized string to apply the color to.</param>
        /// <param name="color">The color to apply.</param>
        /// <returns>A localized string with color formatting applied.</returns>
        /// <remarks>
        /// The formatting uses Barotrauma's RichText syntax. The ‖ symbol is the RichText color tag delimiter.
        /// </remarks>
        public static LocalizedString SetColor(this LocalizedString text, Color color)
            => $"‖color:{color.R},{color.G},{color.B}‖{text}‖end‖";

        /// <summary>
        /// Sets a color on a localized string using a hex color code.
        /// </summary>
        /// <param name="text">The localized string to apply the color to.</param>
        /// <param name="hexCode">The hex color code.</param>
        /// <returns>A localized string with color formatting applied.</returns>
        /// <remarks>
        /// The formatting uses Barotrauma's RichText syntax. The ‖ symbol is the RichText color tag delimiter.
        /// </remarks>
        public static LocalizedString SetColorHex(this LocalizedString text, string hexCode)
            => $"‖color:{hexCode}‖{text}‖end‖";

        /// <summary>
        /// Sets bold formatting on a localized string.
        /// </summary>
        /// <param name="text">The localized string to make bold.</param>
        /// <returns>A localized string with bold formatting applied.</returns>
        /// <remarks>
        /// The formatting uses Barotrauma's RichText syntax. The ‖ symbol is the RichText formatting tag delimiter.
        /// </remarks>
        public static LocalizedString SetBold(this LocalizedString text)
            => $"‖bold‖{text}‖end‖";

        /// <summary>
        /// Sets italic formatting on a localized string.
        /// </summary>
        /// <param name="text">The localized string to make italic.</param>
        /// <returns>A localized string with italic formatting applied.</returns>
        /// <remarks>
        /// The formatting uses Barotrauma's RichText syntax. The ‖ symbol is the RichText formatting tag delimiter.
        /// </remarks>
        public static LocalizedString SetItalic(this LocalizedString text)
            => $"‖italic‖{text}‖end‖";

        /// <summary>
        /// Sets underline formatting on a localized string.
        /// </summary>
        /// <param name="text">The localized string to underline.</param>
        /// <returns>A localized string with underline formatting applied.</returns>
        /// <remarks>
        /// The formatting uses Barotrauma's RichText syntax. The ‖ symbol is the RichText formatting tag delimiter.
        /// </remarks>
        public static LocalizedString SetUnderline(this LocalizedString text)
            => $"‖underline‖{text}‖end‖";

        /// <summary>
        /// Sets strikethrough formatting on a localized string.
        /// </summary>
        /// <param name="text">The localized string to strikethrough.</param>
        /// <returns>A localized string with strikethrough formatting applied.</returns>
        /// <remarks>
        /// The formatting uses Barotrauma's RichText syntax. The ‖ symbol is the RichText formatting tag delimiter.
        /// </remarks>
        public static LocalizedString SetStrikethrough(this LocalizedString text)
            => $"‖strikethrough‖{text}‖end‖";

    }

    /// <summary>
    /// Provides methods for binding hyperlinks to GUI text blocks and joining enumerable items to rich strings.
    /// </summary>
    /// <remarks>
    /// Contains extension methods for creating rich text strings with clickable hyperlinks and for binding
    /// those hyperlinks to GUI components's click areas.
    /// </remarks>
    public static class HyperlinkExtensions
    {
        /// <summary>
        /// Joins an enumerable of items into a single <see cref="RichString"/>, applying color formatting to each item.
        /// </summary>
        /// <typeparam name="T">The type of items in the enumerable.</typeparam>
        /// <param name="items">The items to join.</param>
        /// <param name="separator">The separator string between items.</param>
        /// <param name="textSelector">A function that selects the text for each item.</param>
        /// <param name="colorSelector">A function that selects the color for each item.</param>
        /// <returns>A <see cref="RichString"/> containing all items with color formatting applied.</returns>
        /// <remarks>
        /// Each item's text is formatted with its corresponding color using the <c>RichString.SetColor(string)</c>
        /// pattern. The ‖ symbol is used as the RichText color tag delimiter. The original ‖ characters in the text
        /// are removed (replaced with empty string) to avoid breaking the RichText parser.
        /// </remarks>
        public static RichString JoinToRichString<T>(
                    this IEnumerable<T> items,
                    string separator,
                    Func<T, string> textSelector,
                    Func<T, Color> colorSelector)
        {
            var sb = new System.Text.StringBuilder();
            var list = items.ToList();

            for (int i = 0; i < list.Count; i++)
            {
                var item = list[i];
                Color color = colorSelector(item);
                string text = textSelector(item).Replace("‖", "");

                // Formateo simple por color.
                sb.Append(text.SetColor(color));

                if (i < list.Count - 1) sb.Append(separator);
            }

            return RichString.Rich(sb.ToString());
        }

        /// <summary>
        /// Binds clickable hyperlinks to a <see cref="GUITextBlock"/> from an enumerable of items.
        /// </summary>
        /// <typeparam name="T">The type of items.</typeparam>
        /// <param name="textBlock">The text block to which click areas will be added.</param>
        /// <param name="items">The items to bind hyperlinks for.</param>
        /// <param name="onPrimaryClick">The action to invoke when a hyperlink is primary-clicked.</param>
        /// <param name="onSecondaryClick">Optional action to invoke when a hyperlink is secondary-clicked.</param>
        /// <remarks>
        /// The method iterates over the RichTextData of the text block and adds clickable areas corresponding to
        /// each item. Clickable areas store the data and invoke the appropriate click handlers. If
        /// <paramref name="onSecondaryClick"/> is not provided, secondary clicks are ignored.
        /// </remarks>
        public static void BindHyperlinks<T>(
                    this GUITextBlock textBlock,
                    IEnumerable<T> items,
                    Action<T> onPrimaryClick,
                    Action<T>? onSecondaryClick = null)
        {
            var list = items.ToList();

            void ApplyLinks()
            {
                if (textBlock.RichTextData == null) return;
                textBlock.ClickableAreas.Clear();

                int index = 0;
                foreach (var data in textBlock.RichTextData)
                {
                    if (data.StartIndex >= data.EndIndex || data.StartIndex < 0 || data.Color == null) continue;
                    if (index >= list.Count) break;

                    var target = list[index];
                    textBlock.ClickableAreas.Add(new GUITextBlock.ClickableArea()
                    {
                        Data = data,
                        OnClick = (tb, area) => { onPrimaryClick?.Invoke(target); },
                        OnSecondaryClick = onSecondaryClick != null ? ((tb, area) => { onSecondaryClick.Invoke(target); }) : null
                    });
                    index++;
                }
            }

            ApplyLinks();
            textBlock.RectTransform.SizeChanged += ApplyLinks;
        }
    }

    // This Class has been generated by AI, does not affect the copyright or copyleft.
    /// <summary>
    /// Provides syntax highlighting for XML code strings, coloring nodes, attributes, values, comments, and punctuation.
    /// </summary>
    /// <remarks>
    /// Uses regular expressions to identify and color different parts of XML syntax. The coloring follows a "Dark Theme"
    /// style palette. Note that color tags (‖color:...‖) are protected from being replaced by the punctuation regex.
    /// </remarks>
    public static partial class XMLHighlighter
    {
        // Syntax colors (IDE "Dark Theme" style palette)
        private static readonly Color ColNode = Color.CornflowerBlue;   // <Item>
        private static readonly Color ColAttr = Color.LightSkyBlue;     // identifier=
        private static readonly Color ColValue = Color.LightSalmon;     // "steel"
        private static readonly Color ColComment = Color.DarkSeaGreen;  // <!-- comment -->
        private static readonly Color ColPunctuation = Color.LightGray; // < > / =

        /// <summary>
        /// Formats an XML string with syntax highlighting colors.
        /// </summary>
        /// <param name="rawXml">The raw XML string to format. If null or whitespace, returns an empty RichString.</param>
        /// <returns>A <see cref="RichString"/> with syntax highlighting colors applied.</returns>
        /// <remarks>
        /// The formatting performs the following steps:
        /// 1. Escapes the ‖ RichText character to || to avoid parser conflicts.
        /// 2. Highlights string values (text between quotes) using the ColValue color.
        /// 3. Highlights attributes (identifier=) using the ColAttr color.
        /// 4. Highlights node names (&lt;Node&gt;) using the ColNode color.
        /// 5. Highlights punctuation (&lt; &gt; / =) using the ColPunctuation color.
        ///     - Note: To avoid replacing our own color tags (‖color:Hex‖), the regex will not touch anything between ‖ symbols.
        /// 6. Highlights comments (&lt;!-- ... --&gt;) using the ColComment color, overwriting any internal colors.
        /// 
        /// The coloring uses a "Dark Theme" style palette defined as private static readonly fields:
        /// - ColNode: CornflowerBlue (for node names)
        /// - ColAttr: LightSkyBlue (for attributes)
        /// - ColValue: LightSalmon (for string values)
        /// - ColComment: DarkSeaGreen (for comments)
        /// - ColPunctuation: LightGray (for punctuation)
        /// 
        /// Example usage:
        /// <code>
        /// var formatted = XMLHighlighter.FormatToXMLCode("&lt;Item identifier=\"test\"&gt;value&lt;/Item&gt;");
        /// </code>
        /// </remarks>
        public static RichString FormatToXMLCode(this string rawXml)
        {
            if (string.IsNullOrWhiteSpace(rawXml)) return RichString.Rich("");

            // 1. Scape Barotrauma RichText characters (the ‖ symbol)
            // If the raw XML had this symbol for some reason, it would break the parser.
            string safeXml = rawXml.Replace("‖", "||");

            // 2. Highlight Strings (Values between quotes)
            safeXml = RegexValue().Replace(safeXml, match
                => match.Value.SetColor(ColValue));

            // 3. Highlight Attributes
            safeXml = RegexAttribute().Replace(safeXml, match
                => match.Value.SetColor(ColAttr));

            // 4. Highlight Node Names (<Node)
            safeXml = RegexNodeName().Replace(safeXml, match
                => match.Value.SetColor(ColNode));

            // 5. Highlight Punctuation (Angles and equals signs)
            // NOTE: To avoid replacing our own color tags (‖color:Hex‖), 
            // the regex will not touch anything between ‖ symbols.
            // A safer way is to do punctuation first, but it interferes with HTML.
            // To simplify, we color the basic punctuation.
            safeXml = RegexPunctuation().Replace(safeXml, match
                => match.Value.SetColor(ColPunctuation));

            // 6. Highlight Comments (They have priority and overwrite any internal color)
            safeXml = RegexComment().Replace(safeXml, match
                => CleanComment().Replace(match.Value, "").SetColor(ColComment));

            return safeXml.Rich();
        }

        [GeneratedRegex(@"<!--[\s\S]*?-->", RegexOptions.Compiled)]
        private static partial Regex RegexComment();
        [GeneratedRegex(@"(?<=<|</)[a-zA-Z0-9_\-]+", RegexOptions.Compiled)]
        private static partial Regex RegexNodeName();
        [GeneratedRegex(@"([a-zA-Z0-9_\-]+)(?=\s*=)", RegexOptions.Compiled)]
        private static partial Regex RegexAttribute();
        [GeneratedRegex(@"""[^""]*""", RegexOptions.Compiled)]
        private static partial Regex RegexValue();
        [GeneratedRegex(@"<|>|/|=", RegexOptions.Compiled)]
        private static partial Regex RegexPunctuation();
        [GeneratedRegex(@"‖color:[^‖]+‖|‖color:end‖")]
        private static partial Regex CleanComment();
    }
    // End of AI Code.

    /// <summary>
    /// Provides extension methods for floating-point number formatting and conversion.
    /// </summary>
    /// <remarks>
    /// Methods include conversion to meter strings, value strings with optional decimal places,
    /// and signed value formatting with prefix characters (+, -, space).
    /// </remarks>
    internal static class FloatExt
    {
        /// <summary>
        /// Converts a float value to a meter string (value / 10 with "m" suffix).
        /// </summary>
        /// <param name="value">The float value to convert.</param>
        /// <returns>A string in the format "X.Xm" (e.g., "5.0m" for a value of 50).</returns>
        /// <remarks>
        /// The value is divided by 10 to convert from the game's internal unit to meters.
        /// </remarks>
        internal static string ToMeters(this float value) => (value / 10f).ToValue() + 'm';

        /// <summary>
        /// Converts a float value to a string with up to 3 decimal places.
        /// </summary>
        /// <param name="value">The float value to convert.</param>
        /// <returns>A string representation of the value with up to 3 decimal places (e.g., "5.123").</returns>
        /// <remarks>
        /// Uses the format string "0.###" which shows up to 3 decimal places, removing trailing zeros.
        /// </remarks>
        internal static string ToValue(this float value) => value.ToString("0.###");

        /// <summary>
        /// Converts a float value to a signed string with a prefix character.
        /// </summary>
        /// <param name="value">The float value to convert.</param>
        /// <returns>A string with a prefix of "+" (positive), "-" (negative), or " " (zero), followed by the value string.</returns>
        /// <remarks>
        /// The prefix character indicates the sign of the value. The value part uses <see cref="ToValue"/> for formatting.
        /// </remarks>
        internal static string ToSignedValue(this float value) => ((value > 0) ? '+' : (value < 0) ? '-' : ' ') + value.ToValue();
    }

    /// <summary>
    /// Provides extension methods for working with prefabs, including name resolution, icon retrieval,
    /// and config element access.
    /// </summary>
    /// <remarks>
    /// These methods are useful for modders who need to display prefab information in custom UI.
    /// The SafeName method handles null prefabs and provides default colors/text for missing data.
    /// </remarks>
    internal static class PrefabExt
    {

        /// <summary>
        /// Gets the safe name and text color for a prefab, handling null values and missing data.
        /// </summary>
        /// <param name="prefab">The prefab to get the name for. Can be null.</param>
        /// <param name="defaultColor">The default color to use if the prefab has no name or identifier.</param>
        /// <returns>A tuple containing the display name and text color.</returns>
        /// <remarks>
        /// If the prefab is null, returns the default name "???" in the default color.
        /// If the prefab has an empty name, the identifier is shown in brackets with red color.
        /// Otherwise, the prefab's name value is used with the default color.
        /// </remarks>
        public static (string Name, Color TextColor) SafeName(this Prefab? prefab, Color defaultColor)
        {
            return prefab switch
            {
                ItemPrefab item => item.Name.IsNullOrEmpty()
                                        ? ($"[{item.Identifier}]", Color.Red)
                                        : (item.Name.Value, defaultColor),
                AfflictionPrefab affliction => affliction.Name.IsNullOrEmpty()
                                        ? ($"[{affliction.Identifier}]", Color.Red)
                                        : (affliction.Name.Value, defaultColor),
                _ => (Texts.Get("sos.gen.unknown", "???").Value, defaultColor),
            };
        }
        /// <summary>
        /// Gets the display name for a prefab.
        /// </summary>
        /// <param name="prefab">The prefab to get the name for.</param>
        /// <returns>The name of the prefab, or the identifier as a string if the name is not available.</returns>
        public static string Name(this Prefab prefab)
        {
            return prefab switch
            {
                ItemPrefab item => item.Name.ToString(),
                AfflictionPrefab affliction => affliction.Name.ToString(),
                _ => prefab.Identifier.ToString()
            };
        }
        /// <summary>
        /// Gets the icon sprite for a prefab.
        /// </summary>
        /// <param name="prefab">The prefab to get the icon for. Can be null.</param>
        /// <returns>The inventory icon sprite for items, the affliction icon for afflictions, or null for other types.</returns>
        /// <remarks>
        /// For <see cref="ItemPrefab"/>, prefers the inventory icon, falling back to the sprite.
        /// For <see cref="AfflictionPrefab"/>, returns the Icon property.
        /// Returns null for other prefab types or if the prefab is null.
        /// </remarks>
        public static Sprite? Icon(this Prefab? prefab)
        {
            return prefab switch
            {
                ItemPrefab item => item.InventoryIcon ?? item.sprite,
                AfflictionPrefab affliction => affliction.Icon,
                _ => null
            };
        }
        /// <summary>
        /// Gets the icon color for a prefab.
        /// </summary>
        /// <param name="prefab">The prefab to get the icon color for. Can be null.</param>
        /// <returns>The inventory icon color for items, the first icon color for afflictions, or white for other types.</returns>
        /// <remarks>
        /// For <see cref="ItemPrefab"/>, returns the InventoryIconColor.
        /// For <see cref="AfflictionPrefab"/>, returns the first color from IconColors or White.
        /// Returns White for other prefab types or if the prefab is null.
        /// </remarks>
        public static Color IconColor(this Prefab? prefab)
        {
            return prefab switch
            {
                ItemPrefab item => item.InventoryIconColor,
                AfflictionPrefab affliction => affliction.IconColors?.FirstOrDefault(Color.White),
                _ => null
            } ?? Color.White;
        }

        /// <summary>
        /// Gets the configuration XML element for a prefab.
        /// </summary>
        /// <param name="prefab">The prefab to get the config element for.</param>
        /// <returns>The ConfigElement for items, the configElement for afflictions, or null for other types.</returns>
        /// <remarks>
        /// For <see cref="ItemPrefab"/>, returns the ConfigElement property.
        /// For <see cref="AfflictionPrefab"/>, returns the configElement field.
        /// Returns null for other prefab types.
        /// </remarks>
        public static ContentXElement? ConfigElement(this Prefab prefab)
        {
            return prefab switch
            {
                ItemPrefab item => item.ConfigElement,
                AfflictionPrefab affliction => affliction.configElement,
                _ => null
            };
        }
    }

    /// <summary>
    /// Provides extension methods for <see cref="Type"/>.
    /// </summary>
    /// <remarks>
    /// Currently provides a method to get the full name or short name of a type.
    /// </remarks>
    internal static class TypeExt
    {
        /// <summary>
        /// Gets the full name of a type, or the short name if the full name is null.
        /// </summary>
        /// <param name="type">The type to get the name for.</param>
        /// <returns>The full name of the type, or the short name if the full name is null.</returns>
        /// <remarks>
        /// This is a safe way to get a type name for logging or display purposes, as some types
        /// may have a null <see cref="Type.FullName"/>.
        /// </remarks>
        internal static string FullOrName(this Type type) => type.FullName ?? type.Name;
    }

    /// <summary>
    /// Provides extension methods for <see cref="IEnumerable{T}"/>.
    /// </summary>
    /// <remarks>
    /// Currently provides a method to join items into a CSV string.
    /// </remarks>
    public static class IEnumerableExt
    {
        /// <summary>
        /// Joins the elements of a collection into a comma-separated string.
        /// </summary>
        /// <typeparam name="T">The type of elements in the collection.</typeparam>
        /// <param name="collection">The collection to join.</param>
        /// <param name="separator">The separator character to use. Defaults to ','.</param>
        /// <returns>A string containing all elements joined by the separator.</returns>
        /// <remarks>
        /// Uses <c>string.Join(char, IEnumerable{object})</c> internally. Each element's ToString()
        /// method is called to get its string representation.
        /// </remarks>
        public static string ToCsv<T>(this IEnumerable<T> collection, char separator = ',')
        {
            return string.Join(separator, collection);
        }
    }

    /// <summary>
    /// Provides extension methods for <see cref="IDictionary{TKey, TValue}"/>.
    /// </summary>
    /// <remarks>
    /// Currently provides a thread-safe method to get a value by key.
    /// </remarks>
    public static class IDictionaryExt
    {
        /// <summary>
        /// Gets a value from a dictionary in a thread-safe manner.
        /// </summary>
        /// <typeparam name="S">The key type. Must not be null.</typeparam>
        /// <typeparam name="T">The value type.</typeparam>
        /// <param name="dict">The dictionary to look up the value in.</param>
        /// <param name="key">The key to look up.</param>
        /// <returns>The value associated with the key, or the default value for <typeparamref name="T"/> if not found.</returns>
        /// <remarks>
        /// Acquires a lock on the dictionary before performing the lookup, ensuring thread safety
        /// when multiple threads access the same dictionary.
        /// </remarks>
        public static T? GetValueLocked<S, T>(this IDictionary<S, T> dict, S key) where S : notnull
        {
            lock (dict)
                if (dict.TryGetValue(key, out var value))
                    return value;
            return default;
        }
    }

    /// <summary>
    /// Provides extension methods for <see cref="ISettingBase{T}"/> and <see cref="ISettingControl"/>.
    /// </summary>
    /// <remarks>
    /// Provides a SetIfNotEqual method that only sets the value if it's different from the current value,
    /// preventing unnecessary change events and saves.
    /// </remarks>
    public static class ISettingBaseExt
    {
        /// <summary>
        /// Sets the setting value only if it differs from the current value.
        /// </summary>
        /// <typeparam name="T">The setting value type. Must implement <see cref="IEquatable{T}"/> and <see cref="IConvertible"/>.</typeparam>
        /// <param name="setting">The setting to update.</param>
        /// <param name="value">The new value to set.</param>
        /// <returns><c>true</c> if the value was changed; <c>false</c> if the value was already equal to the current value.</returns>
        /// <remarks>
        /// Uses <see cref="IEquatable{T}.Equals(T)"/> to compare the current value with the new value.
        /// Only calls <see cref="ISettingBase{T}.TrySetValue(T)"/> if the values differ.
        /// </remarks>
        public static bool SetIfNotEqual<T>([NotNullWhen(false)] this ISettingBase<T> setting, T value) where T : IEquatable<T>, IConvertible
                    => (!setting.Value?.Equals(value) ?? true) && setting.TrySetValue(value);

        /// <summary>
        /// Sets the key or mouse binding only if it differs from the current value.
        /// </summary>
        /// <param name="setting">The setting to update.</param>
        /// <param name="value">The new key or mouse value to set.</param>
        /// <returns><c>true</c> if the value was changed; <c>false</c> if the value was already equal to the current value.</returns>
        /// <remarks>
        /// Uses <see cref="IEquatable{T}.Equals(T)"/> to compare the current value with the new value.
        /// Only calls <see cref="ISettingControl.TrySetValue(KeyOrMouse)"/> if the values differ.
        /// </remarks>
        public static bool SetIfNotEqual([NotNullWhen(false)] this ISettingControl setting, KeyOrMouse value)
                    => (!setting.Value?.Equals(value) ?? true) && setting.TrySetValue(value);
    }
}