// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using Barotrauma;
using Microsoft.Xna.Framework;

namespace SOS.Prefabs
{
    /// <summary>
    /// Provides static methods for managing favorite prefabs.
    /// </summary>
    /// <remarks>
    /// Maintains a <see cref="HashSet{T}"/> of favorite prefab identifiers. Provides methods for adding,
    /// removing, and toggling favorites. Optionally emits a <see cref="CommKeys.RefreshSearch"/> event
    /// after modifications to notify UI components of changes.
    /// </remarks>
    public static class PrefabHelper
    {
        private static readonly HashSet<string> favorites = [];

        /// <summary>
        /// Gets the read-only collection of favorite prefab identifiers.
        /// </summary>
        /// <returns>A read-only collection containing the identifiers of all favorited prefabs.</returns>
        /// <remarks>
        /// The underlying storage is a <see cref="HashSet{T}"/>, ensuring unique identifiers and O(1) lookup.
        /// </remarks>
        public static IReadOnlyCollection<string> Favorites => favorites;

        /// <summary>
        /// Checks if a prefab identifier is in the favorites collection.
        /// </summary>
        /// <param name="id">The prefab identifier to check.</param>
        /// <returns><c>true</c> if the identifier is in favorites; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// Performs an O(1) lookup in the underlying <see cref="HashSet{T}"/>.
        /// </remarks>
        public static bool IsFavorite(string id) => favorites.Contains(id);

        /// <summary>
        /// Adds a prefab identifier to the favorites collection.
        /// </summary>
        /// <param name="id">The prefab identifier to add.</param>
        /// <param name="emit">If <c>true</c>, emits a <see cref="CommKeys.RefreshSearch"/> event after adding.</param>
        /// <returns><c>true</c> if the identifier was added; <c>false</c> if it was already in favorites.</returns>
        /// <remarks>
        /// If the identifier is already in favorites, the method returns <c>false</c> and no event is emitted.
        /// </remarks>
        public static bool AddFavorite(string id, bool emit = true)
        {
            var result = favorites.Add(id);
            if (emit) API.Emit(CommKeys.RefreshSearch);
            return result;
        }

        /// <summary>
        /// Adds multiple prefab identifiers to the favorites collection.
        /// </summary>
        /// <param name="ids">The prefab identifiers to add.</param>
        /// <param name="emit">If <c>true</c>, emits a <see cref="CommKeys.RefreshSearch"/> event after adding.</param>
        /// <returns><c>true</c> if at least one identifier was added; <c>false</c> if all were already in favorites.</returns>
        /// <remarks>
        /// Adds each identifier individually. The event is emitted only once if <paramref name="emit"/> is <c>true</c>
        /// and at least one identifier was successfully added.
        /// </remarks>
        public static bool AddRangeFavorite(IEnumerable<string> ids, bool emit = true)
        {
            var result = false;
            foreach (var id in ids)
                result |= favorites.Add(id);
            if (emit) API.Emit(CommKeys.RefreshSearch);
            return result;
        }

        /// <summary>
        /// Removes a prefab identifier from the favorites collection.
        /// </summary>
        /// <param name="id">The prefab identifier to remove.</param>
        /// <param name="emit">If <c>true</c>, emits a <see cref="CommKeys.RefreshSearch"/> event after removing.</param>
        /// <returns><c>true</c> if the identifier was removed; <c>false</c> if it was not in favorites.</returns>
        /// <remarks>
        /// If the identifier is not in favorites, the method returns <c>false</c> and no event is emitted.
        /// </remarks>
        public static bool RemoveFavorite(string id, bool emit = true)
        {
            var result = favorites.Remove(id);
            if (emit) API.Emit(CommKeys.RefreshSearch);
            return result;
        }

        /// <summary>
        /// Toggles a prefab identifier in the favorites collection.
        /// </summary>
        /// <param name="id">The prefab identifier to toggle.</param>
        /// <param name="emit">If <c>true</c>, emits a <see cref="CommKeys.RefreshSearch"/> event after toggling.</param>
        /// <returns><c>true</c> if the identifier was added (was not a favorite); <c>false</c> if it was removed (was a favorite).</returns>
        /// <remarks>
        /// If the identifier is currently a favorite, it is removed; otherwise, it is added.
        /// </remarks>
        public static bool ToggleFavorite(string id, bool emit = true)
        {
            bool isFav = favorites.Contains(id);
            if (isFav) RemoveFavorite(id, emit); else AddFavorite(id, emit);
            return !isFav;
        }

        /// <summary>
        /// Clears all favorite prefab identifiers.
        /// </summary>
        /// <param name="emit">If <c>true</c>, emits a <see cref="CommKeys.RefreshSearch"/> event after clearing.</param>
        /// <remarks>
        /// Removes all identifiers from the favorites collection. The event is emitted if <paramref name="emit"/> is <c>true</c>.
        /// </remarks>
        public static void ClearFavorites(bool emit = true)
        {
            favorites.Clear();
            if (emit) API.Emit(CommKeys.RefreshSearch);
        }

        /// <summary>
        /// Selects a target prefab by emitting <see cref="CommKeys.SelectTarget"/>.
        /// </summary>
        /// <param name="target">The prefab target to select, or <c>null</c> to clear selection.</param>
        /// <remarks>
        /// Emits <see cref="CommKeys.SelectTarget"/> only if the target differs from the current API state.
        /// </remarks>
        public static void SelectTarget(Prefab? target)
        {
            var cur = API.GetState<Prefab?>(CommKeys.SelectTarget);
            if (cur != target)
                API.Emit(CommKeys.SelectTarget, target);
        }

        /// <summary>
        /// Opens a context menu for the target prefab.
        /// </summary>
        /// <param name="target">The prefab to open the context menu for.</param>
        /// <param name="position">Optional mouse position. Defaults to <see cref="PlayerInput.MousePosition"/>.</param>
        /// <remarks>
        /// Collects context options from all <see cref="ISOSPrefab"/> instances whose
        /// <see cref="ISOSPrefab.PrefabType"/> is assignable from <paramref name="target"/>'s type,
        /// then creates a <see cref="GUIContextMenu"/> with those options.
        /// Returns immediately if no options are available.
        /// </remarks>
        public static void OpenContextMenu(Prefab target, Vector2? position = null)
        {
            if (target == null) return;
            var options = API.GetAllPrefabProviders()
                .Where(p => p.PrefabType.IsAssignableFrom(target.GetType()))
                .SelectMany(p => p.BuildContextOptions(target))
                .ToList();
            if (options.Count == 0) return;
            RichString name = target.Name();
            _ = GUIContextMenu.CreateContextMenu(position ?? PlayerInput.MousePosition, name, null, [.. options]);
        }
    }
}
