// Copyright (c) 2026 Retype15
// This file is licensed under the GNU GPLv3.
// See the LICENSE file in the project root for details.
// All documentation was generated by AI. Revised, but may still contain errors.

#pragma warning disable IDE0130
#pragma warning disable IDE0290

using Barotrauma;

namespace SOS
{
    /// <summary>
    /// Provides localized text lookup with fallback support for S.O.S mod.
    /// </summary>
    /// <remarks>
    /// Texts are resolved via <see cref="TextManager.Get(string)"/> with an optional fallback string.
    /// In DEBUG mode, fallbacks are prefixed with "[NT]" (NOT-TRANSLATED) to identify missing translations.
    /// The result is cached by prefix for performance via <see cref="GetTranslationsByPrefix"/>.
    /// </remarks>
    /// <example>
    /// <code>
    /// // Basic usage with fallback
    /// var text = Texts.Get("sos.some_key", "Fallback text if not found");
    ///
    /// // Get all translations starting with a prefix
    /// var translations = Texts.GetTranslationsByPrefix("sos.");
    /// </code>
    /// </example>
    public static class Texts
    {
        private static readonly Dictionary<string, Dictionary<Identifier, string>> prefixCache = [];

        /// <summary>
        /// Gets a localized string by key with an optional fallback.
        /// </summary>
        /// <param name="key">The localization key to look up.</param>
        /// <param name="fallback">The fallback string to use if the key is not found.</param>
        /// <param name="forceFallback">If <c>true</c>, returns <paramref name="fallback"/> directly without lookup.</param>
        /// <returns>
        /// The localized string if found; otherwise <paramref name="fallback"/> (prefixed with "[NT]" in DEBUG).
        /// </returns>
        /// <remarks>
        /// In DEBUG builds, missing translations are prefixed with "[NT]" to highlight untranslated content.
        /// In RELEASE builds, the raw fallback is returned without the prefix.
        /// If <paramref name="fallback"/> is <c>null</c> or empty, returns the result from
        /// <see cref="TextManager.Get(string)"/> directly.
        /// </remarks>
        public static LocalizedString Get(string key, string fallback = "", bool forceFallback = false)
        {
            var text = TextManager.Get(key);

            if (!string.IsNullOrEmpty(fallback))
            {
                if (forceFallback) return fallback;
#if DEBUG
                return text.Fallback("[NT]" + fallback); // NT=NOT-TRANSLATED
#else
                return text.Fallback(fallback);
#endif
            }
            return text;
        }

        /// <summary>
        /// Gets all translations matching the specified prefix, with caching.
        /// </summary>
        /// <param name="prefix">The key prefix to filter translations by.</param>
        /// <returns>
        /// A dictionary mapping localization keys (<see cref="Identifier"/>) to their translated values,
        /// filtered to keys that start with <paramref name="prefix"/>.
        /// </returns>
        /// <remarks>
        /// Results are cached in <see cref="prefixCache"/> for subsequent calls with the same prefix.
        /// The cache is populated by querying <see cref="TextManager.GetAllTagTextPairs"/> on first access.
        /// Returns an empty dictionary if no translations match the prefix.
        /// </remarks>
        public static Dictionary<Identifier, string> GetTranslationsByPrefix(string prefix)
        {
            if (prefixCache.TryGetValue(prefix, out var cached)) return cached;

            var allTranslations = TextManager.GetAllTagTextPairs();
            var filtered = allTranslations
                .Where(kvp => kvp.Key.StartsWith(prefix))
                .ToDictionary(kvp => kvp.Key, kvp => kvp.Value);

            prefixCache[prefix] = filtered;
            return filtered;
        }
    }
}